use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

#[derive(Clone, Debug)]
struct SourceIcon {
    icon: String,
    color: String,
    name: String,
}

#[derive(Clone, Debug)]
struct GeneratedIcon {
    key: String,
    icon: String,
    name: String,
    dark: (u8, u8, u8),
    light: (u8, u8, u8),
}

pub(crate) fn run(args: Vec<String>) {
    let source = args
        .first()
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("/tmp/nvim-web-devicons"));
    let repo = source.join("lua/nvim-web-devicons");
    let dark_ext = parse_table(&repo.join("default/icons_by_file_extension.lua"));
    let dark_name = parse_table(&repo.join("default/icons_by_filename.lua"));
    let light_ext = parse_table(&repo.join("light/icons_by_file_extension.lua"));
    let light_name = parse_table(&repo.join("light/icons_by_filename.lua"));

    let extension_icons = merge_icons(dark_ext, light_ext);
    let filename_icons = merge_icons(dark_name, light_name);
    let out = render_generated(&extension_icons, &filename_icons);
    let path = PathBuf::from("crates/core/src/content/file_icons/generated.rs");
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .unwrap_or_else(|e| panic!("create {}: {e}", parent.display()));
    }
    std::fs::write(&path, out).unwrap_or_else(|e| panic!("write {}: {e}", path.display()));
    eprintln!(
        "generated {} extension icons and {} filename icons into {}",
        extension_icons.len(),
        filename_icons.len(),
        path.display()
    );
}

fn parse_table(path: &Path) -> BTreeMap<String, SourceIcon> {
    let text =
        std::fs::read_to_string(path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    let mut out = BTreeMap::new();
    for line in text.lines() {
        let Some(key_start) = line.find("[\"") else {
            continue;
        };
        let key_start = key_start + 2;
        let Some(key_end) = line[key_start..].find("\"]") else {
            continue;
        };
        let key = &line[key_start..key_start + key_end];
        let Some(icon) = field(line, "icon") else {
            continue;
        };
        let Some(color) = field(line, "color") else {
            continue;
        };
        let Some(name) = field(line, "name") else {
            continue;
        };
        out.insert(key.to_string(), SourceIcon { icon, color, name });
    }
    out
}

fn field(line: &str, name: &str) -> Option<String> {
    let needle = format!("{name} = \"");
    let start = line.find(&needle)? + needle.len();
    let end = line[start..].find('"')?;
    Some(line[start..start + end].to_string())
}

fn merge_icons(
    dark: BTreeMap<String, SourceIcon>,
    light: BTreeMap<String, SourceIcon>,
) -> Vec<GeneratedIcon> {
    let mut out = Vec::with_capacity(dark.len().max(light.len()));
    for (key, dark_icon) in &dark {
        let light_icon = light.get(key).unwrap_or(dark_icon);
        out.push(GeneratedIcon {
            key: key.clone(),
            icon: dark_icon.icon.clone(),
            name: dark_icon.name.clone(),
            dark: parse_hex_color(&dark_icon.color),
            light: parse_hex_color(&light_icon.color),
        });
    }
    for (key, light_icon) in light {
        if dark.contains_key(&key) {
            continue;
        }
        out.push(GeneratedIcon {
            key,
            icon: light_icon.icon,
            name: light_icon.name,
            dark: parse_hex_color(&light_icon.color),
            light: parse_hex_color(&light_icon.color),
        });
    }
    out.sort_by(|a, b| a.key.cmp(&b.key));
    out
}

fn parse_hex_color(s: &str) -> (u8, u8, u8) {
    let hex = s.strip_prefix('#').unwrap_or(s);
    assert!(hex.len() == 6, "invalid color {s}");
    let r = u8::from_str_radix(&hex[0..2], 16).unwrap();
    let g = u8::from_str_radix(&hex[2..4], 16).unwrap();
    let b = u8::from_str_radix(&hex[4..6], 16).unwrap();
    (r, g, b)
}

fn render_generated(extension_icons: &[GeneratedIcon], filename_icons: &[GeneratedIcon]) -> String {
    let mut out = String::new();
    out.push_str(
        r#"// @generated by `cargo xtask gen-file-icons`; do not edit by hand.
//
// Icon data is generated from nvim-tree/nvim-web-devicons.
// Source: https://github.com/nvim-tree/nvim-web-devicons
//
// MIT License
//
// Copyright (c) 2023 nvim-tree
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

"#,
    );
    out.push_str("use super::IconEntry;\n\n");
    out.push_str("pub(super) const DEFAULT_ICON: IconEntry = IconEntry {\n");
    out.push_str("    key: \"__default__\",\n");
    out.push_str("    icon: \"\",\n");
    out.push_str("    name: \"Default\",\n");
    out.push_str("    dark: (0x6d, 0x80, 0x86),\n");
    out.push_str("    light: (0x6d, 0x80, 0x86),\n");
    out.push_str("};\n\n");
    render_table(&mut out, "BY_EXTENSION", extension_icons);
    out.push('\n');
    render_table(&mut out, "BY_FILENAME", filename_icons);
    out
}

fn render_table(out: &mut String, name: &str, icons: &[GeneratedIcon]) {
    out.push_str(&format!("pub(super) const {name}: &[IconEntry] = &[\n"));
    for icon in icons {
        out.push_str("    IconEntry { ");
        out.push_str(&format!("key: {:?}, ", icon.key));
        out.push_str(&format!("icon: {:?}, ", icon.icon));
        out.push_str(&format!("name: {:?}, ", icon.name));
        out.push_str(&format!(
            "dark: (0x{:02x}, 0x{:02x}, 0x{:02x}), ",
            icon.dark.0, icon.dark.1, icon.dark.2
        ));
        out.push_str(&format!(
            "light: (0x{:02x}, 0x{:02x}, 0x{:02x}) ",
            icon.light.0, icon.light.1, icon.light.2
        ));
        out.push_str("},\n");
    }
    out.push_str("];\n");
}
