[package]
name = "smelt-lua-doc-derive"
version = "0.5.0-alpha.9"
edition = "2021"
rust-version.workspace = true
description = "Proc macros for declaring Lua-side types from Rust structs/enums (smelt internal)"

[lib]
name = "lua_doc_derive"
proc-macro = true

[dependencies]
syn = "2"
quote = "1"
proc-macro2 = "1"

