-- `/settings` — every key in `smelt.settings.schema()` shows up here:
--   * bool                   → Enter toggles
--   * string with `choices`  → Enter cycles to the next choice
--   * number                 → shown read-only; tune via init.lua, `--set`,
--                              or `smelt.settings.<key> = N`
--
-- Toggles apply to the current session only — `init.lua` is the only
-- persistence path. After each change the picker prints the exact
-- `smelt.settings.<key> = ...` line to paste into `init.lua`.
--
-- The list is schema-driven on purpose. Every newly declared setting in
-- `smelt_core::config::SETTINGS` shows up here automatically — no hand
-- list to keep in sync.

local function humanise(key)
  return (key:gsub("_", " "))
end

local function describe(row)
  local v = smelt.settings[row.key]
  if row.kind == "bool" then
    return v and "on" or "off"
  end
  return tostring(v)
end

local function next_choice(choices, current)
  for i, c in ipairs(choices) do
    if c == current then return choices[(i % #choices) + 1] end
  end
  return choices[1]
end

local function snippet_for(key, value)
  if type(value) == "string" then
    return string.format("smelt.settings.%s = %q", key, value)
  end
  return string.format("smelt.settings.%s = %s", key, tostring(value))
end

local function notify_session_only(key)
  smelt.notify(
    "session only — add `" .. snippet_for(key, smelt.settings[key]) .. "` to init.lua to persist"
  )
end

local function build_items()
  local items = {}
  for _, row in ipairs(smelt.settings.schema()) do
    items[#items + 1] = {
      label        = humanise(row.key),
      description  = describe(row),
      search_terms = row.key,
      _row         = row,
    }
  end
  return items
end

smelt.cmd.picker("settings", {
  desc       = "open settings menu",
  items      = build_items,
  on_enter   = function(item)
    local row = item._row
    if not row then return end
    if row.kind == "bool" then
      smelt.settings[row.key] = not smelt.settings[row.key]
      notify_session_only(row.key)
    elseif row.kind == "string" and row.choices then
      smelt.settings[row.key] = next_choice(row.choices, smelt.settings[row.key])
      notify_session_only(row.key)
    end
    -- numbers are read-only in the picker; no-op
  end,
  stay_open  = true,
  startup_ok = true,
})

-- `/settings-export` — copy a Lua snippet of the live state (settings +
-- active theme + current model / mode / reasoning effort) to the
-- clipboard. Paste into `init.lua` to promote the current session into
-- persistent config.
local function build_snippet()
  local lines = { "-- generated by /settings-export" }
  for _, row in ipairs(smelt.settings.schema()) do
    lines[#lines + 1] = snippet_for(row.key, smelt.settings[row.key])
  end
  local defaults = {}
  local model = smelt.model and smelt.model()
  if type(model) == "string" and model ~= "" then
    defaults[#defaults + 1] = string.format("  model = %q,", model)
  end
  local mode = smelt.mode and smelt.mode()
  if type(mode) == "string" and mode ~= "" then
    defaults[#defaults + 1] = string.format("  mode = %q,", mode)
  end
  local effort = smelt.reasoning and smelt.reasoning()
  if type(effort) == "string" and effort ~= "" then
    defaults[#defaults + 1] = string.format("  reasoning_effort = %q,", effort)
  end
  if #defaults > 0 then
    lines[#lines + 1] = "smelt.defaults({"
    for _, line in ipairs(defaults) do
      lines[#lines + 1] = line
    end
    lines[#lines + 1] = "})"
  end
  return table.concat(lines, "\n") .. "\n"
end

smelt.cmd.register("settings-export", function()
  local snippet = build_snippet()
  smelt.clipboard.write(snippet)
  smelt.notify("settings snippet copied — paste into init.lua to persist")
end, { desc = "copy current settings as init.lua snippet" })
