//! Registration surfaces — every binding here writes to `LuaShared`
//! state that other Lua-side code reads back later: command handlers,
//! keymap chords, autocmd subscribers, deferred timers, plugin tools,
//! statusline sources, and spawned tasks.

use super::{lua_table_to_args, lua_table_to_json};
use crate::lua::{
    AutocmdEvent, LuaHandle, LuaShared, PluginToolHandles, TaskCompletion, TaskEvent,
};
use mlua::prelude::*;
use std::sync::atomic::Ordering;
use std::sync::Arc;
use std::time::Duration;

pub(super) fn register(
    lua: &Lua,
    smelt: &mlua::Table,
    smelt_keymap: &mlua::Table,
    shared: &Arc<LuaShared>,
) -> LuaResult<()> {
    register_cmd(lua, smelt, shared)?;
    register_keymap(lua, smelt_keymap, shared)?;
    register_task(lua, smelt, shared)?;
    register_tools(lua, smelt, shared)?;
    register_statusline(lua, smelt, shared)?;
    register_autocmd(lua, smelt, shared)?;
    register_timer(lua, smelt)?;
    register_spawn(lua, smelt, shared)?;
    Ok(())
}

fn register_cmd(lua: &Lua, smelt: &mlua::Table, shared: &Arc<LuaShared>) -> LuaResult<()> {
    let cmd_tbl = lua.create_table()?;
    {
        let s = shared.clone();
        cmd_tbl.set(
            "register",
            lua.create_function(
                move |lua, (name, handler, opts): (String, mlua::Function, Option<mlua::Table>)| {
                    let desc: Option<String> = opts
                        .as_ref()
                        .and_then(|t| t.get::<Option<String>>("desc").ok().flatten());
                    // `args` may be either a Lua array of strings (static) or
                    // omitted. Drives the secondary CommandArg picker that
                    // opens after `/name `.
                    let args: Vec<String> = opts
                        .as_ref()
                        .and_then(|t| t.get::<Option<mlua::Table>>("args").ok().flatten())
                        .map(|t| {
                            let mut v = Vec::new();
                            for pair in t.pairs::<mlua::Value, String>().flatten() {
                                v.push(pair.1);
                            }
                            v
                        })
                        .unwrap_or_default();
                    let key = lua.create_registry_value(handler)?;
                    if let Ok(mut map) = s.commands.lock() {
                        map.insert(
                            name,
                            crate::lua::RegisteredCommand {
                                handle: LuaHandle { key },
                                description: desc,
                                args,
                            },
                        );
                    }
                    Ok(())
                },
            )?,
        )?;
    }
    cmd_tbl.set(
        "run",
        lua.create_function(|_, line: String| {
            crate::lua::with_app(|app| app.apply_lua_command(&line));
            Ok(())
        })?,
    )?;
    {
        let s = shared.clone();
        cmd_tbl.set(
            "list",
            lua.create_function(move |lua, ()| {
                let names: Vec<String> = s
                    .commands
                    .lock()
                    .map(|m| m.keys().cloned().collect())
                    .unwrap_or_default();
                let table = lua.create_table()?;
                for (i, name) in names.iter().enumerate() {
                    table.set(i + 1, name.as_str())?;
                }
                Ok(table)
            })?,
        )?;
    }
    smelt.set("cmd", cmd_tbl)?;
    Ok(())
}

fn register_keymap(
    lua: &Lua,
    smelt_keymap: &mlua::Table,
    shared: &Arc<LuaShared>,
) -> LuaResult<()> {
    // smelt.keymap.help_sections() — reads the layered binding help
    // generated by `crate::keymap::hints` so plugins (notably /help)
    // share the same source of truth as built-in help.
    let keymap_tbl = lua.create_table()?;
    keymap_tbl.set(
        "help_sections",
        lua.create_function(|lua, ()| {
            let vim_enabled =
                crate::lua::try_with_app(|app| app.input.vim_enabled()).unwrap_or(false);
            let sections = crate::keymap::hints::help_sections(vim_enabled);
            let out = lua.create_table()?;
            for (i, (title, entries)) in sections.into_iter().enumerate() {
                let row = lua.create_table()?;
                row.set("title", title)?;
                let entries_tbl = lua.create_table()?;
                for (j, (label, detail)) in entries.into_iter().enumerate() {
                    let entry = lua.create_table()?;
                    entry.set("label", label)?;
                    entry.set("detail", detail)?;
                    entries_tbl.set(j + 1, entry)?;
                }
                row.set("entries", entries_tbl)?;
                out.set(i + 1, row)?;
            }
            Ok(out)
        })?,
    )?;
    smelt_keymap.set("help", keymap_tbl.get::<mlua::Function>("help_sections")?)?;

    {
        let s = shared.clone();
        smelt_keymap.set(
            "set",
            lua.create_function(
                move |lua, (mode, chord, handler): (String, String, mlua::Function)| {
                    // Canonicalize at registration so `"normal"` / `"n"` /
                    // `""` and `"c-r"` / `"<C-r>"` / `"<c-r>"` all land as
                    // the same lookup key as the dispatcher produces from
                    // a crossterm KeyEvent. Unknown mode or chord → raise
                    // immediately, not silent miss at dispatch.
                    let canonical_mode = crate::lua::normalize_mode(&mode).ok_or_else(
                        || {
                            LuaError::RuntimeError(format!(
                                "keymap.set: unknown mode `{mode}` (expected \"n\"|\"i\"|\"v\"|\"\" or \"normal\"|\"insert\"|\"visual\")"
                            ))
                        },
                    )?;
                    let canonical_chord = crate::lua::canonicalize_chord(&chord)
                        .ok_or_else(|| {
                            LuaError::RuntimeError(format!(
                                "keymap.set: unknown chord `{chord}`"
                            ))
                        })?;
                    let key = lua.create_registry_value(handler)?;
                    if let Ok(mut map) = s.keymaps.lock() {
                        map.insert((canonical_mode, canonical_chord), LuaHandle { key });
                    }
                    Ok(())
                },
            )?,
        )?;
    }
    Ok(())
}

fn register_task(lua: &Lua, smelt: &mlua::Table, shared: &Arc<LuaShared>) -> LuaResult<()> {
    let task_tbl = lua.create_table()?;
    {
        let s = shared.clone();
        task_tbl.set(
            "alloc",
            lua.create_function(move |_, ()| {
                Ok(s.next_external_id.fetch_add(1, Ordering::Relaxed))
            })?,
        )?;
    }
    {
        let s = shared.clone();
        task_tbl.set(
            "resume",
            lua.create_function(move |lua, (id, value): (u64, mlua::Value)| {
                let key = lua.create_registry_value(value)?;
                if let Ok(mut inbox) = s.task_inbox.lock() {
                    inbox.push(TaskEvent::ExternalResolved {
                        external_id: id,
                        value: key,
                    });
                }
                Ok(())
            })?,
        )?;
    }
    smelt.set("task", task_tbl)?;
    Ok(())
}

fn register_tools(lua: &Lua, smelt: &mlua::Table, shared: &Arc<LuaShared>) -> LuaResult<()> {
    let tools_tbl = lua.create_table()?;
    let s = shared.clone();
    let tools_register = lua.create_function(move |lua, def: mlua::Table| {
        let name: String = def.get("name")?;
        let handler: mlua::Function = def.get("execute")?;
        let key = lua.create_registry_value(handler)?;

        // Optional permission hooks. When present, the engine asks
        // the TUI to evaluate them before deciding Allow / Deny / Ask.
        let needs_confirm_handle = def
            .get::<mlua::Function>("needs_confirm")
            .ok()
            .map(|f| lua.create_registry_value(f).map(|key| LuaHandle { key }))
            .transpose()?;
        let approval_patterns_handle = def
            .get::<mlua::Function>("approval_patterns")
            .ok()
            .map(|f| lua.create_registry_value(f).map(|key| LuaHandle { key }))
            .transpose()?;
        let preflight_handle = def
            .get::<mlua::Function>("preflight")
            .ok()
            .map(|f| lua.create_registry_value(f).map(|key| LuaHandle { key }))
            .transpose()?;

        let meta = lua.create_table()?;
        let desc: String = def.get("description").unwrap_or_default();
        meta.set("description", desc)?;
        if let Ok(params) = def.get::<mlua::Table>("parameters") {
            if let Ok(json_str) = serde_json::to_string(&lua_table_to_json(lua, &params)) {
                meta.set("parameters_json", json_str)?;
            }
        }
        if let Ok(modes) = def.get::<mlua::Table>("modes") {
            meta.set("modes", modes)?;
        }
        if let Ok(mode_str) = def.get::<String>("execution_mode") {
            meta.set("execution_mode", mode_str)?;
        }
        // Hook flag bits — let `plugin_tool_defs` build
        // `PluginToolHookFlags` without reaching back into the
        // handles map.
        meta.set("hook_needs_confirm", needs_confirm_handle.is_some())?;
        meta.set("hook_approval_patterns", approval_patterns_handle.is_some())?;
        meta.set("hook_preflight", preflight_handle.is_some())?;
        // override_core: explicit signal that this plugin shadows a
        // core Rust tool of the same name. The engine drops the
        // colliding core definition from the LLM schema and routes
        // dispatch to the plugin.
        let override_core: bool = def.get::<bool>("override").unwrap_or(false);
        meta.set("override_core", override_core)?;
        lua.set_named_registry_value(&format!("__pt_meta_{name}"), meta)?;

        if let Ok(mut map) = s.plugin_tools.lock() {
            map.insert(
                name,
                PluginToolHandles {
                    execute: LuaHandle { key },
                    needs_confirm: needs_confirm_handle,
                    approval_patterns: approval_patterns_handle,
                    preflight: preflight_handle,
                },
            );
        }
        Ok(())
    })?;
    tools_tbl.set("register", tools_register)?;
    {
        let s = shared.clone();
        tools_tbl.set(
            "unregister",
            lua.create_function(move |_, name: String| {
                if let Ok(mut map) = s.plugin_tools.lock() {
                    map.remove(&name);
                }
                Ok(())
            })?,
        )?;
    }
    tools_tbl.set(
        "resolve",
        lua.create_function(
            |_, (request_id, call_id, result): (u64, String, mlua::Table)| {
                let content: String = result.get("content").unwrap_or_default();
                let is_error: bool = result.get("is_error").unwrap_or(false);
                crate::lua::with_app(|app| {
                    app.engine.send(protocol::UiCommand::PluginToolResult {
                        request_id,
                        call_id,
                        content,
                        is_error,
                    })
                });
                Ok(())
            },
        )?,
    )?;
    // Internal: dispatch a `smelt.tools.call` side request to the
    // engine. The Lua wrapper in `_bootstrap.lua` mints `request_id`
    // via `smelt.task.alloc` and yields after this returns.
    tools_tbl.set(
        "__send_call",
        lua.create_function(
            |lua,
             (request_id, parent_call_id, tool_name, args): (
                u64,
                String,
                String,
                mlua::Table,
            )| {
                let arg_map = lua_table_to_args(lua, &args);
                crate::lua::with_app(|app| {
                    app.engine.send(protocol::UiCommand::CallCoreTool {
                        request_id,
                        parent_call_id,
                        tool_name,
                        args: arg_map,
                    })
                });
                Ok(())
            },
        )?,
    )?;
    smelt.set("tools", tools_tbl)?;
    Ok(())
}

fn register_statusline(lua: &Lua, smelt: &mlua::Table, shared: &Arc<LuaShared>) -> LuaResult<()> {
    let statusline_tbl = lua.create_table()?;
    {
        let s = shared.clone();
        statusline_tbl.set(
            "register",
            lua.create_function(
                move |lua, (name, handler, opts): (String, mlua::Function, Option<mlua::Table>)| {
                    let default_align_right = opts
                        .as_ref()
                        .and_then(|t| t.get::<Option<String>>("align").ok().flatten())
                        .map(|s| s == "right")
                        .unwrap_or(false);
                    let key = lua.create_registry_value(handler)?;
                    let source = crate::lua::StatusSource {
                        handle: LuaHandle { key },
                        default_align_right,
                    };
                    if let Ok(mut sources) = s.statusline_sources.lock() {
                        if let Some(existing) = sources.iter_mut().find(|(n, _)| n == &name) {
                            existing.1 = source;
                        } else {
                            sources.push((name, source));
                        }
                    }
                    Ok(())
                },
            )?,
        )?;
    }
    {
        let s = shared.clone();
        statusline_tbl.set(
            "unregister",
            lua.create_function(move |_, name: String| {
                if let Ok(mut sources) = s.statusline_sources.lock() {
                    sources.retain(|(n, _)| n != &name);
                }
                Ok(())
            })?,
        )?;
    }
    smelt.set("statusline", statusline_tbl)?;
    Ok(())
}

fn register_autocmd(lua: &Lua, smelt: &mlua::Table, shared: &Arc<LuaShared>) -> LuaResult<()> {
    let s = shared.clone();
    smelt.set(
        "on",
        lua.create_function(move |lua, (event, handler): (String, mlua::Function)| {
            let Some(kind) = AutocmdEvent::from_lua_name(&event) else {
                return Err(LuaError::RuntimeError(format!("unknown event: {event}")));
            };
            let key = lua.create_registry_value(handler)?;
            if let Ok(mut map) = s.autocmds.lock() {
                map.entry(kind).or_default().push(LuaHandle { key });
            }
            Ok(())
        })?,
    )?;
    Ok(())
}

fn register_timer(lua: &Lua, smelt: &mlua::Table) -> LuaResult<()> {
    let timer_tbl = lua.create_table()?;
    timer_tbl.set(
        "set",
        lua.create_function(|lua, (ms, handler): (u64, mlua::Function)| {
            let key = lua.create_registry_value(handler)?;
            Ok(crate::lua::try_with_app(|app| {
                app.timers.set(Duration::from_millis(ms), LuaHandle { key })
            })
            .unwrap_or(0))
        })?,
    )?;
    timer_tbl.set(
        "every",
        lua.create_function(|lua, (ms, handler): (u64, mlua::Function)| {
            if ms == 0 {
                return Err(LuaError::RuntimeError(
                    "smelt.timer.every: period must be > 0".into(),
                ));
            }
            let key = lua.create_registry_value(handler)?;
            Ok(crate::lua::try_with_app(|app| {
                app.timers
                    .every(Duration::from_millis(ms), LuaHandle { key })
            })
            .unwrap_or(0))
        })?,
    )?;
    timer_tbl.set(
        "cancel",
        lua.create_function(|_, id: u64| {
            Ok(crate::lua::try_with_app(|app| app.timers.cancel(id)).unwrap_or(false))
        })?,
    )?;
    smelt.set("timer", timer_tbl)?;

    // `smelt.defer(ms, fn)` — alias for `smelt.timer.set` kept for the
    // nvim-shaped one-shot ergonomics. Returns nothing so existing
    // callers stay untouched.
    smelt.set(
        "defer",
        lua.create_function(|lua, (ms, handler): (u64, mlua::Function)| {
            let key = lua.create_registry_value(handler)?;
            crate::lua::try_with_app(|app| {
                app.timers.set(Duration::from_millis(ms), LuaHandle { key })
            });
            Ok(())
        })?,
    )?;
    Ok(())
}

fn register_spawn(lua: &Lua, smelt: &mlua::Table, shared: &Arc<LuaShared>) -> LuaResult<()> {
    let s = shared.clone();
    smelt.set(
        "spawn",
        lua.create_function(move |lua, handler: mlua::Function| {
            if let Ok(mut rt) = s.tasks.lock() {
                rt.spawn(
                    lua,
                    handler,
                    mlua::MultiValue::new(),
                    TaskCompletion::FireAndForget,
                )?;
            }
            Ok(())
        })?,
    )?;
    Ok(())
}
