[package]
name = "smelt-core"
version = "0.5.0-alpha.8"
edition = "2021"

[dependencies]
smelt-protocol = { workspace = true }
smelt-engine = { workspace = true }
smelt-perf = { workspace = true }
smelt-buffer = { workspace = true }
smelt-ansi = { workspace = true }
smelt-lua-doc-derive = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "sync", "time", "io-util", "process"] }
tokio-util = { workspace = true, features = ["rt"] }
serde = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true }
rmcp = { version = "1", default-features = false, features = ["client", "transport-child-process"] }
sha2 = { workspace = true }
libc = { workspace = true }
unicode-width = { workspace = true }
url = { workspace = true }
dirs = { workspace = true }
glob = { workspace = true }
globset = { workspace = true }
ignore = { workspace = true }
syntect = "5"
two-face = "0.5"
similar = { version = "3", features = ["inline"] }
seahash = "4"
mlua = { workspace = true }
scraper = "0.27"
ego-tree = "0.11"
include_dir = "0.7"
neo_frizbee = "0.10"
notify = { workspace = true }
pulldown-cmark = { version = "0.13", default-features = false }
shellexpand = "3.1.2"
smelt-store = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
