-- Default smelt init.lua
-- Generated by `smelt config default`. Copy to ~/.config/smelt/init.lua
-- and edit the values you want to override. All uncommented settings
-- below are set to their built-in defaults.

-- Optional bundled plugins. Uncomment to enable.
-- require("smelt.plugins.which_key")
-- require("smelt.plugins.inspect")
-- require("smelt.plugins.lsp")

-- Providers
-- No provider is registered by default. Use `smelt auth` to add one,
-- or uncomment and edit one of these examples. Provider type values:
-- openai-compatible, openai, codex, anthropic-compatible, anthropic, copilot, kimi-code.
--
-- smelt.provider.register("openai", {
--   type = "openai",
--   api_base = "https://api.openai.com/v1",
--   api_key_env = "OPENAI_API_KEY",
--   models = { "gpt-5.5" },
-- })
--
-- smelt.provider.register("ollama", {
--   type = "openai-compatible",
--   api_base = "http://localhost:11434/v1",
--   models = {
--     { name = "qwen3.6:27b", temperature = 0.8, top_p = 0.95 },
--   },
-- })

-- Startup defaults
-- nil means no configured cold-start default. Startup falls back to
-- CLI flags, recent choices, then the first registered provider/model.
smelt.defaults.set({
  model = nil,             -- example: "openai/gpt-5.5"
  mode = nil,              -- possible: "normal", "plan", "apply", "yolo"
  reasoning_effort = nil,  -- possible: "off", "low", "medium", "high", "max"
})

-- Remember last-used startup choices from recent.json.
smelt.remember.set({
  model = true,
  mode = true,
  reasoning_effort = true,
})

-- Settings
-- These are the built-in defaults. Every key can also be overridden
-- for one launch with `--set key=value`.
-- Vi keybindings in the prompt.
smelt.settings.vim = false

-- Sync prompt kills and yanks with the OS clipboard. Disable to keep `C-w`/`C-k`/`C-u`/`C-y` and vim `y`/`p` internal when OSC 52 clipboard writes are unreliable. Bracketed terminal paste still works.
smelt.settings.system_clipboard = true

-- Auto-summarize when request context usage crosses `compact_threshold` (forced on in headless).
smelt.settings.auto_compact = true

-- Idle auto-continue policy: `off` disables it, `goal` continues active auto goals, and `always` continues any idle session.
-- possible values: off, goal, always
smelt.settings.auto_continue = "goal"

-- Tokens/sec in status bar.
smelt.settings.show_tps = true

-- Context token count in status bar.
smelt.settings.show_tokens = true

-- Session cost in status bar.
smelt.settings.show_cost = true

-- Ghost-text input predictions in the prompt.
smelt.settings.show_prediction = true

-- Curated discovery tips in the start banner and prompt chrome.
smelt.settings.show_tips = true

-- Show Nerd Font file-type icons before inline-code paths that point at existing files.
smelt.settings.file_icons = false

-- Color inline-code file icons with nvim-web-devicons colors when `file_icons` is enabled.
smelt.settings.file_icon_colors = true

-- Task-slug label in status bar.
smelt.settings.show_slug = true

-- Keep the terminal window/tab title in sync with the current session title.
smelt.settings.terminal_title = true

-- Downgrade `Allow` to `Ask` for paths outside the workspace.
smelt.settings.restrict_to_workspace = true

-- Scrub detected secrets from user input and tool results before they reach the LLM.
smelt.settings.redact_secrets = false

-- Watch Lua config inputs (init.lua, plugins/, commands/, completers/, tools/, dialogs/, runtime overrides) and dispatch `/reload` when any of them changes. Prompt inputs such as AGENTS.md, SKILL.md, and `--system-prompt` stay manual via `/reload`.
smelt.settings.auto_reload = true

-- Fraction of the configured context window (0, 1] at which the bundled compact plugin auto-triggers before oversized requests.
smelt.settings.compact_threshold = 0.8

-- Minimum number of trailing message groups kept verbatim after compaction. A group is a user message, a plain assistant message, or an assistant tool-use step together with its tool outputs.
smelt.settings.compact_keep_recent_groups = 1

-- Request audit storage mode. `summary` keeps timing, token, cost, and size metadata only; `full` stores reconstructable provider payloads; `off` disables request audit writes.
-- possible values: off, summary, full
smelt.settings.request_audit = "summary"

-- Request the provider's accelerated inference mode when supported.
smelt.settings.fast_mode = false

-- Anthropic prompt cache TTL. `false` uses the 5-minute ephemeral TTL; `true` opts into the 1-hour TTL. Has no effect on non-Anthropic providers.
smelt.settings.cache_ttl_long = false

-- Search provider used by the built-in `web_search` tool.
-- possible values: duckduckgo, brave
smelt.settings.web_search_provider = "duckduckgo"

-- Environment variable containing the Brave Search API key.
smelt.settings.brave_search_api_key_env = "BRAVE_SEARCH_API_KEY"

-- Root directory for managed git worktrees. Relative paths are resolved inside the git root and contain worktrees directly; absolute paths are external roots and get a per-repository bucket. Supports leading `~`, `$VAR`, and `${VAR}` expansion; relative roots may not escape the repo.
smelt.settings.worktree_root = ".worktrees"

-- Autoupgrade behavior. `"off"` skips checks; `"notify"` shows a pill when an update is available; `"auto"` installs in background on detection.
-- possible values: off, notify, auto
smelt.settings.autoupgrade = "notify"

-- Release channel autoupgrade tracks: `"stable"` (tagged releases, including prereleases) or `"unstable"` (`main` HEAD).
-- possible values: stable, unstable
smelt.settings.autoupgrade_channel = "stable"

-- Seconds between background autoupgrade checks. The upgrade plugin clamps to a 60-second minimum to avoid hammering GitHub.
smelt.settings.autoupgrade_interval = 3600

-- Terminal notification preferences. Use /notify for temporary turn-end alerts.
smelt.settings.notifications = {
  turn_end = false,
}

-- Transcript display settings
-- Fold-state values: "collapsed", "peek", "expanded".
-- Set a group to false to disable that built-in grouping.
smelt.settings.transcript = {
  view = {
    blocks = { thinking = "peek" },
    tools = {
      load_skill = "collapsed",
      read_file = "collapsed",
      grep = "collapsed",
      glob = "collapsed",
      web_fetch = "collapsed",
      write_file = "expanded",
      edit_file = "collapsed",
      edit_notebook = "expanded",
    },
    groups = { explore = "collapsed", lsp = "collapsed", web = "collapsed" },
  },
  limits = {
    tool_rows = 20,
    tool_header_rows = 20,
    tool_body_rows = 20,
    tool_output_rows = 20,
    collapsed_error_rows = 4,
    thinking_peek_rows = 4,
    thinking_peek_head_rows = 1,
  },
}

-- Per-plugin helper model preferences
-- Defaults are nil, which means each helper uses the active model.
-- Names used by bundled plugins: title, compact, predict, btw, web_fetch.
-- smelt.model.preferred("title", "openai/gpt-5-mini")
-- smelt.model.preferred("compact", "anthropic/claude-haiku-4-5")

-- MCP servers
-- No MCP servers are registered by default. Uncomment to add one.
-- smelt.mcp.register("filesystem", {
--   type = "local",
--   description = "Read and write files under /tmp via MCP.",
--   command = { "npx", "-y", "@modelcontextprotocol/server-filesystem", "/tmp" },
--   env = {},
--   timeout = 30000,
--   enabled = true,
-- })

-- Permission rules
-- Default is to ask for tools that require permission. Uncomment to customize.
-- smelt.permissions.extend({
--   default = {
--     patterns = { bash = { allow = { "git status *", "git diff *" } } },
--   },
--   apply = {
--     patterns = { bash = { allow = { "git commit *" } } },
--   },
-- })

-- Theme
-- smelt.lifecycle.on_ready(function()
--   smelt.theme.use("default")
-- end)
