---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `#[derive(LuaOpts)]` / `#[derive(LuaAlias)]` site in Rust, or the `---@class` / `---@alias` block in the matching bundled Lua module.

--- Registration handle returned by every reactive-subscription API. `:remove()` undoes the binding (frees the underlying callback / cancels the timer / drops the subscription). Idempotent: subsequent calls return `false`.
---@class smelt.Reg
---@field remove fun(): boolean Undo the registration. Returns `true` the first time; `false` on subsequent calls or when the underlying target is already gone.

--- Buffer handle returned by `smelt.buf.new(opts?)`. Setter methods return the same handle for chaining.
---@class smelt.buf.Buf
---@field source fun(s: string?): any Read or write the buffer's full source. Without arg returns the source string (or `nil` if the buffer is gone). With arg replaces the source and returns the handle for chaining.
---@field lines fun(arr: string[]?): any Read or write the buffer as a string array. Without arg returns the lines; with arg replaces all lines and returns the handle for chaining.
---@field line fun(idx: integer): string? Read a single line by 1-based index. `nil` if out of range or the buffer is gone.
---@field styled fun(lines: table): smelt.buf.Buf Replace the buffer with a list of styled lines (`{ { text, style?, syntax? }, ... }`). Returns the handle for chaining.
---@field readonly fun(val: boolean?): any Read or write the readonly flag. With arg, returns the handle for chaining.
---@field mark fun(ns: integer, row: integer, col: integer, opts: smelt.buf.MarkOpts?): integer Place a highlight or virt-text extmark at `(row, col)`. Row is 1-based; `col` and `opts.end_col` are byte offsets into the line — the same unit as `#s`, `string.find`, and `string.sub`. Off-boundary bytes snap to the nearest UTF-8 char boundary; out-of-range bytes clamp to the line end. Returns the new extmark id. Allocate `ns` via `smelt.ns(name)`.
---@field clear_ns fun(ns: integer, start: integer?, end_: integer?): smelt.buf.Buf Drop every extmark owned by `ns` between `[start, end)` (1-based, exclusive end). Defaults clear the whole buffer. Returns the handle for chaining.

--- Options accepted by `buf:mark(ns, row, col, opts)`. Mirrors a useful subset of `nvim_buf_set_extmark`'s keyset; pick highlight or virt-text fields, not both.
---@class smelt.buf.MarkOpts
---@field id? integer Retarget an existing mark by id instead of allocating a new one.
---@field end_row? integer 1-based end row (inclusive). `nil` keeps the mark single-line.
---@field end_col? integer End byte offset for highlight ranges (exclusive). Same unit as `col` — bytes into the line, matching `#s` and `string.find`.
---@field priority? integer Higher-priority marks paint over lower-priority ones.
---@field right_gravity? boolean If true, the mark sticks with text inserted to its right.
---@field end_right_gravity? boolean Right-gravity flag for the end-of-range cursor.
---@field hl_group? string Theme group whose style is applied as the highlight base.
---@field fg? string | integer[] | { ansi: integer } | { rgb: integer[] } Foreground override. Either a theme group name (string) or a direct RGB triple `{ r, g, b }`. Takes precedence over `hl_group`.
---@field bg? string | integer[] | { ansi: integer } | { rgb: integer[] } Background override. Either a theme group name (string) or a direct RGB triple `{ r, g, b }`. Takes precedence over `hl_group`.
---@field bold? boolean Force-bold the highlight.
---@field dim? boolean Force-dim the highlight.
---@field italic? boolean Force-italic the highlight.
---@field hl_eol? boolean Extend the highlight past the last column to fill the EOL.
---@field on_cursor_row? boolean Paint only on the window's cursor row. Decorates the selected list item without re-rendering on every move.
---@field virt_text? string Virtual-text chunk to render alongside the line.
---@field virt_text_hl? string Theme group applied to the virt-text chunk.
---@field virt_text_pos? smelt.buf.VirtTextPos Where the virt-text appears relative to the line.
---@field selectable? boolean If false, the range is skipped by mouse selection.
---@field yank_as? string Override the yanked string when the user copies this range.

--- Selector accepted by `smelt.builtins.disable` / `enable`. Each list is a set of bundled module short-names — see the table below for the `smelt.<dotted>` form each one expands to. | field | expansion | |---|---| | `tools = { "web_search" }` | `smelt.tools.web_search` | | `commands = { "compact" }` | `smelt.commands.compact` | | `plugins = { "predict" }` | `smelt.plugins.predict` | | `dialogs = { "resume" }` | `smelt.dialogs.resume` | | `modules = { "smelt.foo.bar" }` | passed through verbatim |
---@class smelt.builtins.Selector
---@field tools? string[] Short tool names under `smelt.tools.*` (e.g. `"bash"`, `"web_search"`).
---@field commands? string[] Short command names under `smelt.commands.*` (e.g. `"compact"`).
---@field plugins? string[] Short plugin names under `smelt.plugins.*` (e.g. `"predict"`).
---@field dialogs? string[] Short dialog names under `smelt.dialogs.*` (e.g. `"resume"`).
---@field modules? string[] Fully-qualified `smelt.<dotted>` module names, passed through verbatim.

--- Sticky handle returned by `smelt.cell(name)`. Setters return the handle for chaining; `:subscribe` returns a `Reg`.
---@class smelt.cell.Cell
---@field get fun(): any Return the current cell value, or `nil` when the cell isn't declared.
---@field set fun(value: any): smelt.cell.Cell Publish a new value. Returns the handle for chaining.
---@field subscribe fun(handler: fun(value: any)): smelt.Reg Register `handler(value)` to fire on every `set`. Returns a `Reg` whose `:remove()` drops the subscription. No-op when called before the host pointer is live (e.g. the pre-TUI plugin pass) — the module body re-runs inside `bring_up_lua` where the bind takes effect.
---@field name fun(): string Return the cell name.

--- Flag specification accepted by `smelt.cli.register_flag`.
---@class smelt.cli.RegisterFlagOpts
---@field name string Flag name without `--`. Used as the key for `smelt.cli.get`.
---@field kind smelt.cli.FlagKind `"boolean"` (default `false`), `"string"`, or `"integer"`.
---@field default? any Default value when the flag is absent from argv. Type must match `kind`.
---@field short? string Short flag character (e.g. `"u"` for `-u`). Optional.
---@field long? string Long flag name override. Defaults to `name` when absent.
---@field description? string Human-readable description for `--help`.
---@field value_optional? boolean String/Integer flags only. When true, the flag may be passed without a value (`smelt -r` valid alongside `smelt -r abc`); the value-less form yields `""` for String and `0` for Integer. Defaults to `false`. Ignored for Boolean flags.

--- Options accepted by `smelt.cmd.register`.
---@class smelt.cmd.RegisterOpts
---@field desc? string Human-readable description shown in `/help` and the slash-command picker.
---@field args? string[] Positional argument labels used for help text and completion hints.
---@field while_busy? boolean If true, the command can be invoked while an agent turn is running. Defaults to `true`.
---@field queue_when_busy? boolean If true, busy invocations are queued instead of rejected. Defaults to `false`.
---@field startup_ok? boolean If true, the command may run before the runtime has finished bootstrapping. Defaults to `false`.
---@field hidden? boolean If true, the command is hidden from `/help` and the picker (still callable). Defaults to `false`.

--- One dialog-level keymap entry. `on_press(ctx)` receives the dialog
--- context exposing `ctx.close()` and `ctx.resolve(value)` so the
--- handler can dismiss the dialog or resolve the blocking `open` call.
---@class smelt.dialog.Keymap
---@field key string Chord string (e.g. `"q"`, `"<Esc>"`, `"ctrl-j"`).
---@field hint? string Optional one-line hint surfaced in the dialog footer.
---@field on_press fun(ctx: any): any Handler invoked when the key fires.

--- Each item displayed in `smelt.dialog.menu`. Strings are also accepted
--- and lifted into this shape automatically.
---@class smelt.dialog.MenuItem
---@field label string Row text after the dim ` N. ` numbering.
---@field description? string Optional second row, rendered dim.
---@field key? string Optional chord that triggers this item (defaults to its 1-based index for items 1..9).

--- Options accepted by `smelt.dialog.menu`.
---@class smelt.dialog.MenuOpts
---@field selected? integer 1-based starting cursor (default 1).
---@field shortcuts? "submit"|"select"|false Digit-key behavior. Default `"submit"`.
---@field numbered? boolean Show the dim ` N. ` prefix (default true).
---@field on_submit? fun(ctx: any): any Override the submit path. `ctx` carries the dialog handles plus `ctx.index` (1-based) and `ctx.item`. Default resolves the active dialog with `{ index, item }`.

--- Options accepted by `smelt.dialog.open` / `smelt.dialog.open_handle`.
--- Body sizing is body-relative: integer `height` values are forwarded
--- through with the chrome row added automatically; `"N%"`, `"fill"`,
--- and `"fit"` pass through verbatim. Pick one of `height` or
--- `max_height`; setting both raises.
---@class smelt.dialog.Opts
---@field title? string Title rendered in the chrome row.
---@field panels smelt.dialog.Panel[] Ordered list of body panels.
---@field focus? smelt.win.Win Leaf that should receive initial focus.
---@field height? any Fixed total body size: integer cells, `"N%"`, `"fill"`, or `"fit"`.
---@field max_height? any Shrink-to-content cap that pairs with `min_height`.
---@field min_height? any Floor for the body size (defaults to `"30%"` in fit mode).
---@field blocks_agent? boolean Block the agent loop while the dialog is open. Defaults to `false`.
---@field keymaps? smelt.dialog.Keymap[] Dialog-level key bindings (merged with built-ins).
---@field on_submit? fun(ctx: any): any Handler invoked on Enter; default resolves with the focused leaf.
---@field on_dismiss? fun(): nil Handler invoked when the dialog is dismissed.

--- One body panel inside a dialog. `leaf` is the win/leaf built by one of
--- the `smelt.dialog.*` helpers; `height` follows the same grammar as
--- `smelt.dialog.open` (integer cells, `"N%"`, `"fill"`, `"fit"`).
---@class smelt.dialog.Panel
---@field leaf smelt.win.Win A leaf returned by `smelt.dialog.input/options/list/markdown/content`.
---@field height? any Integer cells, `"N%"`, `"fill"`, or `"fit"`.

--- Options accepted by `smelt.dialog.picker`. Layered on top of
--- `smelt.dialog.Opts`; only the picker-specific fields are listed.
---@class smelt.dialog.PickerOpts
---@field items? any[] | fun(): any[] Eager item table or a lazy producer; re-evaluated by `on_query`.
---@field render fun(item: any): table Per-item `{ text, marks }` table — see `smelt.list.new`.
---@field filter? fun(item: any): boolean Predicate applied during `set_filter` / `refresh`.
---@field placeholder? string Input placeholder; defaults to `""`.
---@field empty_text? string Shown in the list when nothing matches.
---@field on_open? fun(ctx: any): nil Fires once after the input/list have been built.
---@field on_query? fun(query: string, ctx: any): nil Fires on every keystroke; default re-applies `filter`.
---@field on_submit? fun(ctx: any): any Fires on Enter. `ctx.item` is the highlighted row; defaults to resolving with `ctx.item` when non-nil.
---@field on_dismiss? fun(): nil Fires when the dialog is dismissed.
---@field keymaps? smelt.dialog.Keymap[] Extra dialog-level keymaps merged on top of navigation bindings.
---@field title? string Forwarded to `smelt.dialog.open`.
---@field height? any Forwarded to `smelt.dialog.open`.
---@field max_height? any Forwarded to `smelt.dialog.open`.
---@field min_height? any Forwarded to `smelt.dialog.open`.
---@field blocks_agent? boolean Forwarded to `smelt.dialog.open`.

--- Typed error table delivered to `on_response` when the underlying provider call fails. `kind` is a stable string the caller can branch on; `message` is a human-readable single-line description. The struct exists purely as a doc / LuaCATS schema target — the actual table is built in `LuaRuntime::fire_ask_callback` because it lands on a callback path that bypasses `FromLua` decoding.
---@class smelt.engine.AskError
---@field kind string One of `"network" | "rate_limited" | "quota" | "invalid_response" | "context_window" | "cancelled" | "other"`.
---@field message string Human-readable single-line description (newlines collapsed to spaces).

--- One text-only message used by request hooks that exchange plain user/assistant rows.
---@class smelt.engine.AskMessage
---@field role string Either `"user"` or `"assistant"`. Other roles are silently dropped.
---@field content string Message body as plain text.

--- Structured JSON-output specification for `smelt.engine.ask`.
---@class smelt.engine.AskResponseFormat
---@field name string Schema name (used by some providers as the response_format label).
---@field schema table JSON schema describing the expected response shape. Accepts a Lua table that round-trips through `lua_table_to_json` into a JSON value.

--- Spec for `smelt.engine.ask`.
---@class smelt.engine.AskSpec
---@field system string System prompt sent before the conversation.
---@field messages? table Prior turns. When present, this must be a sequence of full `protocol::Message`-shaped rows such as `{ role, content?, reasoning_content?, tool_calls?, tool_call_id?, is_error? }`.
---@field question? string Single-shot question appended as a final user message after `messages`.
---@field model? string Model reference (`"provider/model"` or a bare name resolved against the configured providers). When `nil`, falls back to the primary model.
---@field response_format? smelt.engine.AskResponseFormat JSON-schema response constraint.
---@field reasoning_effort? smelt.reasoning.Effort Reasoning effort for the request; defaults to `"off"`.
---@field on_response? fun(arg1: any, arg2: smelt.engine.AskError?) Fires once with `(response, err)`. On success `err` is `nil` and `response` is a full assistant message table; on failure `response` is `nil` and `err` is a `smelt.engine.AskError` table.

--- Front-matter override block accepted by `smelt.engine.submit_command`. Mirrors what plugin commands set in their markdown header. Tool-name keys (e.g. `bash`, `edit`) become per-subcommand pattern buckets.
---@class smelt.engine.CommandOverrides
---@field description? string Override the command description shown in `/help`.
---@field provider? string Force a specific provider for this command's turn.
---@field model? string Force a specific model id.
---@field temperature? number Sampling temperature override.
---@field top_p? number Nucleus-sampling cutoff override.
---@field top_k? integer Top-k sampling cutoff override.
---@field min_p? number Minimum-probability cutoff override.
---@field repeat_penalty? number Repeat-penalty override.
---@field reasoning_effort? string Reasoning-effort override; one of the `smelt.reasoning.Effort` strings.
---@field tools? smelt.engine.RuleOverride Per-tool `allow`/`ask`/`deny` patterns for the duration of the turn.
---@field [string] smelt.engine.RuleOverride Per-subcommand pattern buckets keyed by tool name.

--- Spec for `smelt.engine.ask_inherited`.
---@class smelt.engine.InheritedAskSpec
---@field messages? table Prior turns. When present, this must be a sequence of full `protocol::Message`-shaped rows such as `{ role, content?, reasoning_content?, tool_calls?, tool_call_id?, is_error? }`. When omitted or empty, the live model-visible history is inherited.
---@field question? string Single-shot question appended as a final user message after `messages`.
---@field model? string Model reference (`"provider/model"` or a bare name resolved against the configured providers). When `nil`, falls back to the primary model.
---@field response_format? smelt.engine.AskResponseFormat JSON-schema response constraint.
---@field reasoning_effort? smelt.reasoning.Effort Reasoning effort for the request; defaults to `"off"`.
---@field on_response? fun(arg1: any, arg2: smelt.engine.AskError?) Fires once with `(response, err)`. On success `err` is `nil` and `response` is a full assistant message table; on failure `response` is `nil` and `err` is a `smelt.engine.AskError` table.

--- Token accounting breakdown passed inside `smelt.engine.PrepareRequest`.
---@class smelt.engine.PrepareContextEstimate
---@field source string One of `"full_request_estimate" | "provider_snapshot" | "provider_snapshot_plus_history_delta" | "visible_fallback"`.
---@field total_context_tokens integer Total active-context estimate used by auto-compaction.
---@field provider_context_tokens? integer Latest provider-reported active context, when available.
---@field estimated_delta_tokens integer Locally estimated tokens added on top of provider usage.
---@field latest_snapshot_history_len? integer History length attached to the latest token snapshot, when available.
---@field current_history_len integer Current session history length at the prepare hook.

--- Request object passed to `smelt.engine.on_prepare_request`.
---@class smelt.engine.PrepareRequest
---@field messages smelt.engine.AskMessage[] Model-visible conversation excluding the system prompt.
---@field estimated_tokens integer Conservative token estimate for the request about to be sent, including system prompt, messages, and tool definitions.
---@field estimated_context_tokens integer Active-context estimate for auto-compaction. When a provider has reported context usage, this starts from that server-observed count and adds only local messages appended after the matching token snapshot; before the first usage report it equals `estimated_tokens`.
---@field context_estimate smelt.engine.PrepareContextEstimate Structured breakdown explaining how `estimated_context_tokens` was computed.

--- Subcommand rule override accepted inside `CommandOverrides`. Mirrors the front-matter `{ allow?, ask?, deny? }` shape.
---@class smelt.engine.RuleOverride
---@field allow? string[] Patterns that auto-allow.
---@field ask? string[] Patterns that always prompt.
---@field deny? string[] Patterns that auto-deny.

--- Options accepted by `smelt.list.new`. `leaf` and `buf` are mandatory —
--- they own the rendered selection cursor and the backing line buffer;
--- the rest configure how data is sourced, filtered, and rendered.
---@class smelt.list.Opts
---@field leaf smelt.win.Win Selectable list leaf (typically from `smelt.dialog.list`).
---@field buf smelt.buf.Buf Backing buffer that mirrors the rendered rows.
---@field items? any[] Initial item set. Mutate via `:set_items(...)` later if needed.
---@field render fun(item: any): table Returns `{ text, marks }` per visible row.
---@field filter? fun(item: any): boolean Predicate re-run on `:set_filter` / `:refresh`.
---@field empty_text? string Placeholder line shown when no row passes the filter.

--- MCP server config accepted by `smelt.mcp.register`.
---@class smelt.mcp.Config
---@field type? string Server kind. Only `"local"` (the default) is supported.
---@field command? string|string[] Executable + leading argv. Either a string (`"my-server"`) or a list (`{"my-server", "--flag"}`).
---@field args? string[] Trailing arguments appended after `command`.
---@field env? table<string, string> Extra environment variables to set on the child process.
---@field timeout? integer Request timeout in milliseconds. Defaults to `30000`.
---@field enabled? boolean Whether the server is enabled. Defaults to `true`.

--- Source-bound notify handle returned by `smelt.notify.scoped`. Callable
--- as `handle(msg)` for an info toast; `handle.error(msg)` and
--- `handle.warn(msg)` raise error/warning toasts. Every call forwards to
--- the underlying `smelt.notify*` with the source string pinned at
--- factory time.
---@class smelt.notify.Scoped
---@field error fun(msg: string) Raise an error toast tagged with the bound source.
---@field warn fun(msg: string) Raise a warning toast tagged with the bound source.
---@field [string] any Callable: `handle(msg)` -> info toast tagged with the bound source.

--- Overlay handle returned by `smelt.overlay.new(opts)`.
---@class smelt.overlay.Overlay
---@field close fun(): nil Close the overlay. No-op if already closed.
---@field key fun(chord: string, func: fun(value: table)): smelt.Reg Bind `func` to `chord` on this overlay. Fires when any leaf of the overlay holds focus, after a per-window keymap miss but before global Lua keymaps. Returns a Reg whose `:remove()` undoes the binding.

--- Opaque handle returned by `smelt.paint.register`. Usable directly in `smelt.ui.layout.leaf(handle, opts)` (it stands in for a Win in layout leaves).
---@class smelt.paint.Paint
---@field remove fun(): boolean Drop the paint callback. Returns `true` if it was still registered. Subsequent paints of this id no-op.
---@field rect fun(): any Return the paint leaf's current screen rect as `{ row, col, width, height }`, or `nil` until the first render lays it out.
---@field on fun(event: smelt.paint.Event, func: fun(value: table)): smelt.Reg Subscribe `func` to `event` on this paint leaf. Returns a Reg handle whose `:remove()` undoes the subscription.

--- Grid slice passed to paint callbacks. Methods delegate to the live grid slice for the current frame; out-of-scope calls fail cleanly.
---@class smelt.paint.Slice
---@field width fun(): integer Return the slice width in cells.
---@field height fun(): integer Return the slice height in cells.
---@field set fun(row: integer, col: integer, ch: string, style: table?): nil Write a single character with optional style at (row, col).
---@field put_str fun(row: integer, col: integer, text: string, style: table?): nil Write a string with optional style at (row, col).
---@field fill_rect fun(row: integer, col: integer, w: integer, h: integer, ch: string?, style: table?): nil Fill a rectangle with an optional character and style.

--- Permission slots that apply within a single agent mode. The fixed `tools` key controls the tool itself; any additional key is treated as a subcommand bucket and routed through that tool's subpattern parser (e.g. `bash = { allow = { "git status" } }`).
---@class smelt.permissions.ModePerms
---@field tools? smelt.permissions.RuleSet Per-tool `allow`/`ask`/`deny` patterns.
---@field [string] smelt.permissions.RuleSet Subcommand patterns keyed by tool name (`"bash"`, `"edit"`, …).

--- `allow`/`ask`/`deny` pattern arrays accepted by every permission slot.
---@class smelt.permissions.RuleSet
---@field allow? string[] Patterns that auto-allow without prompting.
---@field ask? string[] Patterns that always prompt.
---@field deny? string[] Patterns that auto-deny.

--- Spec for `smelt.permissions.set_rules`. Each mode falls back to `default` (and then to host-level rules) when its slot is `nil`.
---@class smelt.permissions.RulesSpec
---@field default? smelt.permissions.ModePerms Baseline rules applied unless a mode-specific slot overrides.
---@field normal? smelt.permissions.ModePerms Rules active while the agent is in normal mode.
---@field plan? smelt.permissions.ModePerms Rules active while the agent is in plan mode.
---@field apply? smelt.permissions.ModePerms Rules active while the agent is in apply mode.
---@field yolo? smelt.permissions.ModePerms Rules active while the agent is in yolo mode.

--- A single session permission entry (one approved tool/pattern pair).
---@class smelt.permissions.SessionEntry
---@field tool string Tool name the rule applies to (e.g. `"shell"`).
---@field pattern string Pattern matched against the tool's argument bucket.

--- Spec for `smelt.permissions.sync`.
---@class smelt.permissions.SyncSpec
---@field session? smelt.permissions.SessionEntry[] Session entries; applied for this run only.
---@field workspace? smelt.permissions.WorkspaceRule[] Workspace rules; persisted to disk under the current cwd.

--- A workspace permission rule (one tool with N patterns, persisted to disk).
---@class smelt.permissions.WorkspaceRule
---@field tool string Tool name the rule applies to.
---@field patterns string[] Patterns granted for this tool.

--- Picker handle returned by `smelt.picker.new(opts)`. Setter methods return the same handle for chaining.
---@class smelt.picker.Picker
---@field win fun(): smelt.win.Win Return the underlying Win handle (use `win:key(...)`, `win:on(...)` to bind input).
---@field close fun(): nil Close the picker overlay. No-op if already closed.
---@field items fun(items: table, selected: integer?): smelt.picker.Picker Replace the picker's items. Each entry is a string or `{ label, description?, ansi_color?, prefix?, ... }`. `selected` is the 0-based logical index to land the cursor on (default 0 — top of the new list); pass the current selection here to avoid a flash to row 0 followed by a separate `:selected()` call. Returns the handle for chaining.
---@field selected fun(idx: integer?): any Read or write the current logical selection (0-based). Without arg returns the index (`nil` if the picker is empty); with arg sets the selection and returns the handle for chaining.
---@field move fun(delta: integer): smelt.picker.Picker Move the picker's cursor by `delta` rows (clamped to the buffer's line count). Returns the handle for chaining.

--- Completer specification handed to `smelt.prompt.completer`. Every
--- field is required: `detect` recognises a trigger token in the live
--- prompt text, `items` enumerates the candidate set, `query` ranks
--- the candidates against the user's input, and `accept` splices the
--- chosen value back into the prompt.
---@class smelt.prompt.CompleterSpec
---@field detect fun(text: string, cpos: integer): any?, integer? Detect the trigger; returns `(spec_data, anchor_byte_offset)` or `nil`.
---@field items fun(spec_data: any): table[] Build the candidate list (one entry per row).
---@field query fun(spec_data: any, token: string, items: table[]): table[] Filter / rank the candidates.
---@field accept fun(spec_data: any, item: table): nil Splice the accepted candidate into the prompt.

--- Picker entry shown in the prompt-docked dropdown. `label` and the
--- optional flavour fields mirror what the fuzzy ranker renders; the
--- caller is free to attach extra fields and read them back from
--- `on_select` / `on_enter`.
---@class smelt.prompt.PickerItem
---@field label string Primary text rendered for the row.
---@field description? string Secondary text shown dimmed after the label.
---@field ansi_color? any ANSI color spec used for the prefix glyph.
---@field label_color? any Override the label's color.
---@field prefix? string Glyph rendered before the label.
---@field search_terms? string Extra haystack tokens for the fuzzy match.

--- Options accepted by `smelt.prompt.open_picker`. Passing `on_enter`
--- switches the picker to persistent mode (stays open across selects);
--- omit it for single-shot behaviour.
---@class smelt.prompt.PickerOpts
---@field items smelt.prompt.PickerItem[] | fun(): smelt.prompt.PickerItem[] Eager list or lazy producer.
---@field on_select? fun(item: smelt.prompt.PickerItem): nil Fires on every cursor move.
---@field on_enter? fun(item: smelt.prompt.PickerItem, idx: integer): nil Persistent-mode accept handler.
---@field on_dismiss? fun(): nil Fires on Esc.

--- Spec accepted by `smelt.provider.register`.
---@class smelt.provider.Config
---@field type? string Provider kind tag (`"openai"`, `"anthropic"`, etc.).
---@field api_base? string Base URL the engine talks to.
---@field api_key_env? string Environment variable that holds the bearer token.
---@field models? string|smelt.provider.Model[] Models offered by this provider.

--- One model entry in a provider's `models` list. Plugin authors can pass either a bare model id string or a full table — the wrapper handles both forms transparently.
---@class smelt.provider.Model
---@field name? string Model id as it appears in API requests.
---@field temperature? number Default sampling temperature.
---@field top_p? number Default nucleus-sampling cutoff.
---@field top_k? integer Default top-k sampling cutoff.
---@field min_p? number Default minimum-probability cutoff.
---@field repeat_penalty? number Default repeat penalty.
---@field tool_calling? boolean Whether the model supports tool calls.
---@field input_cost? number Cost per input token in USD.
---@field output_cost? number Cost per output token in USD.
---@field cache_read_cost? number Cost per cache-read token in USD.
---@field cache_write_cost? number Cost per cache-write token in USD.
---@field max_tokens? integer Maximum output tokens for this model. Defaults to the model's own limit, falling back to 4096 if unknown.
---@field thinking_budgets? table Per-level token budgets for budget-based thinking.

--- Color value. Set `ansi` (256-color palette index) or `rgb` (`{R, G, B}` triple) for a direct color, or `dark` / `light` (themselves `ColorDecl`s) for a branch that resolves against the terminal background. A matching-side branch wins over the direct fields.
---@class smelt.theme.ColorDecl
---@field ansi? integer ANSI 256-color palette index for the default (non-branched) case.
---@field rgb? integer[] `[r, g, b]` sRGB triple for the default (non-branched) case.
---@field light? smelt.theme.ColorDecl Color this branch resolves to when `is_light == true`.
---@field dark? smelt.theme.ColorDecl Color this branch resolves to when `is_light == false`.

--- Style table for a single highlight group. Every field is optional — unset fields stay at `Style::default()`. Pass a string in place of this struct (at the group-map level) to alias another group.
---@class smelt.theme.StyleDecl
---@field fg? smelt.theme.ColorDecl Foreground color.
---@field bg? smelt.theme.ColorDecl Background color.
---@field bold? boolean Bold text.
---@field italic? boolean Italic text.
---@field dim? boolean Dim / faint text.
---@field underline? boolean Underline.
---@field crossedout? boolean Strikethrough.

--- Flat map keyed by highlight-group name (`Comment`, `Visual`, `SmeltAccent`, …). Each value is either a `StyleDecl` table or a string referencing another group in the same spec. Every themable color (foreground, background, diff row fills, scrollbar colors, mode indicators) is just a group.
---@class smelt.theme.ThemeSpec
---@field [string] string | smelt.theme.StyleDecl Style table or alias string for the group named by the key.

--- Per-mode default decisions installed by `smelt.tools.register`. Each missing field falls through to the host's generic rules.
---@class smelt.tools.PermissionDefaults
---@field normal? smelt.tools.Decision Decision applied in normal mode.
---@field plan? smelt.tools.Decision Decision applied in plan mode.
---@field apply? smelt.tools.Decision Decision applied in apply mode.
---@field yolo? smelt.tools.Decision Decision applied in yolo mode.

--- Plugin tool definition passed to `smelt.tools.register`. `execute` is required; the remaining hooks are optional and are invoked at well-defined points during a tool turn — see the field docs for each callback's contract.
---@class smelt.tools.ToolDef
---@field name string Tool name; used as the engine-facing identifier.
---@field execute function Required handler: `execute(args, ctx)` — returns the tool result.
---@field description? string Human-readable description shown to the model.
---@field parameters? table JSON-schema parameters table passed through to the model.
---@field permission_defaults? smelt.tools.PermissionDefaults Per-mode default decisions.
---@field default_allow? string[] Subcommand patterns that auto-allow without prompting.
---@field subpattern_parser? string Built-in subpattern parser kind (e.g. `"bash"`).
---@field modes? table Agent modes the tool is available in; nil means all modes.
---@field execution_mode? string `"concurrent"` (default) or `"sequential"`.
---@field summary? function `summary(args) -> string | styled_lines | nil` — styled label rendered in the transcript header AND confirm dialog body header. Plain string is auto-wrapped as one plain span; the styled-lines form is `{ { { text, syntax?, style? }, ... }, ... }` — same span shape as `buf:styled`.
---@field approval_patterns? function `approval_patterns(args, ctx) -> string[]` — patterns offered as one-click approvals.
---@field preflight? function `preflight(args, ctx) -> table?` — validation hook; nil result skips.
---@field render? function `render(buf, args, result)` — custom transcript render.
---@field paths_for_workspace? function `paths_for_workspace(args) -> string[]` — files this invocation will touch.
---@field preview? function `preview(args) -> smelt.layout` — pre-execute preview render. Returns the same `smelt.layout` value the `render` callback returns; the confirm dialog renders it directly into the preview pane.
---@field decide? function `decide(args, mode) -> smelt.tools.Decision?` — per-call decision; nil falls through to generic permissions.
---@field override? boolean Replace a core tool of the same name (advanced).

--- Window handle returned by `smelt.win.new(buf, opts?)`. Setter methods return the same handle for chaining.
---@class smelt.win.Win
---@field close fun(): nil Close the overlay leaf. No-op if the window is already closed.
---@field focus fun(): nil Move keyboard focus to this window. No-op if the window is not focusable.
---@field buf fun(): smelt.buf.Buf? Return the backing Buf handle, or `nil` if the window is gone.
---@field rect fun(): any Return the window's current viewport rect as `{ row, col, width, height }`, or `nil` until the first render lays it out.
---@field content_width fun(): any Return the inner-content width in cells (gutter and pad_left/pad_right already subtracted), or `nil` until the first render lays the window out. Use this instead of `rect().width` when fitting text into the window's actual content budget.
---@field cursor fun(row: integer?): any Read or write the cursor row (0-based). Without arg returns the row; with arg sets and returns the handle for chaining.
---@field move_cursor fun(delta: integer): smelt.win.Win Move the cursor by `delta` rows (clamped to the buffer's line count). Returns the handle for chaining.
---@field key fun(chord: string, func: fun(value: table)): smelt.Reg Bind `func` to `chord` on this window. Returns a Reg handle whose `:remove()` undoes the binding. Raises on unknown chords.
---@field on fun(event: smelt.win.Event, func: fun(value: table)): smelt.Reg Subscribe `func` to `event` on this window. Returns a Reg handle whose `:remove()` undoes the subscription.
---@field placeholder fun(text: string, opts: table?): smelt.win.Win Set the window's placeholder — a dim suggestion rendered when the buffer is empty. Replaces any prior placeholder. `text` must be a single line (no `\n`); split before calling. `opts.accept_keys` (array of chord strings, default `{}`) accept the placeholder into the buffer and fire `placeholder_accepted`. `opts.dismiss_keys` (default `{ "esc", "c-c" }`) clear the placeholder and fire `placeholder_dismissed`. Typing does not destroy the placeholder; the extmark survives so an undo back to an empty buffer makes it visible again. Today only the prompt window renders the dim text and runs the accept/dismiss dispatch — calls on other windows store state but won't render. Returns the handle for chaining.
---@field clear_placeholder fun(): nil Clear the window's placeholder text and opts. Idempotent.
---@field placeholder_text fun(): string? Return the current placeholder text, or `nil` if none is set.
---@field link_scroll fun(others: smelt.win.Win): smelt.win.Win Link `scroll_top` between this window and the variadic `others`. Closing any member auto-removes it. Returns the handle for chaining.
---@field scroll fun(arg: any): any Read or write the window's scroll state. No arg returns `{ top, follow, total, viewport }` (`total` is the buffer's line count; `viewport` is the leaf's height). An integer sets `scroll_top` and clears the pin-to-tail flag. The literal string `"tail"` re-pins the viewport to the buffer's tail.

--- Where a virtual-text chunk is rendered relative to the line.
---@alias smelt.buf.VirtTextPos "inline"|"overlay"|"right_align"|"eol"

--- Name of a reactive cell. Open alias — plugin-defined cells declared via `smelt.cell.new` are accepted alongside the well-known runtime cells listed here.
---@alias smelt.cell.Name string|"agent_mode"|"block_done"|"branch"|"cmd_post"|"cmd_pre"|"confirm_requested"|"confirm_resolved"|"confirms_pending"|"cursor_pos"|"cwd"|"errors"|"history"|"input_submit"|"model"|"now"|"permission_pending"|"reasoning"|"running_procs"|"session_ended"|"session_started"|"session_title"|"shutdown"|"spinner_frame"|"stream_delta"|"task_label"|"tokens_used"|"tool_end"|"tool_start"|"tps"|"turn_complete"|"turn_end"|"turn_error"|"turn_start"|"vim_mode"|"work_busy"|"work_elapsed_ms"|"work_label"|"work_outcome"|"work_retry_attempt"|"work_retry_remaining_ms"|"work_state"

--- Type of CLI flag declared via `smelt.cli.register_flag`. Matches the subset of clap that we expose to Lua.
---@alias smelt.cli.FlagKind "boolean"|"string"|"integer"

--- Agent mode string literal.
---@alias smelt.mode.Mode "normal"|"plan"|"apply"|"yolo"

--- Paint-leaf events accepted by `paint:on(event, fn)`.
---@alias smelt.paint.Event "press"|"release"|"drag"

--- Reasoning effort level string literal.
---@alias smelt.reasoning.Effort "off"|"low"|"medium"|"high"|"max"

--- Decision string accepted by `decide` callbacks and `permission_defaults`. Matches `protocol::Decision::{Allow, Ask, Deny}` — the engine's `Error(_)` variant is not exposed.
---@alias smelt.tools.Decision "allow"|"ask"|"deny"

--- Vim mode string literal.
---@alias smelt.vim.Mode "insert"|"normal"|"visual"|"visual_line"

--- Window-event names accepted by `win:on(event, fn)`. Maps onto the internal `WinEvent` enum.
---@alias smelt.win.Event "open"|"close"|"focus"|"blur"|"selection_changed"|"submit"|"text_changed"|"dismiss"|"tick"|"press"|"release"|"drag"|"scrolled"|"resized"|"placeholder_accepted"|"placeholder_dismissed"

