---@meta

-- Auto-generated by `cargo run -p tui --bin gen-lua-docs`.
-- Do not edit by hand; update the `#[derive(LuaOpts)]`/`#[derive(LuaAlias)]` site in Rust instead.

--- Options accepted by `smelt.buf.set_extmark`. Mirrors a useful subset of `nvim_buf_set_extmark`'s keyset; pick highlight or virt-text fields, not both.
---@class smelt.buf.ExtmarkOpts
---@field id? integer Retarget an existing mark by id instead of allocating a new one.
---@field end_row? integer 1-based end row (inclusive). `nil` keeps the mark single-line.
---@field end_col? integer End column for highlight ranges.
---@field priority? integer Higher-priority marks paint over lower-priority ones.
---@field right_gravity? boolean If true, the mark sticks with text inserted to its right.
---@field end_right_gravity? boolean Right-gravity flag for the end-of-range cursor.
---@field hl_group? string Theme group whose style is applied as the highlight base.
---@field fg? string Theme group whose foreground overrides `hl_group`.
---@field bg? string Theme group whose background overrides `hl_group`.
---@field bold? boolean Force-bold the highlight.
---@field dim? boolean Force-dim the highlight.
---@field italic? boolean Force-italic the highlight.
---@field hl_eol? boolean Extend the highlight past the last column to fill the EOL.
---@field virt_text? string Virtual-text chunk to render alongside the line.
---@field virt_text_hl? string Theme group applied to the virt-text chunk.
---@field virt_text_pos? smelt.buf.VirtTextPos Where the virt-text appears relative to the line.
---@field selectable? boolean If false, the range is skipped by mouse selection.
---@field yank_as? string Override the yanked string when the user copies this range.

--- Sticky handle returned by `smelt.cell(name)`. Provides `:get()`, `:set(value)`, `:subscribe(handler)`, `:unsubscribe(id)`, and `:name()` methods.
---@class smelt.cell.CellHandle
---@field get fun(): any Return the current cell value, or `nil` when the cell isn't declared.
---@field set fun(value: any): boolean Publish a new value. Returns `true` on success.
---@field subscribe fun(handler: fun(value: any)): integer? Register handler(value) to fire on every set. Returns subscription id or `nil`.
---@field unsubscribe fun(id: integer): boolean Drop the subscription with id. Returns `true` on success.
---@field name fun(): string Return the cell name.

--- Options accepted by `smelt.cmd.register`.
---@class smelt.cmd.RegisterOpts
---@field desc? string Human-readable description shown in `/help` and the slash-command picker.
---@field args? string[] Positional argument labels used for help text and completion hints.
---@field while_busy? boolean If true, the command can be invoked while an agent turn is running. Defaults to `true`.
---@field queue_when_busy? boolean If true, busy invocations are queued instead of rejected. Defaults to `false`.
---@field startup_ok? boolean If true, the command may run before the runtime has finished bootstrapping. Defaults to `false`.
---@field hidden? boolean If true, the command is hidden from `/help` and the picker (still callable). Defaults to `false`.

--- One message in a `smelt.engine.ask` conversation.
---@class smelt.engine.AskMessage
---@field role string Either `"user"` or `"assistant"`. Other roles are silently dropped.
---@field content string Message body as plain text.

--- Spec for `smelt.engine.ask`.
---@class smelt.engine.AskSpec
---@field system string System prompt sent before the conversation.
---@field messages? smelt.engine.AskMessage[] Prior turns. Each message is `{ role = "user"|"assistant", content = "..." }`.
---@field question? string Single-shot question appended as a final user message after `messages`.
---@field task? smelt.engine.AskTask Routing tag; defaults to `"btw"`.
---@field on_response? fun(value: string) Fires once with the assistant's reply string.

--- Front-matter override block accepted by [`smelt.engine.submit_command`]. Mirrors what plugin commands set in their markdown header. Tool-name keys (e.g. `bash`, `edit`) become per-subcommand pattern buckets.
---@class smelt.engine.CommandOverrides
---@field description? string Override the command description shown in `/help`.
---@field provider? string Force a specific provider for this command's turn.
---@field model? string Force a specific model id.
---@field temperature? number Sampling temperature override.
---@field top_p? number Nucleus-sampling cutoff override.
---@field top_k? integer Top-k sampling cutoff override.
---@field min_p? number Minimum-probability cutoff override.
---@field repeat_penalty? number Repeat-penalty override.
---@field reasoning_effort? string Reasoning-effort override; one of the `smelt.reasoning.Effort` strings.
---@field tools? smelt.engine.RuleOverride Per-tool `allow`/`ask`/`deny` patterns for the duration of the turn.
---@field [string] smelt.engine.RuleOverride Per-subcommand pattern buckets keyed by tool name.

--- Subcommand rule override accepted inside `CommandOverrides`. Mirrors the front-matter `{ allow?, ask?, deny? }` shape.
---@class smelt.engine.RuleOverride
---@field allow? string[] Patterns that auto-allow.
---@field ask? string[] Patterns that always prompt.
---@field deny? string[] Patterns that auto-deny.

--- MCP server config accepted by `smelt.mcp.register`.
---@class smelt.mcp.Config
---@field type? string Server kind. Only `"local"` (the default) is supported.
---@field command? string|string[] Executable + leading argv. Either a string (`"my-server"`) or a list (`{"my-server", "--flag"}`).
---@field args? string[] Trailing arguments appended after `command`.
---@field env? table<string, string> Extra environment variables to set on the child process.
---@field timeout? integer Request timeout in milliseconds. Defaults to `30000`.
---@field enabled? boolean Whether the server is enabled. Defaults to `true`.

--- Grid slice passed to paint callbacks. Methods delegate to the live grid slice for the current frame; out-of-scope calls fail cleanly.
---@class smelt.paint.Slice
---@field width fun(): integer Return the slice width in cells.
---@field height fun(): integer Return the slice height in cells.
---@field set fun(row: integer, col: integer, ch: string, style: table?): nil Write a single character with optional style at (row, col).
---@field put_str fun(row: integer, col: integer, text: string, style: table?): nil Write a string with optional style at (row, col).
---@field fill_rect fun(row: integer, col: integer, w: integer, h: integer, ch: string?, style: table?): nil Fill a rectangle with an optional character and style.

--- Permission slots that apply within a single agent mode. The fixed `tools` key controls the tool itself; any additional key is treated as a subcommand bucket and routed through that tool's subpattern parser (e.g. `bash = { allow = { "git status" } }`).
---@class smelt.permissions.ModePerms
---@field tools? smelt.permissions.RuleSet Per-tool `allow`/`ask`/`deny` patterns.
---@field [string] smelt.permissions.RuleSet Subcommand patterns keyed by tool name (`"bash"`, `"edit"`, …).

--- `allow`/`ask`/`deny` pattern arrays accepted by every permission slot.
---@class smelt.permissions.RuleSet
---@field allow? string[] Patterns that auto-allow without prompting.
---@field ask? string[] Patterns that always prompt.
---@field deny? string[] Patterns that auto-deny.

--- Spec for `smelt.permissions.set_rules`. Each mode falls back to `default` (and then to host-level rules) when its slot is `nil`.
---@class smelt.permissions.RulesSpec
---@field default? smelt.permissions.ModePerms Baseline rules applied unless a mode-specific slot overrides.
---@field normal? smelt.permissions.ModePerms Rules active while the agent is in normal mode.
---@field plan? smelt.permissions.ModePerms Rules active while the agent is in plan mode.
---@field apply? smelt.permissions.ModePerms Rules active while the agent is in apply mode.
---@field yolo? smelt.permissions.ModePerms Rules active while the agent is in yolo mode.

--- A single session permission entry (one approved tool/pattern pair).
---@class smelt.permissions.SessionEntry
---@field tool string Tool name the rule applies to (e.g. `"shell"`).
---@field pattern string Pattern matched against the tool's argument bucket.

--- Spec for `smelt.permissions.sync`.
---@class smelt.permissions.SyncSpec
---@field session? smelt.permissions.SessionEntry[] Session entries; applied for this run only.
---@field workspace? smelt.permissions.WorkspaceRule[] Workspace rules; persisted to disk under the current cwd.

--- A workspace permission rule (one tool with N patterns, persisted to disk).
---@class smelt.permissions.WorkspaceRule
---@field tool string Tool name the rule applies to.
---@field patterns string[] Patterns granted for this tool.

--- Spec accepted by `smelt.provider.register`.
---@class smelt.provider.Config
---@field type? string Provider kind tag (`"openai"`, `"anthropic"`, etc.).
---@field api_base? string Base URL the engine talks to.
---@field api_key_env? string Environment variable that holds the bearer token.
---@field models? string|smelt.provider.Model[] Models offered by this provider.

--- One model entry in a provider's `models` list. Plugin authors can pass either a bare model id string or a full table — the wrapper handles both forms transparently.
---@class smelt.provider.Model
---@field name? string Model id as it appears in API requests.
---@field temperature? number Default sampling temperature.
---@field top_p? number Default nucleus-sampling cutoff.
---@field top_k? integer Default top-k sampling cutoff.
---@field min_p? number Default minimum-probability cutoff.
---@field repeat_penalty? number Default repeat penalty.
---@field tool_calling? boolean Whether the model supports tool calls.
---@field input_cost? number Cost per input token in USD.
---@field output_cost? number Cost per output token in USD.
---@field cache_read_cost? number Cost per cache-read token in USD.
---@field cache_write_cost? number Cost per cache-write token in USD.

--- Options accepted by `smelt.statusline.register`.
---@class smelt.statusline.RegisterOpts
---@field align? string `"right"` makes the source's segments default to the right strip. Defaults to left.

--- Per-mode default decisions installed by `smelt.tools.register`. Each missing field falls through to the host's generic rules.
---@class smelt.tools.PermissionDefaults
---@field normal? smelt.tools.Decision Decision applied in normal mode.
---@field plan? smelt.tools.Decision Decision applied in plan mode.
---@field apply? smelt.tools.Decision Decision applied in apply mode.
---@field yolo? smelt.tools.Decision Decision applied in yolo mode.

--- Plugin tool definition passed to `smelt.tools.register`. `execute` is required; the remaining hooks are optional and are invoked at well-defined points during a tool turn — see the field docs for each callback's contract.
---@class smelt.tools.ToolDef
---@field name string Tool name; used as the engine-facing identifier.
---@field execute function Required handler: `execute(args, ctx)` — returns the tool result.
---@field description? string Human-readable description shown to the model.
---@field parameters? table JSON-schema parameters table passed through to the model.
---@field permission_defaults? smelt.tools.PermissionDefaults Per-mode default decisions.
---@field default_allow? string[] Subcommand patterns that auto-allow without prompting.
---@field subpattern_parser? string Built-in subpattern parser kind (e.g. `"bash"`).
---@field modes? table Agent modes the tool is available in; nil means all modes.
---@field execution_mode? string `"concurrent"` (default) or `"sequential"`.
---@field summary? function `summary(args, result) -> string` — short label for the picker.
---@field confirm_text? function `confirm_text(args, ctx) -> string` — prompt body shown in the approval modal.
---@field approval_patterns? function `approval_patterns(args, ctx) -> string[]` — patterns offered as one-click approvals.
---@field preflight? function `preflight(args, ctx) -> table?` — validation hook; nil result skips.
---@field render? function `render(buf, args, result)` — custom transcript render.
---@field paths_for_workspace? function `paths_for_workspace(args) -> string[]` — files this invocation will touch.
---@field preview? function `preview(buf, args)` — pre-execute preview render.
---@field decide? function `decide(args, mode) -> smelt.tools.Decision?` — per-call decision; nil falls through to generic permissions.
---@field override? boolean Replace a core tool of the same name (advanced).

--- Where a virtual-text chunk is rendered relative to the line.
---@alias smelt.buf.VirtTextPos "inline"|"overlay"|"right_align"|"eol"

--- Name of a reactive cell. Open alias — plugin-defined cells declared via `smelt.cell.new` are accepted alongside the well-known runtime cells listed here.
---@alias smelt.cell.Name string|"agent_mode"|"block_done"|"branch"|"cmd_post"|"cmd_pre"|"confirm_requested"|"confirm_resolved"|"confirms_pending"|"cwd"|"errors"|"history"|"input_submit"|"model"|"now"|"reasoning"|"session_ended"|"session_started"|"session_title"|"shutdown"|"spinner_frame"|"tokens_used"|"tool_end"|"tool_start"|"turn_complete"|"turn_end"|"turn_error"|"turn_start"|"vim_mode"

--- Auxiliary task tag accepted by `smelt.engine.ask`. Routes the request to a dedicated auxiliary model when one is configured.
---@alias smelt.engine.AskTask "title"|"prediction"|"compaction"|"btw"

--- Agent mode string literal.
---@alias smelt.mode.Mode "normal"|"plan"|"apply"|"yolo"

--- Reasoning effort level string literal.
---@alias smelt.reasoning.Effort "off"|"low"|"medium"|"high"|"max"

--- Decision string accepted by `decide` callbacks and `permission_defaults`. Matches `protocol::Decision::{Allow, Ask, Deny}` — the engine's `Error(_)` variant is not exposed.
---@alias smelt.tools.Decision "allow"|"ask"|"deny"

--- Vim mode string literal.
---@alias smelt.vim.Mode "insert"|"normal"|"visual"|"visual_line"

--- Window-event names accepted by `smelt.win.on_event` and `smelt.win.clear_event`. Maps onto the internal `WinEvent` enum.
---@alias smelt.win.Event "open"|"close"|"focus"|"blur"|"selection_changed"|"submit"|"text_changed"|"dismiss"|"tick"

