---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `#[derive(LuaOpts)]` / `#[derive(LuaAlias)]` site in Rust, or the `---@class` / `---@alias` block in the matching bundled Lua module.

--- Handle returned by `smelt.plugin` for a named plugin scope.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.Plugin
---@field name string Stable scope name.
---@field state table Ephemeral JSON-shaped state that survives `/reload` but not restart.

--- Registration handle returned by every reactive-subscription API. `:remove()` undoes the binding (frees the underlying callback / cancels the timer / drops the subscription). Idempotent: subsequent calls return `false`.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.Reg
---@field remove fun(): boolean Undo the registration. Returns `true` the first time; `false` on subsequent calls or when the underlying target is already gone.

--- Buffer handle returned by `smelt.buf.new(opts?)`. Setter methods return the same handle for chaining.
--- Classification: Advanced - Documented low-level capability for plugins that need full control. It may evolve more freely than the Supported facade.
---@class smelt.buf.Buf
---@field source fun(s: string?): any Read or write the buffer's full source. Without arg returns the source string (or `nil` if the buffer is gone). With arg replaces the source and returns the handle for chaining. On the built-in prompt buffer, this routes through `smelt.prompt.set_text` semantics so cursor, undo, attachments, and completer state stay coherent.
---@field lines fun(arr: string[]?): any Read or write the buffer as a string array. Without arg returns the lines; with arg replaces all lines and returns the handle for chaining. On the built-in prompt buffer, writes are joined with `\n` and installed through `smelt.prompt.set_text` semantics.
---@field line fun(idx: integer): string? Read a single line by 1-based index. `nil` if out of range or the buffer is gone.
---@field styled fun(lines: table): smelt.buf.Buf Replace the buffer with a list of styled lines (`{ { text, style?, syntax? }, ... }`). Returns the handle for chaining.
---@field readonly fun(val: boolean?): any Read or write the readonly flag. With arg, returns the handle for chaining.
---@field mark fun(ns: integer, row: integer, col: integer, opts: smelt.buf.MarkOpts?): integer Place a highlight or virt-text extmark at `(row, col)`. Row is 1-based; `col` and `opts.end_col` are byte offsets into the line, the same unit as `#s`, `string.find`, and `string.sub`. Off-boundary bytes snap to the nearest UTF-8 char boundary; out-of-range bytes clamp to the line end. Returns the new extmark id. Allocate `ns` via `smelt.ns(name)`.
---@field clear_ns fun(ns: integer, start: integer?, end_: integer?): smelt.buf.Buf Drop every extmark owned by `ns` between `[start, end)` (1-based, exclusive end). Defaults clear the whole buffer. Returns the handle for chaining.

--- Options accepted by `buf:mark(ns, row, col, opts)`. Mirrors a useful subset of `nvim_buf_set_extmark`'s keyset; pick highlight or virt-text fields, not both.
--- Classification: Advanced - Documented low-level capability for plugins that need full control. It may evolve more freely than the Supported facade.
---@class smelt.buf.MarkOpts
---@field id? integer Retarget an existing mark by id instead of allocating a new one.
---@field end_row? integer 1-based end row (inclusive). `nil` keeps the mark single-line.
---@field end_col? integer End byte offset for highlight ranges (exclusive). Same unit as `col` - bytes into the line, matching `#s` and `string.find`.
---@field priority? integer Higher-priority marks paint over lower-priority ones.
---@field right_gravity? boolean If true, the mark sticks with text inserted to its right.
---@field end_right_gravity? boolean Right-gravity flag for the end-of-range cursor.
---@field hl_group? string Theme group whose style is applied as the highlight base.
---@field fg? string | integer[] | { ansi: integer } | { rgb: integer[] } Foreground override. Either a theme group name (string) or a direct RGB triple `{ r, g, b }`. Takes precedence over `hl_group`.
---@field bg? string | integer[] | { ansi: integer } | { rgb: integer[] } Background override. Either a theme group name (string) or a direct RGB triple `{ r, g, b }`. Takes precedence over `hl_group`.
---@field bold? boolean Force-bold the highlight.
---@field dim? boolean Force-dim the highlight.
---@field italic? boolean Force-italic the highlight.
---@field reverse? boolean Force reverse-video on the highlight.
---@field hl_eol? boolean Extend the highlight past the last column to fill the EOL.
---@field on_cursor_row? boolean Paint only on the window's cursor row. Decorates the selected list item without re-rendering on every move.
---@field virt_text? string Virtual-text chunk to render alongside the line.
---@field virt_text_hl? string Theme group applied to the virt-text chunk. `fg`, `bg`, and text attributes below can further override it.
---@field virt_text_pos? smelt.buf.VirtTextPos Where the virt-text appears relative to the line.
---@field selectable? boolean If false, the range is skipped by mouse selection.
---@field yank_as? string Override the yanked string when the user copies this range.

--- Options for `smelt.buf.new(opts?)`. Named buffers survive `/reload`; anonymous buffers are reaped.
--- Classification: Advanced - Documented low-level capability for plugins that need full control. It may evolve more freely than the Supported facade.
---@class smelt.buf.NewOpts
---@field name? string Stable name used to reuse this buffer across `/reload`.
---@field readonly? boolean When true, UI editing operations cannot mutate the buffer.
---@field editable? boolean Enable undo history for plugin-managed editable buffers.
---@field undo? integer Undo history entry limit when `editable = true` (defaults to 100).
---@field mode? "plain"|"markdown"|"md"|"code" Attach a parser-backed renderer to the buffer.
---@field lang? string Syntax language token required by `mode = "code"`.
---@field diff_base? string When `mode = "code"`, render the buffer source as an inline diff against this base text.

--- Selector accepted by `smelt.builtins.disable` / `enable`. Each list is a set of bundled module short-names - see the table below for the `smelt.<dotted>` form each one expands to. | field | expansion | |---|---| | `tools = { "web_search" }` | `smelt.tools.web_search` | | `commands = { "compact" }` | `smelt.commands.compact` | | `plugins = { "predict" }` | `smelt.plugins.predict` | | `dialogs = { "resume" }` | `smelt.dialogs.resume` | | `modules = { "smelt.foo.bar" }` | passed through verbatim |
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.builtins.Selector
---@field tools? string[] Short tool names under `smelt.tools.*` (e.g. `"bash"`, `"web_search"`).
---@field commands? string[] Short command names under `smelt.commands.*` (e.g. `"compact"`).
---@field plugins? string[] Short plugin names under `smelt.plugins.*` (e.g. `"predict"`).
---@field dialogs? string[] Short dialog names under `smelt.dialogs.*` (e.g. `"resume"`).
---@field modules? string[] Fully-qualified `smelt.<dotted>` module names, passed through verbatim.

--- Flag specification accepted by `smelt.cli.register_flag`.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.cli.RegisterFlagOpts
---@field name string Flag name without `--`. Used as the key for `smelt.cli.get`.
---@field kind smelt.cli.FlagKind `"boolean"` (default `false`), `"string"`, or `"integer"`.
---@field default? any Default value when the flag is absent from argv. Type must match `kind`.
---@field short? string Short flag character (e.g. `"u"` for `-u`). Optional.
---@field long? string Long flag name override. Defaults to `name` when absent.
---@field description? string Human-readable description for `--help`.
---@field value_optional? boolean String/Integer flags only. When true, the flag may be passed without a value (`smelt -r` valid alongside `smelt -r abc`); the value-less form yields `""` for String and `0` for Integer. Defaults to `false`. Ignored for Boolean flags.

--- Options accepted by `smelt.cmd.register`.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.cmd.RegisterOpts
---@field desc? string Human-readable description shown in `/help` and the slash-command picker.
---@field args? string[] Positional argument labels used for help text and completion hints.
---@field busy? string Busy behavior while an agent turn is running: `run` (default), `reject`, `queue_request`, or `queue_command`.
---@field startup_ok? boolean If true, the command may run before the runtime has finished bootstrapping. Defaults to `false`.
---@field hidden? boolean If true, the command is hidden from `/help` and the picker (still callable). Defaults to `false`.
---@field override? boolean If true, replace an existing command with the same name. Defaults to `false`.

--- Spec accepted by `smelt.defaults`.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.defaults.Config
---@field model? string Starting model reference (`"provider/model"` or bare model name).
---@field mode? string Starting agent mode. Must name a registered mode.
---@field reasoning_effort? string Starting reasoning effort. Known labels are `"off"`, `"low"`, `"medium"`, `"high"`, `"xhigh"`, `"max"`, and `"ultra"`; provider-defined labels are also accepted.

--- One dialog-level keymap entry. `on_press(ctx)` receives the dialog
--- context exposing `ctx.close()` and `ctx.resolve(value)` so the
--- handler can dismiss the dialog or resolve the blocking `open` call.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.dialog.Keymap
---@field key string Chord string (e.g. `"q"`, `"<Esc>"`, `"ctrl-j"`).
---@field hint? string Optional one-line hint surfaced in the dialog footer.
---@field on_press fun(ctx: any): any Handler invoked when the key fires.

--- Each item displayed in `smelt.dialog.menu`. Strings are also accepted
--- and lifted into this shape automatically.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.dialog.MenuItem
---@field label string Row text after the dim ` N. ` numbering.
---@field description? string Optional second row, rendered dim.
---@field key? string Optional chord that triggers this item (defaults to its 1-based index for items 1..9).
---@field disabled? boolean Render dimmed and skip selection/submission when true.

--- Options accepted by `smelt.dialog.menu`.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.dialog.MenuOpts
---@field selected? integer 1-based starting cursor (default 1).
---@field shortcuts? "submit"|"select"|false Digit-key behavior. Default `"submit"`.
---@field numbered? boolean Show the dim ` N. ` prefix (default true).
---@field wrap? boolean Hard-wrap long labels/descriptions to the menu width so fit-height dialogs grow vertically instead of clipping or panning.
---@field wrap_width? integer Initial wrap width used before the first resize event.
---@field on_submit? fun(ctx: any): any Override the submit path. `ctx` carries the dialog handles plus `ctx.index` (1-based) and `ctx.item`. Default resolves the active dialog with `{ index, item }`.

--- Options accepted by `smelt.dialog.open` / `smelt.dialog.new`.
--- Dialogs fit their content by default while preserving transcript context.
--- Integer `height` values are body-relative and gain
--- the top chrome row automatically. Pick one of `height` or `max_height`;
--- setting both raises.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.dialog.Opts
---@field title? string Title rendered in the chrome row.
---@field panels smelt.dialog.Panel[] Ordered list of body panels.
---@field bottom_panels? smelt.dialog.Panel[] Panels pinned to the bottom when the dialog has surplus height; extra height is placed between them and `panels`.
---@field bottom_gap? integer Minimum blank rows between `panels` and `bottom_panels` (default 0).
---@field focus? smelt.win.Win Leaf that should receive initial focus.
---@field height? any Fixed total body size: integer cells, `"N%"`, `"fill"`, or `"fit"`.
---@field max_height? any Maximum root-layout height while fitting content.
---@field min_height? any Minimum root-layout height while fitting content.
---@field blocks_agent? boolean Block the agent loop while the dialog is open. Defaults to `false`.
---@field border? table Top border style override; defaults to `{ top = "SmeltAccent" }`.
---@field resizable? boolean Set `false` to disable the default top-edge resize handle.
---@field keymaps? smelt.dialog.Keymap[] Dialog-level key bindings (merged with built-ins).
---@field close_with_q? boolean Bind `q` to close for read-only/list dialogs. Leave false for dialogs that accept text input.
---@field on_submit? fun(ctx: any): any Handler invoked on Enter. Without a handler, Enter leaves the dialog open.
---@field on_dismiss? fun(): nil Handler invoked when the dialog is dismissed.
---@field on_close? fun(ctx: any): nil Handler invoked once whenever the dialog resolves or closes.

--- One body panel inside a dialog. `leaf` is the win/leaf built by one of
--- the `smelt.dialog.*` helpers; `height` follows the same grammar as
--- `smelt.dialog.open` (integer cells, `"N%"`, `"fill"`, `"fit"`).
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.dialog.Panel
---@field leaf smelt.win.Win A leaf returned by `smelt.dialog.input/options/list/markdown/content`.
---@field height? any Integer cells, `"N%"`, `"fill"`, or `"fit"`.

--- Options accepted by `smelt.dialog.picker`. Layered on top of
--- `smelt.dialog.Opts`; only the picker-specific fields are listed.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.dialog.PickerOpts
---@field items? any[] | fun(): any[] Eager item table or a lazy producer; re-evaluated by `on_query`.
---@field render fun(item: any): table Per-item `{ text, marks }` table - see `smelt.list.new`.
---@field filter? fun(item: any): boolean Predicate applied during `set_filter` / `refresh`.
---@field placeholder? string Input placeholder; defaults to `""`.
---@field empty_text? string Shown in the list when nothing matches.
---@field on_open? fun(ctx: any): nil Fires once after the input/list have been built.
---@field on_query? fun(query: string, ctx: any): nil Fires on every keystroke; default re-applies `filter`.
---@field on_submit? fun(ctx: any): any Fires on Enter. `ctx.item` is the highlighted row; defaults to resolving with `ctx.item` when non-nil.
---@field on_dismiss? fun(): nil Fires when the dialog is dismissed.
---@field keymaps? smelt.dialog.Keymap[] Extra dialog-level keymaps merged on top of navigation bindings.
---@field title? string Forwarded to `smelt.dialog.open`.
---@field height? any Forwarded to `smelt.dialog.open`.
---@field max_height? any Forwarded to `smelt.dialog.open`.
---@field min_height? any Forwarded to `smelt.dialog.open`.
---@field blocks_agent? boolean Forwarded to `smelt.dialog.open`.

--- Typed error table delivered to `on_response` when the underlying provider call fails. `kind` is a stable string the caller can branch on; `message` is a human-readable single-line description. The struct exists purely as a doc / LuaCATS schema target - the actual table is built in `LuaExecution::fire_ask_callback` because it lands on a callback path that bypasses `FromLua` decoding.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.engine.AskError
---@field kind string One of `"network" | "rate_limited" | "quota" | "invalid_response" | "context_window" | "cyber_policy" | "cancelled" | "other"`.
---@field message string Human-readable single-line description (newlines collapsed to spaces).

--- One text-only message used by request hooks that exchange plain user/assistant rows.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.engine.AskMessage
---@field role string Either `"user"` or `"assistant"`. Other roles are silently dropped.
---@field content string Message body as plain text.

--- Structured JSON-output specification for `smelt.engine.ask`.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.engine.AskResponseFormat
---@field name string Schema name (used by some providers as the response_format label).
---@field schema table JSON schema describing the expected response shape. Accepts a Lua table that round-trips through `lua_table_to_json` into a JSON value.

--- Spec for `smelt.engine.ask`.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.engine.AskSpec
---@field system string System prompt sent before the conversation.
---@field messages? table Prior turns. When present, this must be a sequence of full `protocol::Message`-shaped rows such as `{ role, content?, reasoning_content?, tool_calls?, tool_call_id?, is_error? }`.
---@field question? string Single-shot question appended as a final user message after `messages`.
---@field model? string Model reference (`"provider/model"` or a bare name resolved against the configured providers). When `nil`, falls back to the primary model.
---@field response_format? smelt.engine.AskResponseFormat JSON-schema response constraint.
---@field reasoning_effort? string Reasoning effort for the request. Provider-defined labels are accepted. When omitted, starts at `"off"` and reconciles to the selected model's advertised levels.
---@field guard? table Lifecycle guard returned by `smelt.lifecycle.guard(...)`. When provided, the Lua bootstrap suppresses `on_delta` and `on_response` after the guard expires.
---@field visible_retries? boolean Surface provider retry events on the main work indicator. Intended for foreground auxiliary work such as compaction.
---@field on_delta? fun(value: string) Fires for each streamed assistant text delta when provided. The final `on_response` still fires once with the full assistant message.
---@field on_response? fun(arg1: any, arg2: smelt.engine.AskError?) Fires once with `(response, err)`. On success `err` is `nil` and `response` is a full assistant message table; on failure `response` is `nil` and `err` is a `smelt.engine.AskError` table.

--- Front-matter override block accepted by `smelt.engine.submit_command`. Mirrors what plugin commands set in their markdown header. Tool-name keys (e.g. `bash`, `edit`) become per-subcommand pattern buckets.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.engine.CommandOverrides
---@field description? string Override the command description shown in `/help`.
---@field provider? string Force a specific provider for this command's turn.
---@field model? string Force a specific model id.
---@field temperature? number Sampling temperature override.
---@field top_p? number Nucleus-sampling cutoff override.
---@field top_k? integer Top-k sampling cutoff override.
---@field min_p? number Minimum-probability cutoff override.
---@field repeat_penalty? number Repeat-penalty override.
---@field reasoning_effort? string Reasoning-effort override. Known and provider-defined string labels are accepted.
---@field tools? smelt.engine.RuleOverride Per-tool `allow`/`ask`/`deny` patterns for the duration of the turn.
---@field [string] smelt.engine.RuleOverride Per-subcommand pattern buckets keyed by tool name.

--- Spec for `smelt.engine.ask_inherited`.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.engine.InheritedAskSpec
---@field messages? table Prior turns. When present, this must be a sequence of full `protocol::Message`-shaped rows such as `{ role, content?, reasoning_content?, tool_calls?, tool_call_id?, is_error? }`. When omitted or empty, the live model-visible history is inherited.
---@field question? string Single-shot question appended as a final user message after `messages`.
---@field model? string Model reference (`"provider/model"` or a bare name resolved against the configured providers). When `nil`, falls back to the primary model.
---@field response_format? smelt.engine.AskResponseFormat JSON-schema response constraint.
---@field reasoning_effort? string Reasoning effort for the request. Provider-defined labels are accepted. When omitted, starts at `"off"` and reconciles to the selected model's advertised levels.
---@field guard? table Lifecycle guard returned by `smelt.lifecycle.guard(...)`. When provided, the Lua bootstrap suppresses `on_delta` and `on_response` after the guard expires.
---@field visible_retries? boolean Surface provider retry events on the main work indicator. Intended for foreground auxiliary work such as compaction.
---@field on_delta? fun(value: string) Fires for each streamed assistant text delta when provided. The final `on_response` still fires once with the full assistant message.
---@field on_response? fun(arg1: any, arg2: smelt.engine.AskError?) Fires once with `(response, err)`. On success `err` is `nil` and `response` is a full assistant message table; on failure `response` is `nil` and `err` is a `smelt.engine.AskError` table.

--- Token accounting breakdown passed inside `smelt.engine.PrepareRequest`.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.engine.PrepareContextEstimate
---@field source string One of `"full_request_estimate" | "provider_snapshot" | "provider_snapshot_plus_history_delta" | "checkpoint_estimate" | "checkpoint_estimate_plus_history_delta"`.
---@field total_context_tokens integer Total active-context estimate used by auto-compaction.
---@field provider_context_tokens? integer Latest provider-reported active context, when available.
---@field estimated_delta_tokens integer Locally estimated tokens added on top of provider usage.
---@field latest_snapshot_history_len? integer History length attached to the latest token snapshot, when available.
---@field current_history_len integer Current session history length at the prepare hook.

--- Request object passed to `smelt.engine.on_prepare_request`.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.engine.PrepareRequest
---@field messages smelt.engine.AskMessage[] Model-visible conversation excluding the system prompt.
---@field estimated_tokens integer Conservative token estimate for the request about to be sent, including system prompt, messages, and tool definitions.
---@field estimated_context_tokens integer Active-context estimate for auto-compaction. When a provider has reported context usage, this starts from that server-observed count and adds only local messages appended after the matching token snapshot. After a compaction checkpoint and before the next provider usage report, this starts from the checkpoint's post-compaction estimate. Before either baseline exists, it equals `estimated_tokens`.
---@field context_estimate smelt.engine.PrepareContextEstimate Structured breakdown explaining how `estimated_context_tokens` was computed.

--- Subcommand rule override accepted inside `CommandOverrides`. Mirrors the front-matter `{ allow?, ask?, deny? }` shape.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.engine.RuleOverride
---@field allow? string[] Patterns that auto-allow.
---@field ask? string[] Patterns that always prompt.
---@field deny? string[] Patterns that auto-deny.

--- Single-line input handle returned by `smelt.input.new(opts)`.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.input.Input
---@field win fun(): smelt.win.Win Return the underlying Win handle for layout, focus, and advanced event bindings.
---@field buf fun(): smelt.buf.Buf? Return the backing buffer, or `nil` if the input window is gone.
---@field text fun(): string Return the current input text.
---@field set_text fun(text: string): nil Replace the current input text. Newlines are collapsed to spaces and the cursor moves to the end.
---@field on fun(event: smelt.input.Event, func: fun(value: table)): smelt.Reg Subscribe to `change`, `submit`, or `cancel`. Callback payload carries `ctx.text`.
---@field key fun(chord: string, func: fun(value: table)): smelt.Reg Bind `func` to `chord` on the underlying input window. Returns a Reg handle.

--- Opaque block-layout node returned by `smelt.layout.*` constructors and accepted by transcript renderers, tool previews, and other content-layout APIs.
--- Classification: Advanced - Documented low-level capability for plugins that need full control. It may evolve more freely than the Supported facade.
---@class smelt.layout.Node

--- Cancellation and supersession guard returned by `smelt.lifecycle.guard`.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.lifecycle.Guard
---@field alive fun(self:smelt.lifecycle.Guard):boolean Return true while every captured epoch still matches and the guard was not cancelled or superseded.
---@field cancel fun(self:smelt.lifecycle.Guard) Mark the guard stale immediately.
---@field latest fun(self:smelt.lifecycle.Guard,key:string):smelt.lifecycle.Guard Mark this guard as the latest request for `key`; older guards with the same key become stale.
---@field wrap fun(self:smelt.lifecycle.Guard,fn:function):function Return a wrapper that calls `fn` only while the guard is alive.

--- Structured list handle returned by `smelt.list.new`.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.list.List
---@field refresh fun(self: smelt.list.List) Re-apply the filter, render visible rows, and move the cursor to the first item.
---@field set_items fun(self: smelt.list.List, items: any[]?) Replace the source items and refresh the list.
---@field set_items_preserve fun(self: smelt.list.List, items: any[]?, key_fn: fun(item: any): any) Replace items and restore the selected row by its `key_fn` result when possible.
---@field set_filter fun(self: smelt.list.List, fn: (fun(item: any): boolean)?) Replace or clear the filter predicate and refresh the list.
---@field set_render fun(self: smelt.list.List, fn: fun(item: any): smelt.list.Row) Replace the row renderer and redraw the current visible items.
---@field visible fun(self: smelt.list.List): any[] Return the filtered items in display order.
---@field size fun(self: smelt.list.List): integer Return the number of visible items.
---@field selected_index fun(self: smelt.list.List): integer? Return the selected visible-item index (0-based), or `nil` when empty.
---@field selected fun(self: smelt.list.List): any Return the selected source item, or `nil` when empty.
---@field set_cursor fun(self: smelt.list.List, i: integer) Move to the clamped 0-based visible-item index.
---@field move_cursor fun(self: smelt.list.List, delta: integer) Move the selection by `delta` rows, clamped to the visible list.

--- Extmark attached to one rendered list row.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.list.Mark
---@field col? integer 0-based byte column for the mark.
---@field opts? smelt.buf.MarkOpts Mark/highlight options.

--- Options accepted by `smelt.list.new`. `leaf` and `buf` are mandatory -
--- they own the rendered selection cursor and the backing line buffer;
--- the rest configure how data is sourced, filtered, and rendered.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.list.Opts
---@field leaf smelt.win.Win Selectable list leaf (typically from `smelt.dialog.list`).
---@field buf smelt.buf.Buf Backing buffer that mirrors the rendered rows.
---@field items? any[] Initial item set. Mutate via `:set_items(...)` later if needed.
---@field render fun(item: any): smelt.list.Row Returns `{ text, spans?, marks? }` per visible row.
---@field filter? fun(item: any): boolean Predicate re-run on `:set_filter` / `:refresh`.
---@field empty_text? string Placeholder line shown when no row passes the filter.
---@field anchor? "top"|"bottom" Render short lists at the top or bottom of the viewport. Defaults to "top".

--- Row shape returned by a `smelt.list` render callback.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.list.Row
---@field text? string Plain row text. Used when `spans` is omitted.
---@field spans? smelt.list.Span[] Styled spans for the row.
---@field marks? smelt.list.Mark[] Extmarks to apply after rendering.

--- Styled text segment in a rendered list row.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.list.Span
---@field text string Span text.
---@field style? table Highlight style passed through to `buf:styled`.
---@field syntax? string Inline syntax token for this span.

--- MCP server config accepted by `smelt.mcp.register`.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.mcp.Config
---@field type? string Server kind. Only `"local"` (the default) is supported.
---@field command? string|string[] Executable + leading argv. Either a string (`"my-server"`) or a list (`{"my-server", "--flag"}`).
---@field args? string[] Trailing arguments appended after `command`.
---@field description? string Human-readable description shown by `/mcp`.
---@field env? table<string, string> Extra environment variables to set on the child process.
---@field timeout? integer Request timeout in milliseconds. Defaults to `30000`.
---@field enabled? boolean Whether the server is enabled. Defaults to `true`.

--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.mode.Mode
---@field name string
---@field label string
---@field icon string
---@field hl_group string
---@field note string
---@field permissions table

--- Source-bound notify handle returned by `smelt.notify.scoped`.
--- Use `handle.info(msg)`, `handle.error(msg)`, or `handle.warn(msg)` to
--- tag every toast with the bound source.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.notify.Scoped
---@field info fun(msg: string) Raise an informational toast tagged with the bound source.
---@field error fun(msg: string) Raise an error toast tagged with the bound source.
---@field warn fun(msg: string) Raise a warning toast tagged with the bound source.

--- Overlay drag configuration table. Use `true` for the floating default: title chrome plus inert-body drag.
--- Classification: Advanced - Documented low-level capability for plugins that need full control. It may evolve more freely than the Supported facade.
---@class smelt.overlay.DragConfig
---@field title? boolean When true, the overlay chrome moves the overlay unless a resize handle owns the cell.
---@field body? boolean | "inert" `true` moves from any body leaf; `"inert"` moves only from non-focusable, non-selectable leaves.

--- One overlay-scoped key binding installed by `smelt.overlay.new({ keymaps = ... })`.
--- Classification: Advanced - Documented low-level capability for plugins that need full control. It may evolve more freely than the Supported facade.
---@class smelt.overlay.Keymap
---@field key string Key chord such as `<Esc>`, `<C-j>`, or `q`.
---@field on_press fun(ctx: table) Handler invoked when the key fires while any overlay leaf has focus.
---@field hint? string Human-readable hint for key-discovery plugins.

--- Options for `smelt.overlay.new(opts)`. The overlay body comes from a `smelt.ui.layout` tree.
--- Classification: Advanced - Documented low-level capability for plugins that need full control. It may evolve more freely than the Supported facade.
---@class smelt.overlay.NewOpts
---@field layout smelt.ui.layout Layout tree to render inside the overlay.
---@field name? string Stable name used to hot-reload this overlay in place.
---@field title? string | table Optional title rendered in the overlay border.
---@field border? table Border style override; parsed with the shared border vocabulary.
---@field anchor? "dock_bottom"|"dock_top"|"dock_left"|"dock_right"|"center"|"screen_at"|"win" Where to place the overlay. Defaults to `dock_bottom`.
---@field above_rows? integer Rows to keep clear above the bottom dock, typically the statusline height.
---@field target? smelt.win.Win | integer Target window for `anchor = "win"`.
---@field attach? string Alignment point for `anchor = "win"` such as `nw`, `center`, or `se`.
---@field row? integer Screen row offset for `anchor = "screen_at"`.
---@field col? integer Screen column offset for `anchor = "screen_at"`.
---@field row_offset? integer Row offset for `anchor = "win"`.
---@field col_offset? integer Column offset for `anchor = "win"`.
---@field corner? string Corner used by `anchor = "screen_at"` (`nw`, `ne`, `sw`, or `se`).
---@field width? integer | string | table Overlay width constraint. Accepts cells, `"N%"`, `"fit"`, `"fill"`, `"min:N"`, `"max:N"`, `"ratio:N/M"`, or long table form.
---@field height? integer | string | table Overlay height constraint. Same vocabulary as `width`.
---@field max_width? integer | string | table Optional upper bound applied after width resolves.
---@field max_height? integer | string | table Optional upper bound applied after height resolves.
---@field min_width? integer | string | table Optional lower bound applied after width resolves.
---@field min_height? integer | string | table Optional lower bound applied after height resolves.
---@field modal? boolean Whether the overlay blocks input behind it. Defaults to true.
---@field blocks_agent? boolean Whether the overlay should block agent progress while open.
---@field z? integer Z-index. Higher overlays render above lower overlays.
---@field draggable? boolean | smelt.overlay.DragConfig Enable or configure mouse dragging.
---@field resizable? boolean | smelt.overlay.ResizeConfig Enable or configure mouse resize handles.
---@field keymaps? smelt.overlay.Keymap[] Overlay-scoped key bindings.

--- Overlay handle returned by `smelt.overlay.new(opts)`.
--- Classification: Advanced - Documented low-level capability for plugins that need full control. It may evolve more freely than the Supported facade.
---@class smelt.overlay.Overlay
---@field close fun(): nil Close the overlay. No-op if already closed.
---@field key fun(chord: string, func: fun(value: table)): smelt.Reg Bind `func` to `chord` on this overlay. Fires when any leaf of the overlay holds focus, after a per-window keymap miss but before global Lua keymaps. Returns a Reg whose `:remove()` undoes the binding.

--- Overlay resize configuration table. Use `true` for the floating default: left/right/bottom edges and corners, leaving the top chrome for drag.
--- Classification: Advanced - Documented low-level capability for plugins that need full control. It may evolve more freely than the Supported facade.
---@class smelt.overlay.ResizeConfig
---@field top? boolean Enable top-edge resize.
---@field right? boolean Enable right-edge resize.
---@field bottom? boolean Enable bottom-edge resize.
---@field left? boolean Enable left-edge resize.
---@field corners? boolean Upgrade cells where two enabled edges meet into diagonal resize handles.

--- Opaque handle returned by `smelt.paint.register`. Usable directly in `smelt.ui.layout.leaf(handle, opts)` (it stands in for a Win in layout leaves).
--- Classification: Advanced - Documented low-level capability for plugins that need full control. It may evolve more freely than the Supported facade.
---@class smelt.paint.Paint
---@field remove fun(): boolean Drop the paint callback. Returns `true` if it was still registered. Subsequent paints of this id no-op.
---@field rect fun(): any Return the paint leaf's current screen rect as `{ row, col, width, height }`, or `nil` until the first render lays it out.
---@field on fun(event: smelt.paint.Event, func: fun(value: table)): smelt.Reg Subscribe `func` to `event` on this paint leaf. Returns a Reg handle whose `:remove()` undoes the subscription.

--- Grid slice passed to paint callbacks. Methods delegate to the live grid slice for the current frame; out-of-scope calls fail cleanly.
--- Classification: Advanced - Documented low-level capability for plugins that need full control. It may evolve more freely than the Supported facade.
---@class smelt.paint.Slice
---@field width fun(): integer Return the slice width in cells.
---@field height fun(): integer Return the slice height in cells.
---@field set fun(row: integer, col: integer, ch: string, style: table?): nil Write exactly one grapheme cluster with optional style at (row, col).
---@field put_str fun(row: integer, col: integer, text: string, style: table?): nil Write a string with optional style at (row, col).
---@field fill_rect fun(row: integer, col: integer, w: integer, h: integer, ch: string?, style: table?): nil Fill a rectangle with one optional Unicode scalar and style.

--- Effect-level decisions that apply to tools without a more specific rule.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.permissions.EffectRules
---@field read? smelt.permissions.Decision Decision for tools that only read data.
---@field write? smelt.permissions.Decision Decision for tools that write or mutate data.
---@field network? smelt.permissions.Decision Decision for tools that access the network.
---@field process? smelt.permissions.Decision Decision for tools that start or control processes.
---@field config? smelt.permissions.Decision Decision for tools that modify configuration.
---@field user? smelt.permissions.Decision Decision for tools that require direct user interaction.
---@field other? smelt.permissions.Decision Decision for tools whose effect has no more specific category.

--- Current permission state returned by `smelt.permissions.list()`.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.permissions.ListResult
---@field session smelt.permissions.SessionEntry[] Session-scoped tool/pattern approvals for this run.
---@field path_grants smelt.permissions.SessionPathGrant[] Session-scoped path grants for this run.
---@field workspace smelt.permissions.WorkspaceRule[] Workspace rules loaded from the on-disk store rooted at the current cwd.
---@field workspace_revision integer Revision required to replace the workspace rules safely.
---@field repository smelt.permissions.WorkspaceRule[] Repository rules shared by all worktrees. Empty outside a Git repository.
---@field repository_revision integer Revision required to replace the repository rules safely.

--- Permission slots that apply within a single agent mode.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.permissions.ModePerms
---@field tools? smelt.permissions.RuleSet Exact tool-name `allow`/`ask`/`deny` entries.
---@field effects? smelt.permissions.EffectRules Effect-level decisions keyed by effect name.
---@field patterns? table<string, smelt.permissions.RuleSet> Tool-specific argument patterns keyed by tool name (`"bash"`, `"web_fetch"`, …).

--- Spec for `smelt.permissions.extend`. Each mode falls back to `default`.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.permissions.PolicySpec
---@field default? smelt.permissions.ModePerms Baseline rules applied unless a mode-specific slot overrides.
---@field [string] smelt.permissions.ModePerms Mode-specific rules keyed by registered mode name.

--- One exact permission entry to revoke transactionally.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.permissions.RevokeSpec
---@field scope string Permission scope: `"session"`, `"workspace"`, or `"repository"`.
---@field tool string Tool name the entry applies to. Use `"directory"` for path-prefix entries.
---@field pattern string Exact pattern to remove. Use `"*"` for a blanket tool approval.

--- `allow`/`ask`/`deny` arrays accepted by permission policy sections.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.permissions.RuleSet
---@field allow? string[] Patterns that auto-allow without prompting.
---@field ask? string[] Patterns that always prompt.
---@field deny? string[] Patterns that auto-deny.

--- Revision-checked replacement for one persisted permission scope.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.permissions.ScopeReplacement
---@field revision integer Revision returned by the `smelt.permissions.list()` snapshot being edited.
---@field rules smelt.permissions.WorkspaceRule[] Complete replacement rule set for this scope.

--- A single session permission entry (one approved tool/pattern pair).
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.permissions.SessionEntry
---@field tool string Tool name the rule applies to (e.g. `"bash"`). Special value `"directory"` grants generic path access.
---@field pattern string Pattern matched against the tool's argument bucket.

--- A tool-specific session path grant. Grants are in-memory only and can satisfy workspace path checks for the matching tool. When `mode` is set, the grant applies only in that mode.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.permissions.SessionPathGrant
---@field kind string Grant kind. Currently only `"path"` is supported.
---@field mode? string Optional mode, e.g. `"plan"`. Omit for mode-independent path trust.
---@field tool string Tool name the grant applies to, e.g. `"read_file"` or `"edit_file"`.
---@field access string Path access granted: `"read"` or `"write"`.
---@field path_prefix string Directory prefix covered by the grant.

--- Spec for `smelt.permissions.sync`.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.permissions.SyncSpec
---@field session? smelt.permissions.SessionEntry[] Session entries to replace for this run. Omit to leave them unchanged.
---@field path_grants? smelt.permissions.SessionPathGrant[] Tool-specific session path grants to replace. Omit to leave them unchanged.
---@field workspace? smelt.permissions.ScopeReplacement Revision-checked workspace replacement. Cannot be combined with `repository`.
---@field repository? smelt.permissions.ScopeReplacement Revision-checked repository replacement. Cannot be combined with `workspace`.

--- A workspace permission rule (one tool with N patterns, persisted to disk).
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.permissions.WorkspaceRule
---@field tool string Tool name the rule applies to.
---@field patterns string[] Patterns granted for this tool.

--- Row accepted by picker constructors. A bare string is also accepted and is treated as `{ label = string }`.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.picker.Item
---@field label string Primary text shown for this row.
---@field description? string Secondary text shown next to the label.
---@field prefix? string Small prefix rendered before the label.
---@field ansi_color? integer ANSI color slot for the prefix.
---@field label_color? integer ANSI color slot for the label.
---@field search_terms? string Extra text considered by fuzzy pickers.

--- Options for the low-level non-blocking picker handle constructor.
--- Classification: Advanced - Documented low-level capability for plugins that need full control. It may evolve more freely than the Supported facade.
---@class smelt.picker.NewOpts
---@field items (string | smelt.picker.Item)[] Initial picker rows. Must be non-empty.
---@field placement? "center"|"bottom"|"cursor"|"prompt_docked" Where to place the picker. Defaults to `center`.

--- High-level picker options. Static floating pickers accept `items` and
--- `placement`. Prompt-docked pickers also support ranking, providers, and
--- persistent `on_enter` handling.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.picker.OpenOpts
---@field items? (string|smelt.picker.Item)[] | fun(): (string|smelt.picker.Item)[] Eager list or lazy producer.
---@field placement? "center"|"bottom"|"cursor"|"prompt_docked" Picker placement. Ranking, providers, and persistent mode use `prompt_docked`.
---@field provider? fun(query: string, limit: integer): table Async provider returning `{ items, searching?, scanning?, message?, status? }`.
---@field limit? integer Maximum rows requested from `provider`; defaults to 200.
---@field poll_ms? integer Refresh interval while provider returns `{ scanning = true }` or `{ searching = true }`.
---@field loading_delay_ms? integer Delay before showing an initial loading row when there are no stale rows to keep.
---@field loading_poll_ms? integer Quiet polling interval before the initial loading row appears.
---@field on_select? fun(item: string|smelt.picker.Item): nil Fires on every cursor move.
---@field on_enter? fun(item: string|smelt.picker.Item, idx: integer): nil Persistent-mode accept handler.
---@field rank? fun(items: table[], query: string, original: (string|smelt.picker.Item)[]): integer[] Custom filter/ranker. Return 1-based row indices in display order.
---@field on_dismiss? fun(): nil Fires on Esc/Ctrl-C.

--- Accepted value returned by `smelt.picker.open`; dismissal returns `nil`.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.picker.OpenResult
---@field index integer 1-based accepted item index.
---@field item any Original item from `opts.items`.
---@field action "enter"|"tab" Accept action. Floating pickers return `"enter"`.

--- Picker handle returned by `smelt.picker.new(opts)`. Setter methods return the same handle for chaining.
--- Classification: Advanced - Documented low-level capability for plugins that need full control. It may evolve more freely than the Supported facade.
---@class smelt.picker.Picker
---@field win fun(): smelt.win.Win Return the underlying Win handle (use `win:key(...)`, `win:on(...)` to bind input).
---@field close fun(): nil Close the picker overlay. No-op if already closed.
---@field items fun(items: table, selected: integer?): smelt.picker.Picker Replace the picker's items. Each entry is a string or `{ label, description?, ansi_color?, label_color?, prefix?, icon?, ... }`. `icon = { kind = "file"|"dir", path = string }` renders file-list icons unless `prefix` is set. `selected` is the 0-based logical index to land the cursor on (default 0 - top of the new list); pass the current selection here to avoid a flash to row 0 followed by a separate `:selected()` call. Returns the handle for chaining.
---@field selected fun(idx: integer?): any Read or write the current logical selection (0-based). Without arg returns the index (`nil` if the picker is empty); with arg sets the selection and returns the handle for chaining.
---@field move fun(delta: integer): smelt.picker.Picker Move the picker's cursor by `delta` rows (clamped to the buffer's line count). Returns the handle for chaining.

--- Completer specification handed to `smelt.prompt.register_completer` for full candidate
--- sets ranked in Lua.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.prompt.CompleterSpec
---@field detect fun(text: string, cpos: integer): integer? Detect the active trigger and return its 0-based anchor byte offset.
---@field items fun(anchor: integer, text: string, cpos: integer): table[] Build a full candidate set for Lua-side ranking.
---@field query fun(text: string, anchor: integer, cpos: integer): string Query used for Lua-side ranking.
---@field accept fun(item: table, anchor: integer, action: string): nil Splice the accepted candidate into the prompt.
---@field manual? boolean Whether Tab can open this completer when no picker is active.
---@field auto? boolean Set false to prevent text_changed from auto-opening this completer.
---@field accept_single? boolean Set false to keep a manual Tab picker open when there is exactly one match.
---@field on_select? fun(item: table): nil Live selection callback.

--- Completer specification handed to `smelt.prompt.register_completer` for bounded,
--- already-ranked providers.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.prompt.MatchesCompleterSpec
---@field detect fun(text: string, cpos: integer): integer? Detect the active trigger and return its 0-based anchor byte offset.
---@field matches fun(anchor: integer, text: string, cpos: integer, limit: integer): table[]|table Return bounded already-filtered/ranked rows, or `{ items, status?, message? }` for providers with loading/empty/error states.
---@field query? fun(text: string, anchor: integer, cpos: integer): string Query identity used to distinguish user edits from provider refreshes.
---@field accept fun(item: table, anchor: integer, action: string): nil Splice the accepted candidate into the prompt.
---@field manual? boolean Whether Tab can open this completer when no picker is active.
---@field auto? boolean Set false to prevent text_changed from auto-opening this completer.
---@field accept_single? boolean Set false to keep a manual Tab picker open when there is exactly one match.
---@field limit? integer Maximum rows requested from `matches` providers.
---@field poll_ms? integer Refresh interval while `matches` returns `{ scanning = true }` or `{ searching = true }`.
---@field loading_delay_ms? integer Delay before showing an initial loading row when there are no stale rows to keep.
---@field loading_poll_ms? integer Quiet polling interval before the initial loading row appears.
---@field on_select? fun(item: table): nil Live selection callback.

--- Spec accepted by `smelt.provider.register`.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.provider.Config
---@field type? string Provider kind tag (`"openai"`, `"anthropic"`, etc.).
---@field api_base? string Base URL the engine talks to.
---@field api_key_env? string Environment variable that holds the bearer token.
---@field models? string|smelt.provider.Model[] Models offered by this provider.

--- One model entry in a provider's `models` list. Plugin authors can pass either a bare model id string or a full table - the wrapper handles both forms transparently.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.provider.Model
---@field name? string Model id as it appears in API requests.
---@field temperature? number Default sampling temperature.
---@field top_p? number Default nucleus-sampling cutoff.
---@field top_k? integer Default top-k sampling cutoff.
---@field min_p? number Default minimum-probability cutoff.
---@field repeat_penalty? number Default repeat penalty.
---@field tool_calling? boolean Whether the model supports tool calls.
---@field input_cost? number Cost per 1M input tokens in USD.
---@field output_cost? number Cost per 1M output tokens in USD.
---@field cache_read_cost? number Cost per 1M cache-read tokens in USD.
---@field cache_write_cost? number Cost per 1M cache-write tokens in USD.
---@field max_tokens? integer Maximum output tokens for this model. Defaults to the model's own limit, falling back to 4096 if unknown.
---@field thinking_budgets? table Per-level token budgets for budget-based thinking.
---@field context_window? integer Total context window, in tokens.
---@field supports_reasoning? boolean Whether this model supports reasoning/thinking parameters.
---@field supports_fast_mode? boolean Whether this model supports accelerated inference.
---@field input_modalities? string[] Input modalities supported by this model, for example { "text", "image", "pdf" }.

--- Provider rows and loading state returned by `smelt.provider.normalize`.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.provider.NormalizedResult
---@field rows table[] Rows to render after optional synthetic message insertion.
---@field result? table Original provider result when the input used the provider shape.
---@field loading boolean True while the provider is still scanning or searching.

--- Spec accepted by `smelt.remember`.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.remember.Config
---@field model? boolean When true (default), restore the last-used model on launch.
---@field mode? boolean When true (default), restore the last-used agent mode on launch.
---@field reasoning_effort? boolean When true (default), restore the last-used reasoning effort on launch.

--- Options for `smelt.render.diff_split`.
--- Classification: Advanced - Documented low-level capability for plugins that need full control. It may evolve more freely than the Supported facade.
---@class smelt.render.DiffSplitOpts
---@field old? string Left/pre-edit text.
---@field new? string Right/post-edit text.
---@field lang? string Syntax language token such as `"rust"`, `"lua"`, or `"py"`.
---@field path? string Path whose extension is used when `lang` is omitted.

--- Options for `smelt.render.syntax`.
--- Classification: Advanced - Documented low-level capability for plugins that need full control. It may evolve more freely than the Supported facade.
---@class smelt.render.SyntaxOpts
---@field content? string Source code to render.
---@field lang? string Syntax language token such as `"rust"`, `"lua"`, or `"py"`.
---@field path? string Path whose extension is used when `lang` is omitted.

--- Options for `smelt.render.text`.
--- Classification: Advanced - Documented low-level capability for plugins that need full control. It may evolve more freely than the Supported facade.
---@class smelt.render.TextOpts
---@field hl_group? string Highlight group applied to the whole block. When omitted, text renders dim.
---@field width? integer Wrapping width in terminal cells. Defaults to the current terminal width.

--- Color value. Set `ansi` (256-color palette index) or `rgb` (`{R, G, B}` triple) for a direct color, or `dark` / `light` (themselves `ColorDecl`s) for a branch that resolves against the terminal background. A matching-side branch wins over the direct fields.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.theme.ColorDecl
---@field ansi? integer ANSI 256-color palette index for the default (non-branched) case.
---@field rgb? integer[] `[r, g, b]` sRGB triple for the default (non-branched) case.
---@field light? smelt.theme.ColorDecl Color this branch resolves to when `is_light == true`.
---@field dark? smelt.theme.ColorDecl Color this branch resolves to when `is_light == false`.

--- Style table for a single highlight group. Every field is optional - unset fields stay at `Style::default()`. Pass a string in place of this struct (at the group-map level) to alias another group.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.theme.StyleDecl
---@field fg? smelt.theme.ColorDecl Foreground color.
---@field bg? smelt.theme.ColorDecl Background color.
---@field bold? boolean Bold text.
---@field italic? boolean Italic text.
---@field dim? boolean Dim / faint text.
---@field underline? boolean Underline.
---@field crossedout? boolean Strikethrough.
---@field reverse? boolean Reverse video.

--- Colorscheme table with optional metadata and a required `groups` map. `syntax` selects a bundled two-face syntax theme for code highlighting. `light` marks the palette as light or dark; omit it to use terminal background detection. Every themable color (foreground, background, diff row and inline fills, scrollbar colors, mode indicators) is a group.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.theme.ThemeSpec
---@field name? string Display name for this colorscheme.
---@field syntax? string Bundled syntect/two-face syntax theme name for code highlighting.
---@field light? boolean Whether this colorscheme is light. Omit to use terminal background detection.
---@field groups table<string, string | smelt.theme.StyleDecl> Highlight groups keyed by group name.

--- Per-mode default decisions installed by `smelt.tools.register`. Keys are mode names and values are `"allow"`, `"ask"`, or `"deny"`.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.tools.PermissionDefaults
---@field [string] smelt.tools.Decision Per-mode decisions keyed by registered mode name.

--- Plugin tool definition passed to `smelt.tools.register`. `execute` is required; the remaining hooks are optional and are invoked at well-defined points during a tool turn - see the field docs for each callback's contract.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.tools.ToolDef
---@field name string Tool name; used as the engine-facing identifier.
---@field execute function Required handler: `execute(args, ctx)` - returns the tool result.
---@field description? string Human-readable description shown to the model.
---@field parameters? table JSON-schema parameters table passed through to the model.
---@field permission_defaults? smelt.tools.PermissionDefaults Per-mode default decisions.
---@field effect? smelt.tools.Effect Coarse side-effect classification used by permission policy.
---@field default_allow? string[] Subcommand patterns that auto-allow without prompting.
---@field subpattern_parser? string Built-in subpattern parser kind (e.g. `"bash"`).
---@field modes? table Agent modes the tool is available in; nil means all modes.
---@field execution_mode? string `"concurrent"` (default) or `"sequential"`.
---@field summary? function `summary(args) -> string | styled_lines | nil` - styled label rendered in the transcript header AND confirm dialog body header. Plain string is auto-wrapped as one plain span; the styled-lines form is `{ { { text, syntax?, selectable?, title_suffix?, style? }, ... }, ... }` - same span shape as `buf:styled` plus optional `selectable = false` for chrome text and `title_suffix = true` for metadata rendered after the live tool timer.
---@field approval_patterns? function `approval_patterns(args, ctx) -> string[]` - patterns offered as one-click approvals.
---@field preflight? function `preflight(args, ctx) -> table?` - validation hook; nil result skips.
---@field paths_for_workspace? function `paths_for_workspace(args) -> (string|{ path: string, kind?: "file"|"directory"|"unknown" })[]` - paths this invocation will touch. Callback errors and malformed entries reject tool evaluation rather than being treated as no paths.
---@field preview? function `preview(args) -> smelt.layout` - pre-execute preview render. The confirm dialog renders it directly into the preview pane.
---@field preview_output? function `preview_output(args) -> { content, is_error?, metadata?, display_content? }|nil` - immutable pending transcript output derived from final streamed arguments before execution. Growing display payloads belong in `display_content`, not JSON metadata.
---@field draft_preview? function `draft_preview(args, ctx, block, opts) -> smelt.layout|nil` - best-effort renderer for streamed partial arguments in the transcript.
---@field watchdog_timeout_ms? integer Outer watchdog deadline for this tool's coroutine, in milliseconds. This is separate from any timeout the tool implements internally.
---@field watchdog_max_timeout_ms? integer Maximum watchdog deadline accepted from tool arguments, in milliseconds.
---@field watchdog_timeout_arg? string Tool argument that controls the watchdog deadline. Defaults to `timeout_ms`.
---@field watchdog_timeout_arg_scale_ms? integer Multiplier that converts `watchdog_timeout_arg` values to milliseconds. Use `1000` for second-based arguments.
---@field watchdog_grace_ms? integer Extra time added when a tool argument sets the watchdog deadline, in milliseconds.
---@field headless? boolean Whether the tool is available when running headless. Defaults to true. Set to false for tools that require a UI surface (dialogs, menus, managed worktree creation, cwd switching).
---@field override? boolean Replace a core tool of the same name (advanced).

--- Opaque top-level string argument passed to transcript renderers. Complete field
--- content remains in Rust and is available only through `smelt.layout.content`.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.transcript.ArgumentField
---@field name string Top-level argument name.
---@field content_id integer Stable shared-content id accepted by `smelt.layout.content`.
---@field content_revision integer Monotonic content revision.
---@field content_bytes integer Current field size in bytes.
---@field content_lines integer Current logical line count.
---@field content_preview string Bounded text preview for labels and fallback UI, not complete content.
---@field complete boolean True when the JSON parser has consumed the complete field value.

--- Bounded semantic transcript metadata passed to the root renderer.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.transcript.Block
---@field id integer Stable block id within the session.
---@field index integer Zero-based block index in transcript order.
---@field kind "user"|"assistant"|"thinking"|"tool"|"group"|"code"|"exec"|"mode"|"process_status"|"compacted"|"compaction_preview" Block kind.
---@field text? string User/mode/process text.
---@field user_lines? table User text as styled span lines, including slash/ref/image accents.
---@field content? string Code content.
---@field content_id? integer Stable shared-content id for assistant and thinking blocks.
---@field content_revision? integer Monotonic shared-content revision.
---@field content_bytes? integer Shared content size in bytes.
---@field content_lines? integer Shared content logical line count.
---@field content_preview? string Bounded preview for labels and fallback UI, not complete content.
---@field title? string Latest structured reasoning-summary title.
---@field summary_titles? string[] Ordered structured reasoning-summary title history.
---@field reasoning_kind? "summary"|"raw" Reasoning source for thinking blocks.
---@field image_labels? string[] User image labels.
---@field icon? string Mode icon.
---@field hl_group? string Mode/process highlight group.
---@field lang? string Code language.
---@field call_id? string Tool call id.
---@field name? string Tool name.
---@field args? table Bounded tool-argument previews and complete non-string structured values.
---@field argument_fields? smelt.transcript.ArgumentField[] Opaque top-level string arguments. Complete field content is never included in renderer metadata.
---@field summary? any Tool styled summary lines or compacted summary text.
---@field summary_text? string Tool summary flattened to plain text.
---@field status? "pending"|"confirm"|"ok"|"err"|"denied" Tool status.
---@field called_at_ms? integer Invocation start as Unix epoch milliseconds.
---@field elapsed_ms? integer Best-known execution duration in milliseconds.
---@field elapsed_active? boolean True only while elapsed time can continue advancing.
---@field thinking_summary? string Folded thinking summary text.
---@field user_message? string Tool user-facing status message.
---@field preview_output? smelt.transcript.ToolOutput Immutable pending output metadata for a promoted finished draft.
---@field output? smelt.transcript.ToolOutput Tool output metadata.
---@field event? string Process status event type, e.g. `"background_process_completed"`.
---@field event_type? string Alias for `event`.
---@field event_data? table Full typed process status event payload.
---@field process_id? string Background process id for process status events.
---@field exit_code? integer Background process exit code when known.
---@field command? string Exec command.
---@field command_spans? table Exec command as one styled span line, including the `!` accent.
---@field group_kind? string Registered semantic group name.
---@field bucket? string Stable planner bucket for a group.
---@field view_state? "collapsed"|"peek"|"expanded" Effective group or child view state.
---@field children? smelt.transcript.GroupChild[] Ordered bounded child presentation metadata for a group.
---@field child_ids? integer[] Ordered stable block ids for a group.
---@field child_count? integer Number of semantic children in a group.

--- Metadata for a retained payload whose complete content remains in Rust and is
--- available to renderers only through retained layout leaves.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.transcript.ContentMetadata
---@field content_id integer Stable shared-content id accepted by retained layout leaves.
---@field content_revision integer Monotonic content revision.
---@field content_bytes integer Current content size in bytes.
---@field content_lines integer Current logical line count.
---@field content_preview string Strictly bounded preview for labels, never the complete retained payload.

--- Renderer context. Width, theme, and scroll state are intentionally absent.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.transcript.Context
---@field view_state "collapsed"|"peek"|"expanded"|"trimmed_head"|"trimmed_tail" Effective view state for the node currently being rendered.
---@field renderer_generation integer Current renderer generation used for cache invalidation.
---@field surface string Rendering surface name, currently `"transcript"`.
---@field limits table Numeric product row budgets such as `tool_output_rows`.
---@field now_ms integer Unix epoch milliseconds shared by the complete top-level render pass.
---@field render fun(node: smelt.transcript.Block, overrides?: { view_state?: string }): smelt.layout.Node Re-enter the composed root renderer for a semantic child.

--- Visible transcript cursor position relative to the committed viewport.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.transcript.Cursor
---@field viewport_row integer Zero-based row inside the transcript viewport.

--- Semantic transcript group snapshot passed to default renderer helpers.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.transcript.Group
---@field id? integer Stable render-plan group id.
---@field name? string Group spec name.
---@field title? string Optional display title.
---@field view_state? string Current group view state.
---@field children? smelt.transcript.GroupChild[] Ordered bounded child presentation metadata.

--- Bounded semantic metadata for one retained group child. Growing content and
--- complete child payloads are never embedded in group renderer input.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.transcript.GroupChild
---@field id integer Stable child block id.
---@field kind string Semantic block kind.
---@field name? string Tool name.
---@field status? "pending"|"confirm"|"ok"|"err"|"denied" Tool status.
---@field summary_text? string Bounded plain-text summary.
---@field called_at_ms? integer Invocation start as Unix epoch milliseconds.
---@field args? table Bounded argument previews used by collapsed labels.
---@field output? { content_lines?: integer, is_error?: boolean } Bounded output metadata.
---@field event? string Process status event type.
---@field event_data? { process_id?: string, exit_code?: integer } Bounded process metadata.
---@field process_id? string Background process id.
---@field exit_code? integer Background process exit code.

--- Group selector declared through `smelt.transcript.groups.register`.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.transcript.GroupSelector
---@field kind? string Match block kind.
---@field name? string Match one tool name for tool blocks.
---@field names? string[] Match any listed tool name for tool blocks. Cannot be combined with `name`.
---@field terminal? boolean Match terminal/non-terminal blocks.
---@field event? string Match typed process status event type.
---@field event_type? string Alias for `event`.
---@field process_id? string Match typed background process id.
---@field exit_code? integer|string Match typed background process exit code.
---@field fields? table<string,string|integer> Exact block-field matches such as `{ event = "background_process_completed" }`.

--- Declarative transcript group registration. The host owns planning; the root
--- transcript renderer owns presentation for the resulting semantic group node.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.transcript.GroupSpec
---@field name string Unique group name. Registering the same name replaces it.
---@field cache_key? string Persisted layout cache key; omit to opt out while active.
---@field priority? integer Higher priority plans first. Defaults to 0.
---@field min? integer Minimum adjacent matching blocks required. Defaults to 2.
---@field default_view? "collapsed"|"peek"|"expanded" Initial presentation when the group first appears.
---@field selector smelt.transcript.GroupSelector Declarative block matcher.
---@field bucket? string|string[] Stable field names used to split adjacent matching runs.

--- Filters accepted by semantic previous/next block navigation.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.transcript.NavigationOpts
---@field role? smelt.transcript.Role Match only blocks with this semantic role. Defaults to `user`.

--- Viewport placement used when revealing a semantic transcript target.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.transcript.RevealOpts
---@field align? smelt.transcript.RevealAlign Target alignment within the transcript viewport. Currently only `top`.
---@field top_padding? integer Rows to reserve above the target. Defaults to zero.
---@field move_cursor? boolean Move the transcript cursor to the target. Defaults to true.

--- Transcript-shaped streaming renderer for plugin-owned buffers. Append model text deltas and it renders through the same incremental markdown block pipeline as the main transcript.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.transcript.Stream
---@field append fun(delta: string): nil Append one assistant text delta and re-render the target buffer.
---@field finish fun(final_text: string?): nil Finalize the streaming block. If `final_text` is provided and differs from the streamed text, the final text is rendered instead.
---@field reset fun(): nil Clear the stream and the target buffer.
---@field width fun(width: integer?): integer? Read or set the render width in terminal cells.

--- Rendering options for `smelt.transcript.stream`.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.transcript.StreamOpts
---@field width? integer Rendering width in terminal cells. Defaults to the target window's content width when the buffer is visible, then falls back to the current terminal width minus dialog gutters.

--- One span in a styled tool title. Style attributes may be supplied directly or through `style`.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.transcript.StyledSpan
---@field text? string Span text. The positional field `[1]` is also accepted.
---@field style? smelt.transcript.StyledSpanStyle Nested style attributes.
---@field syntax? string Syntax language used to highlight the span text.
---@field hl? string Theme highlight group.
---@field fg? string Foreground color.
---@field bg? string Background color.
---@field dim? boolean Whether to dim the text.
---@field bold? boolean Whether to render bold text.
---@field italic? boolean Whether to render italic text.
---@field selectable? boolean Whether copied transcript text includes this span.
---@field title_suffix? boolean Whether this span is transient pending-state title metadata.

--- Style attributes accepted on one styled title span.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.transcript.StyledSpanStyle
---@field hl? string Theme highlight group.
---@field fg? string Foreground color.
---@field bg? string Background color.
---@field dim? boolean Whether to dim the text.
---@field bold? boolean Whether to render bold text.
---@field italic? boolean Whether to render italic text.

--- Stable semantic transcript navigation target. Pass the target directly to `smelt.transcript.reveal`; internal sparse record coordinates are intentionally hidden.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.transcript.Target
---@field block_id integer Stable transcript block identity.
---@field role smelt.transcript.Role Semantic block role.
---@field first_line string First source line, suitable for navigation labels.

--- Options passed to focused tool body and draft callbacks.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.transcript.ToolBodyOptions
---@field gutter? string Prefix rendered before each body line.

--- Options accepted by the default tool header renderer.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.transcript.ToolHeaderOptions
---@field hl? string Status marker highlight group.

--- Bounded tool output metadata passed to transcript renderers.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.transcript.ToolOutput
---@field content_id integer Stable shared-content id accepted by `smelt.layout.content`.
---@field content_revision integer Monotonic content revision.
---@field content_bytes integer Current output size in bytes.
---@field content_lines integer Current logical line count.
---@field content_preview string Bounded text preview for labels and fallback UI, not complete output.
---@field is_error boolean True when the tool result is an error.
---@field metadata? table Bounded tool-specific structured metadata.
---@field content_fields? table<string, smelt.transcript.ContentMetadata> Named retained payloads referenced by opaque content IDs.

--- Public presentation policy for one tool name. A complete `render` callback
--- takes precedence; otherwise the default renderer composes the focused pieces.
--- Registrations are copied and immutable.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.transcript.ToolPresentation
---@field cache_key? string Stable persisted-layout key. Omit for dynamic presentation state.
---@field render? fun(tool: smelt.transcript.Block, ctx: smelt.transcript.Context, presentation: smelt.transcript.ToolPresentation): smelt.layout.Node Complete replacement renderer.
---@field title? fun(tool: smelt.transcript.Block, ctx: smelt.transcript.Context): string|smelt.transcript.StyledSpan[][]|nil Semantic title after the status marker. Return nil to use the tool summary.
---@field body? fun(tool: smelt.transcript.Block, ctx: smelt.transcript.Context, opts?: smelt.transcript.ToolBodyOptions): smelt.layout.Node|nil Expanded body renderer. Return nil to suppress the body.
---@field draft? fun(draft: smelt.transcript.Block, ctx: smelt.transcript.Context, opts?: smelt.transcript.ToolBodyOptions): smelt.layout.Node|nil Draft body renderer. Return nil to suppress the body.
---@field compact? fun(tool: smelt.transcript.Block, ctx: smelt.transcript.Context): string|smelt.layout.Node|nil Collapsed detail renderer. Return nil to suppress the detail.

--- Immutable committed transcript view delivered to `watch_view`. Navigation methods resolve from this exact semantic viewport anchor.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.transcript.View
---@field revision integer Monotonic revision of observable committed transcript state.
---@field window smelt.win.Win Transcript window handle for overlay anchoring.
---@field viewport smelt.transcript.Viewport Committed viewport geometry and tail state.
---@field focused boolean Whether the transcript currently owns the visible cursor.
---@field cursor? smelt.transcript.Cursor Visible transcript cursor position, or nil when the transcript does not own a visible cursor.
---@field previous_block fun(opts: smelt.transcript.NavigationOpts?): smelt.transcript.Target? Return the nearest actionable matching block when moving backward from this view. A matching block containing the viewport top is returned; one beginning exactly at the top is skipped.
---@field next_block fun(opts: smelt.transcript.NavigationOpts?): smelt.transcript.Target? Return the nearest actionable matching block when moving forward from this view.

--- Geometry and tail state from one committed transcript projection.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.transcript.Viewport
---@field width integer Outer transcript width in cells.
---@field height integer Transcript viewport height in rows.
---@field content_width integer Inner content width after gutters and scrollbar reservation.
---@field scrollable boolean Whether transcript content exceeds the viewport height.
---@field following_tail boolean Whether new content keeps the viewport pinned to the tail.
---@field at_top boolean Whether the committed viewport is at the transcript top.
---@field at_bottom boolean Whether the committed viewport is at the current transcript bottom.

--- Terminal size in cells.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.ui.Size
---@field width integer Terminal width in cells.
---@field height integer Terminal height in cells.

--- Shareable natural-size handle returned by `smelt.ui.layout.measure`.
--- Classification: Advanced - Documented low-level capability for plugins that need full control. It may evolve more freely than the Supported facade.
---@class smelt.ui.layout.Measure
---@field set fun(w: integer, h: integer): nil Update the measured natural size.
---@field get fun(): integer, integer Return the current measured width and height.

--- Handle returned by `Win:decorate(opts)` for a window-owned decoration.
--- Classification: Advanced - Documented low-level capability for plugins that need full control. It may evolve more freely than the Supported facade.
---@class smelt.win.Decoration
---@field close fun(): nil Remove the decoration and any window leaves it owns.

--- Options accepted by `Win:decorate(opts)`. The required `layout` is a `smelt.ui.layout` tree. `align` is one of `nw|n|ne|w|center|e|sw|s|se` and defaults to `center`. Width/height constraints use the same vocabulary as overlays but resolve against the owner window rect.
--- Classification: Advanced - Documented low-level capability for plugins that need full control. It may evolve more freely than the Supported facade.
---@class smelt.win.DecorationOpts
---@field layout smelt.ui.layout.Layout Decoration layout tree.
---@field align? string Owner-relative alignment point; default `center`.
---@field row_offset? integer Rows to offset after alignment.
---@field col_offset? integer Columns to offset after alignment.
---@field z? integer Owner-local stacking order.
---@field width? any Width constraint; defaults to `fit`.
---@field height? any Height constraint; defaults to `fit`.
---@field max_width? any Optional width cap.
---@field max_height? any Optional height cap.
---@field min_width? any Optional width floor.
---@field min_height? any Optional height floor.

--- Window-owned row background highlight. Ranges use absolute visual rows and an exclusive `end`; `{ cursor = true }` follows the window cursor row. `mode` is `always` (default) or `focused`; `width` is `full` (default) or `content`.
--- Classification: Advanced - Documented low-level capability for plugins that need full control. It may evolve more freely than the Supported facade.
---@class smelt.win.RowHighlight
---@field start? integer First absolute visual row to highlight (0-based). Required unless `cursor = true`.
---@field end? integer Exclusive absolute visual row end. Defaults to `start + 1`.
---@field cursor? boolean When true, highlight the current cursor row instead of a fixed range.
---@field hl_group? string Theme highlight group to resolve at render time. Default `CursorLine`.
---@field mode? "always"|"focused" Paint always or only while the window is focused. Default `always`.
---@field width? "full"|"content" Paint the full window row, including gutter and padding, or only the content region. Default `full`.

--- Window handle returned by `smelt.win.new(buf, opts?)`. Setter methods return the same handle for chaining.
--- Classification: Advanced - Documented low-level capability for plugins that need full control. It may evolve more freely than the Supported facade.
---@class smelt.win.Win
---@field close fun(): nil Close the overlay leaf. No-op if the window is already closed.
---@field focus fun(): nil Move keyboard focus to this window. No-op if the window is not focusable.
---@field buf fun(): smelt.buf.Buf? Return the backing Buf handle, or `nil` if the window is gone.
---@field rect fun(): any Return the window's current viewport rect as `{ row, col, width, height }`, or `nil` until the first render lays it out.
---@field content_width fun(): any Return the inner-content width in cells (gutter and pad_left/pad_right already subtracted), or `nil` until the first render lays it out. Use this instead of `rect().width` when fitting text into the window's actual content budget.
---@field decorate fun(opts: table): smelt.win.Decoration Attach a decoration to this window. Decorations are clipped to and painted with their owner pane, below later layout leaves and below global overlays.
---@field cursor fun(row: integer?): any Read or write the absolute cursor row (0-based). Without arg returns the row; with arg sets and returns the handle for chaining. The built-in prompt window ignores row-cursor writes; use `smelt.prompt.cursor(byte_offset)` for prompt text cursor control.
---@field move_cursor fun(delta: integer): smelt.win.Win Move the cursor by `delta` rows (clamped to the buffer's line count). Returns the handle for chaining. The built-in prompt window ignores row-cursor moves; use `smelt.prompt.cursor(byte_offset)` for prompt text cursor control.
---@field reveal fun(row: integer, opts: table?): smelt.win.Win Reveal row `row` (0-based) and return the handle for chaining. By default this also moves the row cursor there. `opts.top_padding` reserves rows above the target after the jump; `opts.bottom_padding` reserves rows below it; `opts.cursor = false` scrolls without moving the cursor. This is a generic row reveal for ordinary windows and explicit row debugging; transcript message navigation should resolve a target from a committed `smelt.transcript.View` and pass it to `smelt.transcript.reveal`. The built-in prompt window ignores row reveals; use `smelt.prompt.cursor(byte_offset)` for prompt text cursor control.
---@field key fun(chord: string, func: fun(value: table)): smelt.Reg Bind `func` to `chord` on this window. Returns a Reg handle whose `:remove()` undoes the binding. Raises on unknown chords.
---@field on fun(event: smelt.win.Event, func: fun(value: table)): smelt.Reg Subscribe `func` to `event` on this window. Returns a Reg handle whose `:remove()` undoes the subscription.
---@field placeholder fun(text: string, opts: table?): smelt.win.Win Set the window's placeholder - a dim suggestion rendered when the buffer is empty. Replaces any prior placeholder. `text` must be a single line (no `\n`); split before calling. `opts.accept_keys` (array of chord strings, default `{}`) accept the placeholder into the buffer and fire `placeholder_accepted`. `opts.dismiss_keys` (default `{ "esc", "c-c" }`) clear the placeholder and fire `placeholder_dismissed`. Typing does not destroy the placeholder; the stored text survives so an undo back to an empty buffer makes it visible again. The prompt renders placeholders as wrapped ghost text; other windows render a single virtual-text row. Returns the handle for chaining.
---@field clear_placeholder fun(): nil Clear the window's placeholder text and opts. Idempotent.
---@field placeholder_text fun(): string? Return the current placeholder text, or `nil` if none is set.
---@field row_highlights fun(specs: table?): smelt.win.Win Replace window-owned row background highlights and return the handle. Specs are `smelt.win.RowHighlight` tables. Pass nil or `{}` to clear. Use this for selection/cursor backgrounds that belong to a window view rather than buffer text.
---@field link_scroll fun(others: smelt.win.Win): smelt.win.Win Link `scroll_top` between this window and the variadic `others`. Closing any member auto-removes it. Returns the handle for chaining.
---@field scroll fun(arg: any): any Read or write the window's scroll state. No arg returns `{ top, follow, total, viewport, max, overflow, at_top, at_bottom, needs_tail_repin }` (`total` is the buffer's line count; `viewport` is the leaf's height; `max` is the largest valid `top`; `needs_tail_repin` means content overflows and the viewport is not already at bottom). An integer sets `scroll_top` and clears the pin-to-tail flag. The literal string `"tail"` jumps the viewport to the buffer's tail while keeping the cursor on the same screen row, then enables tail-follow.
---@field set_renderer fun(renderer: fun(value: smelt.win.Win)?): smelt.win.Win Register a retained renderer for this window, or clear it with nil. While the window is mounted, the renderer runs once after registration and again only after `invalidate_renderer`; its backing buffer remains authoritative between runs. An unmounted window stays dirty and runs when a layout mounts it.
---@field invalidate_renderer fun(): smelt.win.Win Mark this window's retained renderer dirty. It repaints during the next compositor frame in which the window is mounted. Returns the handle for chaining.

--- Where a virtual-text chunk is rendered relative to the line.
--- Classification: Advanced - Documented low-level capability for plugins that need full control. It may evolve more freely than the Supported facade.
---@alias smelt.buf.VirtTextPos "inline"|"overlay"|"right_align"|"eol"

--- Type of CLI flag declared via `smelt.cli.register_flag`. Matches the subset of clap that we expose to Lua.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@alias smelt.cli.FlagKind "boolean"|"string"|"integer"

--- Name of an event-shaped signal. Open alias - plugin-defined event names are accepted alongside the built-in events listed here.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@alias smelt.events.Name string|"block_done"|"cmd_post"|"cmd_pre"|"confirm_resolved"|"history"|"input_submit"|"session_ended"|"session_started"|"shutdown"|"stream_delta"|"stream_phase"|"tool_end"|"tool_start"|"turn_complete"|"turn_end"|"turn_error"|"turn_start"

--- Classification: Supported - Primary alpha facade for user config and plugins.
---@alias smelt.input.Event "change"|"submit"|"cancel"

--- Paint-leaf events accepted by `paint:on(event, fn)`.
--- Classification: Advanced - Documented low-level capability for plugins that need full control. It may evolve more freely than the Supported facade.
---@alias smelt.paint.Event "press"|"release"|"drag"

--- Decision accepted by effect-level permission rules.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@alias smelt.permissions.Decision "allow"|"ask"|"deny"

--- Name of a reactive signal. Open alias - plugin-defined signals declared via `smelt.signal.new` are accepted alongside the well-known runtime signals listed here.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@alias smelt.signal.Name string|"agent_mode"|"block_done"|"branch"|"cmd_post"|"cmd_pre"|"confirm_requested"|"confirm_resolved"|"confirms_pending"|"cursor_pos"|"cwd"|"cwd_branch"|"cwd_managed_worktree"|"cwd_project"|"cwd_worktree"|"cwd_worktree_path"|"errors"|"fast_mode"|"history"|"history_epoch"|"input_epoch"|"input_submit"|"keymap_pending"|"model"|"now"|"notification_visible"|"permission_pending"|"prompt_queue_revision"|"prompt_resize_active"|"prompt_resize_chrome"|"reasoning"|"running_procs"|"session_ended"|"session_epoch"|"session_started"|"session_slug"|"session_title"|"settings_terminal_title"|"shutdown"|"spinner_frame"|"stream_delta"|"stream_phase"|"task_label"|"tokens_used"|"tool_end"|"tool_start"|"tps"|"turn_complete"|"turn_end"|"turn_error"|"turn_start"|"viewport_pos"|"vim_mode"|"vim_pending_input"|"work_busy"|"work_elapsed_ms"|"work_label"|"work_outcome"|"work_retry_attempt"|"work_retry_remaining_ms"|"work_state"

--- Decision string accepted by `decide` callbacks and `permission_defaults`. Matches `protocol::Decision::{Allow, Ask, Deny}` - the engine's `Error(_)` variant is not exposed.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@alias smelt.tools.Decision "allow"|"ask"|"deny"

--- Coarse side-effect classification used by permission policy.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@alias smelt.tools.Effect "read"|"write"|"network"|"user"|"process"|"config"|"other"

--- Classification: Supported - Primary alpha facade for user config and plugins.
---@alias smelt.transcript.RevealAlign "top"

--- Classification: Supported - Primary alpha facade for user config and plugins.
---@alias smelt.transcript.Role "user"|"mode"|"process_status"|"assistant"|"thinking"|"tool"|"code"|"exec"|"compacted"|"compaction_preview"

--- Vim mode string literal.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@alias smelt.vim.Mode "insert"|"normal"|"visual"|"visual_line"

--- Window-event names accepted by `win:on(event, fn)`. Maps onto the internal `WinEvent` enum.
--- Classification: Advanced - Documented low-level capability for plugins that need full control. It may evolve more freely than the Supported facade.
---@alias smelt.win.Event "open"|"close"|"focus"|"blur"|"selection_changed"|"submit"|"text_changed"|"dismiss"|"tick"|"press"|"release"|"drag"|"scrolled"|"resized"|"placeholder_accepted"|"placeholder_dismissed"

