---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Agent-facing prompt customization for Lua plugins.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.agent
local agent = {}

--- Append concise guidance to the system prompt while this Lua runtime is active. Intended for plugins that register tools needing extra usage policy. Returns a `Reg` whose `:remove()` removes the fragment.
---@type fun(text: string): smelt.Reg
agent.add_system_prompt = nil

return agent
