---@meta

-- Auto-generated by `cargo run -p tui --bin gen-lua-docs`.
-- Do not edit by hand; update the `register_fn` call in Rust instead.

--- Nvim-shaped surface aliases for [`smelt.cell`](cell.md). `au.on(name, handler)` is `smelt.cell.subscribe`; `au.fire(name, payload)` is `smelt.cell.set`. Both share the same underlying registry — pick whichever name fits your plugin.
---@class smelt.au
local au = {}

--- Alias of `smelt.cell.set`.
---@see smelt.cell.set
---@type fun(name: smelt.cell.Name, payload: any): boolean
au.fire = nil

--- Alias of `smelt.cell.subscribe`.
---@see smelt.cell.subscribe
---@type fun(name: smelt.cell.Name, handler: fun(value: any)): integer?
au.on = nil

return au
