---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `register_fn` call in Rust instead.

--- Paint bash syntax highlighting into a Buffer. UiHost-only.
---@class smelt.bash
local bash = {}

--- Paint syntax-highlighted bash into the buffer, one source line per row with a single-space leading gutter. Used to render multi-line shell commands inside tool output.
---@type fun(buf_id: integer, command: string): nil
bash.render = nil

--- Paint one bash line into row 0 of the buffer with no leading gutter. Used by tool `render_summary` callbacks where the host supplies a scratch buffer per wrapped summary line.
---@type fun(buf_id: integer, line: string): nil
bash.render_line = nil

return bash
