---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `register_fn` call in Rust instead.

--- Buffer creation, line/source mutation, extmarks, and yank. UiHost-only — buffers are terminal-screen backing stores that windows render into.
---@class smelt.buf
local buf = {}

--- Drop every extmark owned by `ns` between `[line_start, line_end)` (1-based, inclusive start, exclusive end). Defaults clear the whole buffer so plugins that repaint a namespace each tick (perf panel, ghost text) don't have to track ids.
---@type fun(buf: integer, ns: integer, line_start: integer?, line_end: integer?): nil
buf.clear_namespace = nil

--- Create a new buffer and return its id. `opts.mode` selects a `BufFormat` parser; `opts.readonly` blocks edits via the public mutators. `opts.name` opts the buffer into hot-reload survival: re-calling `create` with the same name returns the existing buffer (its contents/extmarks/cursor are preserved) with `readonly`/`mode` re-applied. Anonymous buffers are reaped on `/reload`.
---@type fun(opts: table?): integer
buf.create = nil

--- Look up or allocate a stable namespace id for `name`. Repeated calls with the same name return the same id.
---@type fun(name: string): integer
buf.create_namespace = nil

--- Read a single line by 1-based index. Returns `nil` when out of range.
---@type fun(buf: integer, line: integer): string?
buf.get_line = nil

--- Look up the buffer id registered under `name` (i.e. previously created via `buf.create({ name = name })`). Returns `nil` when no such buffer is open. Used by plugins to recover their named buffer ids without re-calling `create`.
---@type fun(name: string): integer?
buf.named = nil

--- Place a highlight or virt-text extmark at `(row, col)` (row is 1-based). `opts` mirrors `nvim_buf_set_extmark`'s keyset; pass `opts.id` to retarget an existing mark. Returns the new extmark id.
---@type fun(buf: integer, ns: integer, row: integer, col: integer, opts: smelt.buf.ExtmarkOpts?): integer
buf.set_extmark = nil

--- Replace every line of the buffer with the strings in `lines`.
---@type fun(buf: integer, lines: string[]): nil
buf.set_lines = nil

--- Toggle a buffer's read-only flag. Read-only buffers reject `set_lines`/`set_source`.
---@type fun(buf: integer, ro: boolean): nil
buf.set_readonly = nil

--- Replace the buffer's full source text in one call. Cheaper than `set_lines` when you already have the joined string.
---@type fun(buf: integer, source: string): nil
buf.set_source = nil

--- Replace the buffer with a list of styled lines. Each line is a sequence of span tables: `{ text, style?, syntax? }`. `style = { hl?, dim?, bold?, italic?, fg?, bg? }` — `hl` is a theme group name; `fg`/`bg` are theme group names whose fg/bg axis is extracted (matches `set_extmark`). `syntax` runs the span text through the inline syntax highlighter (`"bash"`, `"rust"`, …) and overrides per-character fg; `style` modifiers still apply. An empty span list emits a blank line.
---@type fun(buf: integer, lines: table): nil
buf.set_styled_lines = nil

--- Return the buffer's full source as a string. `nil` if no buffer has that id.
---@type fun(buf: integer): string?
buf.text = nil

return buf
