---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Buffer handle constructor. `smelt.buf.new(opts?)` returns a `Buf` userdata. `opts.name` opts the buffer into hot-reload survival - repeat calls with the same name return the same handle with mutable opts re-applied. Anonymous buffers are reaped on `/reload`. UiHost-only - buffers are terminal-screen backing stores that windows render into.
---@class smelt.buf
local buf = {}

--- Create a buffer and return a `Buf` userdata. `opts.name` opts the buffer into hot-reload survival. Repeat calls with the same name return the same handle with mutable opts re-applied. When omitted from a module body, a stable per-(plugin, declaration-index) name is auto-assigned so the buffer survives `/reload` without explicit naming.
---@type fun(opts: smelt.buf.NewOpts?): smelt.buf.Buf
buf.new = nil

return buf
