---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `register_fn` call in Rust instead.

--- Opt out of bundled `smelt.<dotted>` modules. Call from `early.lua` to prevent the module from auto-loading; calls made later mark the module as disabled but its body has already run. For runtime removal of an already-loaded tool/command, use `smelt.tools.unregister` or `smelt.cmd.unregister` directly.
---@class smelt.builtins
local builtins = {}

--- Mark the bundled modules in `selector` as disabled. The auto-loader skips matching `require()` calls. Returns the count of names marked. Call from `early.lua` for full effect.
---@type fun(selector: smelt.builtins.Selector): integer
builtins.disable = nil

--- Undo a prior `disable` for the bundled modules in `selector`. Returns the count of names un-marked. Has no effect if the modules were never disabled.
---@type fun(selector: smelt.builtins.Selector): integer
builtins.enable = nil

--- Return `true` if the dotted module name (e.g. `"smelt.tools.web_search"`) is currently in the disabled set.
---@see smelt.tools.web_search
---@type fun(module: string): boolean
builtins.is_disabled = nil

--- Return the sorted dotted module names that are currently disabled.
---@type fun(): table
builtins.list = nil

return builtins
