---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Typed reactive cell registry. `smelt.cell(name)` returns a sticky `Cell` handle with `:get`, `:set`, `:subscribe`, `:name`. `smelt.cell.new` declares a cell with an initial value. `smelt.cell.glob` subscribes across every name matching a glob pattern.
---@class smelt.cell
local cell = {}

--- Register `handler(name, value)` for every cell whose name matches `pattern` (glob syntax). Returns a `Reg` whose `:remove()` drops the glob subscription.
---@type fun(pattern: string, handler: fun(arg1: string, arg2: any)): smelt.Reg
cell.glob = nil

--- Declare a cell named `name` with `initial` as its starting value. No-op if the cell already exists.
---@type fun(name: smelt.cell.Name, initial: any): nil
cell.new = nil

return cell
