---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `register_fn` call in Rust instead.

--- Read and write the system clipboard.
---@class smelt.clipboard
local clipboard = {}

--- Read the current clipboard contents as a string, or `nil` if empty/unavailable.
---@type fun(): string?
clipboard.read = nil

--- Write `text` to the system clipboard. Raises if the clipboard backend is unavailable.
---@type fun(text: string): nil
clipboard.write = nil

return clipboard
