---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `register_fn` call in Rust instead.

--- Register and list slash commands. `cmd.run` is injected by the TUI layer so it can access the live app state.
---@class smelt.cmd
local cmd = {}

--- Return every registered slash command as a Lua array of `{ name, desc, args, while_busy, queue_when_busy, startup_ok, hidden }` rows. Sorted by name.
---@type fun(): table
cmd.list = nil

--- Register a slash command `name` whose `handler` is invoked when the user runs it. `opts` accepts `desc`, `args`, `while_busy` (default `true`), `queue_when_busy` (default `false`), `startup_ok` (default `false`), and `hidden` (default `false`).
---@type fun(name: string, handler: fun(value: string?), opts: smelt.cmd.RegisterOpts?): nil
cmd.register = nil

--- Execute the slash-command line `line` (with or without leading `/`) as if the user had typed it. Errors are surfaced as in-app notifications.
---@type fun(line: string): nil
cmd.run = nil

--- Drop the slash command `name` from the registry. Returns `true` if a command was removed, `false` if no command with that name existed.
---@type fun(name: string): boolean
cmd.unregister = nil

return cmd
