---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Resolved application configuration introspection. All fields are read-only snapshots of the active config. UiHost-only.
---@class smelt.config
local config = {}

--- Active API base URL.
---@type fun(): string?
config.api_base = nil

--- Name of the environment variable that supplies the API key for the active provider.
---@type fun(): string?
config.api_key_env = nil

--- Configured context-window size in tokens for the active model, or `nil` when not declared.
---@type fun(): integer?
config.context_window = nil

--- Resolved model-level sampling, capability, and cost overrides as a table. Fields are `nil` when not explicitly set: `name`, `temperature`, `top_p`, `top_k`, `min_p`, `repeat_penalty`, `tool_calling`, `max_tokens`, `context_window`, `supports_reasoning`, `supports_fast_mode`, `input_modalities`, `thinking_budgets` (`{ low, medium, high, max }`), `input_cost`, `output_cost`, `cache_read_cost`, `cache_write_cost`.
---@type fun(): table?
config.model_config = nil

--- Active provider type string, e.g. `"openai"`, `"anthropic"`, `"openai-compatible"`.
---@type fun(): string?
config.provider_type = nil

--- Return sanitized runtime and reload diagnostics: committed Lua/runtime revisions, pending reload and last failure location, model selection, managed-provider freshness, and MCP/LSP/watcher/context controller convergence. No credential values or Lua source contents are included.
---@type fun(): table
config.runtime_status = nil

return config
