---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Confirm dialog primitives — preview dispatch, back-tab cycling, and choice resolution. UiHost-only.
---@class smelt.confirm
local confirm = {}

return confirm
