---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Confirm dialog primitives - preview dispatch, back-tab cycling, and choice resolution. UiHost-only.
---@class smelt.confirm
local confirm = {}

--- Visibility: Internal - Runtime implementation detail. Bundled Lua may call it, but user config and plugins should not depend on it.
--- Drive the bundled tool-permission confirm dialog for `handle_id`.
--- Reads the matching request out of the `confirm_requested` signal, builds
--- the header + preview + option leaves, dispatches the user's choice
--- through `smelt.confirm.__resolve`. Bails when no matching request is
--- active (e.g. a newer prompt has superseded it). Called by the host;
--- plugins should not invoke directly.
---@see smelt.confirm.__resolve
---@type fun(handle_id: string): nil
confirm.open = nil

return confirm
