---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Startup fallbacks for new sessions. `smelt.defaults.set({ model, mode, reasoning_effort })` sets each field; CLI flags and resumed-session state still win.
---@class smelt.defaults
local defaults = {}

--- Set startup defaults for fresh sessions. Accepts `{ model?, mode?, reasoning_effort? }`; CLI flags and resumed-session state still win.
---@type fun(cfg: smelt.defaults.Config): nil
defaults.set = nil

return defaults
