---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `register_fn` call in Rust instead.

--- Paint side-by-side diffs into a pair of Buffers. Inline diffs are returned declaratively via `smelt.layout.diff`. UiHost-only.
---@class smelt.diff
local diff = {}

--- Paint a side-by-side diff between `opts.old` and `opts.new` into two buffers — `left_buf_id` gets the pre-edit view, `right_buf_id` gets the post-edit view. Both buffers end up with the same row count: synthetic padding rows fill in wherever one side has fewer changes than the other, so vertical alignment between sides is exact. Pick the syntax via `opts.lang` (`"rust"`, `"py"`, …) or `opts.path` (extension-sniffed); `lang` wins when both are set.
---@type fun(left_buf_id: integer, right_buf_id: integer, opts: table): nil
diff.render_split = nil

return diff
