---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- LLM engine control — cancel, ask, submit commands, and request tool approval. UiHost-only.
---@class smelt.engine
local engine = {}

--- Run an out-of-band LLM request without touching the main turn. `spec.model` selects an alternate model (defaults to the primary), `spec.response_format` enforces a JSON schema, `spec.reasoning_effort` controls effort (defaults to `"off"`), `spec.trim_on_overflow` wraps the call in a trim-and-retry loop for context-window errors (`spec.max_trims` caps the number of drops, default 20). `spec.on_response` fires once with `(content, err)`; returns the request id.
---@type fun(spec: smelt.engine.AskSpec): integer
engine.ask = nil

--- Cancel the in-flight turn. In-flight background `smelt.engine.ask` requests are unaffected and will still fire their callbacks; plugins owning `smelt.spinner.busy` tokens are responsible for releasing them.
---@see smelt.engine.ask
---@see smelt.spinner.busy
---@type fun(): nil
engine.cancel = nil

--- Return `true` if an agent turn is currently in flight (a request is being streamed or a tool is executing).
---@type fun(): boolean
engine.is_running = nil

--- Re-evaluate every Lua surface: clears every command, keymap, statusline source, tool, hook, timer, and cell subscriber, wipes non-stdlib `package.loaded` entries, then re-runs the bundled autoload modules, `init.lua`, global plugins, and `.smelt/init.lua` + `.smelt/plugins/*`. `early.lua` is intentionally skipped — its CLI-flag and `smelt.builtins.disable` effects are startup-only.
---@see smelt.builtins.disable
---@type fun(): nil
engine.reload = nil

--- Start an agent turn from a Lua-defined custom command (`/name`). Notifies and no-ops if an agent is already running. See `smelt.engine.CommandOverrides` for the override shape.
---@see smelt.engine.CommandOverrides
---@type fun(name: string, body: string, overrides: smelt.engine.CommandOverrides?): nil
engine.submit_command = nil

return engine
