---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Occurrence-oriented subscriptions over event-shaped signals such as `turn_start`, `tool_start`, and `turn_complete`. Use `smelt.signal` when the current value matters; use `smelt.events.on` when only future occurrences matter.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.events
local events = {}

--- Publish `payload` for the event named `event`. Custom events are declared automatically on first emit.
---@type fun(event: smelt.events.Name, payload: any): nil
events.emit = nil

--- Declare an event named `event`. Existing signals are left unchanged. `smelt.events.on` and `smelt.events.emit` also declare custom events automatically, so this is only needed when a plugin wants to document its event surface explicitly.
---@see smelt.events.on
---@see smelt.events.emit
---@type fun(event: smelt.events.Name): nil
events.new = nil

--- Register `handler(payload)` for the event named `event`. Custom events are declared automatically before subscribing. Returns a `Reg` whose `:remove()` unsubscribes.
---@type fun(event: smelt.events.Name, handler: fun(value: any)): smelt.Reg
events.on = nil

return events
