---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Workspace file search. Owns background indexing, filesystem watching, and recent-selection ranking.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.files
local files = {}

--- Record a selected file result for recent-selection ranking. Options: `{ cwd? }`. Returns `(true, nil)` or `(false, err)`.
---@type fun(item: table, opts: table?): boolean, string?
files.accept = nil

--- Trigger an asynchronous full rescan for the current workspace or `opts.cwd`. Returns `(true, nil)` or `(false, err)`.
---@type fun(opts: table?): boolean, string?
files.rescan = nil

--- Search workspace files. Returns `{ items, total_matched, total_files, total_dirs, scanned, scanning, searching, ready, status, message, root }`. Items are `{ label, path, insert_text, kind, score }`. Options: `{ limit?, offset?, include_dirs?, cwd? }`.
---@type fun(query: string, opts: table?): table
files.search = nil

--- Return indexing status for the current workspace or `opts.cwd`: `{ root, initialized, files, scanned, scanning, watcher_ready, warmup_complete }`.
---@type fun(opts: table?): table
files.status = nil

return files
