---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Query which frontend is active (TUI vs headless).
---@class smelt.frontend
local frontend = {}

--- Return `true` when the frontend supports interactive prompts (a TTY user is present). Defaults to `true` when no host is installed.
---@type fun(): boolean
frontend.is_interactive = nil

--- Return the active frontend kind (e.g. `"tui"` or `"headless"`). Falls back to `"tui"` when no host is installed.
---@type fun(): string
frontend.kind = nil

return frontend
