---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Sync filesystem primitives. Errors use the `(value, err_string)` convention so callers can distinguish failures without pcall.
---@class smelt.fs
local fs = {}

--- Copy file `from` to `to`. Returns `(bytes_copied, nil)` on success or `(nil, err_string)` on failure.
---@type fun(from: string, to: string): integer?, string?
fs.copy = nil

--- Return `true` if a filesystem entry exists at `p`.
---@type fun(p: string): boolean
fs.exists = nil

--- Find paths matching `pattern` under `path` (defaults to cwd). Returns the matches sorted newest-first, capped at `opts.max` (default 200). On error returns `(nil, err_string)`.
---@type fun(pattern: string, path: string?, opts: table?): string[]?, string?
fs.glob = nil

--- Return `true` if `p` exists and refers to a directory.
---@type fun(p: string): boolean
fs.is_dir = nil

--- Return `true` if `p` exists and refers to a regular file.
---@type fun(p: string): boolean
fs.is_file = nil

--- Create directory `p` (parents must exist). Returns `(true, nil)` on success or `(false, err_string)` on failure.
---@type fun(p: string): boolean, string?
fs.mkdir = nil

--- Create directory `p` along with any missing parent directories. Returns `(true, nil)` on success or `(false, err_string)` on failure.
---@type fun(p: string): boolean, string?
fs.mkdir_all = nil

--- Read `p` into a string. Returns `(content, nil)` on success or `(nil, err_string)` on failure.
---@type fun(p: string): string?, string?
fs.read = nil

--- List the immediate entries of directory `p`. Returns `(entries, nil)` on success or `(nil, err_string)` on failure.
---@type fun(p: string): string[]?, string?
fs.read_dir = nil

--- Delete the empty directory at `p`. Returns `(true, nil)` on success or `(false, err_string)` on failure.
---@type fun(p: string): boolean, string?
fs.remove_dir = nil

--- Recursively delete the directory tree rooted at `p`. Returns `(true, nil)` on success or `(false, err_string)` on failure.
---@type fun(p: string): boolean, string?
fs.remove_dir_all = nil

--- Delete the file at `p`. Returns `(true, nil)` on success or `(false, err_string)` on failure.
---@type fun(p: string): boolean, string?
fs.remove_file = nil

--- Rename or move `from` to `to`. Returns `(true, nil)` on success or `(false, err_string)` on failure.
---@type fun(from: string, to: string): boolean, string?
fs.rename = nil

--- Return the size of file `p` in bytes. Returns `(size, nil)` or `(nil, err_string)` on failure.
---@type fun(p: string): integer?, string?
fs.size = nil

--- Write `contents` to file `p`, creating it if necessary. Returns `(true, nil)` on success or `(false, err_string)` on failure.
---@type fun(p: string, contents: string): boolean, string?
fs.write = nil

return fs
