---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Sync filesystem primitives. Errors use the `(value, err_string)` convention so callers can distinguish failures without pcall.
---@class smelt.fs
local fs = {}

--- Copy file `from` to `to`. Returns `(bytes_copied, nil)` on success or `(nil, err_string)` on failure.
---@type fun(from: string, to: string): integer?, string?
fs.copy = nil

--- Return `true` if a filesystem entry exists at `p`.
---@type fun(p: string): boolean
fs.exists = nil

--- Find paths matching `pattern` under `path` (defaults to cwd). Returns the matches sorted newest-first, capped at `opts.max` (default 200). On error returns `(nil, err_string)`.
---@type fun(pattern: string, path: string?, opts: table?): string[]?, string?
fs.glob = nil

--- Clear the cached workspace file list. The next `workspace_file_matches` call rebuilds it for the current cwd.
---@type fun(): nil
fs.invalidate_workspace_files = nil

--- Return `true` if `p` exists and refers to a directory.
---@type fun(p: string): boolean
fs.is_dir = nil

--- Return `true` if `p` exists and refers to a regular file.
---@type fun(p: string): boolean
fs.is_file = nil

--- Create directory `p` (parents must exist). Returns `(true, nil)` on success or `(false, err_string)` on failure.
---@type fun(p: string): boolean, string?
fs.mkdir = nil

--- Create directory `p` along with any missing parent directories. Returns `(true, nil)` on success or `(false, err_string)` on failure.
---@type fun(p: string): boolean, string?
fs.mkdir_all = nil

--- Read `p` into a string. Returns `(content, nil)` on success or `(nil, err_string)` on failure.
---@type fun(p: string): string?, string?
fs.read = nil

--- Read `path` off the main thread. Must be called from inside
--- `smelt.spawn(fn)` or a `tool.execute` (anything that runs on the Lua
--- task runtime). Returns `(content, nil)` on success or `(nil, err)` on
--- failure - same convention as `smelt.fs.read`.
---@see smelt.fs.read
---@type fun(path: string): string?, string?
fs.read_async = nil

--- List the immediate entries of directory `p`. Returns `(entries, nil)` on success or `(nil, err_string)` on failure.
---@type fun(p: string): string[]?, string?
fs.read_dir = nil

--- Read at most `max_bytes` bytes from `p`. Returns `({ content, truncated }, nil)` on success or `(nil, err_string)` on failure.
---@type fun(p: string, max_bytes: integer): table?, string?
fs.read_limited = nil

--- Delete the empty directory at `p`. Returns `(true, nil)` on success or `(false, err_string)` on failure.
---@type fun(p: string): boolean, string?
fs.remove_dir = nil

--- Recursively delete the directory tree rooted at `p`. Returns `(true, nil)` on success or `(false, err_string)` on failure.
---@type fun(p: string): boolean, string?
fs.remove_dir_all = nil

--- Delete the file at `p`. Returns `(true, nil)` on success or `(false, err_string)` on failure.
---@type fun(p: string): boolean, string?
fs.remove_file = nil

--- Rename or move `from` to `to`. Returns `(true, nil)` on success or `(false, err_string)` on failure.
---@type fun(from: string, to: string): boolean, string?
fs.rename = nil

--- Return the size of file `p` in bytes. Returns `(size, nil)` or `(nil, err_string)` on failure.
---@type fun(p: string): integer?, string?
fs.size = nil

--- Filesystem watcher. Calls `handler(event)` for each event, where
--- `event = { kind, detail?, paths }`. `kind` is one of `"create" | "modify" | "remove" | "rename" | "access" | "other" | "any"`;
--- `detail` carries notify's sub-kind when one is reported (e.g. `kind = "create"` → `detail = "file" | "folder"`).
--- `opts.recursive` defaults to true; set false to watch only the immediate
--- entries of a directory. Returns a `Reg` whose `:remove()` stops the
--- watcher and cancels the polling coroutine.
---@type fun(path: string, handler: fun(event: { kind: string, detail: string?, paths: string[] }), opts: table?): smelt.Reg
fs.watch = nil

--- Return bounded fuzzy-matched workspace file rows as `{ index, label }` tables. `index` is the 1-based index in the cached workspace file list.
---@type fun(query: string, limit: integer?): table
fs.workspace_file_matches = nil

--- Return tracked + untracked non-ignored files under the cwd, plus every intermediate parent directory, sorted lexicographically. Uses `git ls-files` when a git repo is present and falls back to a depth-capped filesystem walk otherwise. Suitable as the source for an `@file` completer.
---@type fun(): string[]
fs.workspace_files = nil

--- Write `contents` to file `p`, creating it if necessary. Returns `(true, nil)` on success or `(false, err_string)` on failure.
---@type fun(p: string, contents: string): boolean, string?
fs.write = nil

--- Write `contents` to `path` off the main thread. Same yielding rules as
--- `smelt.fs.read_async`. Returns `(true, nil)` on success or
--- `(false, err)` on failure - mirrors `smelt.fs.write`.
---@see smelt.fs.read_async
---@see smelt.fs.write
---@type fun(path: string, contents: string): boolean, string?
fs.write_async = nil

return fs
