---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `register_fn` call in Rust instead.

--- Cached file-state tracker used by tools to detect external modifications between reads and writes.
---@class smelt.fs.file_state
local fs_file_state = {}

--- Look up the cached file-state entry for `p`. Returns `{ content, mtime_ms, read_range }` or `nil` when no entry exists.
---@type fun(p: string): any
fs_file_state.get = nil

--- Return `true` if the file-state cache has a recorded entry for `p`.
---@type fun(p: string): boolean
fs_file_state.has = nil

--- Return the modification time of `p` in milliseconds since the UNIX epoch. Returns `(ms, nil)` or `(nil, err_string)` on failure.
---@type fun(p: string): integer?, string?
fs_file_state.mtime_ms = nil

--- Record that `p` was read at byte range `[offset, offset+limit)` with `content` so subsequent staleness checks know what the agent has seen.
---@type fun(p: string, content: string, offset: integer, limit: integer): nil
fs_file_state.record_read = nil

--- Record that `p` was written with `content` so subsequent staleness checks see the latest state.
---@type fun(p: string, content: string): nil
fs_file_state.record_write = nil

--- Return an error message describing why the cached state of `p` is stale relative to disk, or `nil` if it is up to date. `noun` (default `"file"`) labels the entity in the message.
---@type fun(p: string, noun: string?): string?
fs_file_state.staleness_error = nil

return fs_file_state
