---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `register_fn` call in Rust instead.

--- Ripgrep wrapper for searching files. Exit code 1 (no match) is not an error.
---@class smelt.grep
local grep = {}

--- Run ripgrep with `pattern` over `path`. `opts` accepts `mode` (`content`/`files_with_matches`/`count`), `case_insensitive`, `multiline`, `line_numbers`, `before_context`/`after_context`/`context`, `glob`, `type`, `timeout_secs`. Returns `(result_table, nil)` on success or `(nil, error_string)` on spawn failure. Exit code 1 (no match) is not an error — inspect `exit_code` on the result.
---@type fun(pattern: string, path: string, opts: table?): table?, string?
grep.run = nil

return grep
