---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Prompt history entries and search. UiHost-only.
---@class smelt.history
local history = {}

--- Return the prompt history as an array of strings, oldest first. Mirrors what the up-arrow recall in the input bar walks through.
---@type fun(): table
history.entries = nil

--- Rank prompt history against `query` using the history-specific scorer (word-match boost, recency bonus, dedupe). Returns `{ index, score }` rows where `index` is 1-based into `entries()`.
---@type fun(query: string): table
history.search = nil

return history
