---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `register_fn` call in Rust instead.

--- HTML parsing: title extraction, link scraping, to_text, to_markdown, DDG results.
---@class smelt.html
local html = {}

--- Extract all anchor `href` links from `source`. When `base` is supplied, relative URLs are resolved against it.
---@type fun(source: string, base: string?): string[]
html.links = nil

--- Parse a DuckDuckGo HTML results page into rows of `{ title, link, description }`.
---@type fun(source: string): table
html.parse_ddg_results = nil

--- Return the `<title>` text of `source`, or `nil` if no title element is present.
---@type fun(source: string): string?
html.title = nil

--- Convert `source` HTML to a `{ title, content, links }` table where `content` is markdown. Relative links resolve against `base` when supplied.
---@type fun(source: string, base: string?): table
html.to_markdown = nil

--- Strip HTML tags from `source` and return the visible text content.
---@type fun(source: string): string
html.to_text = nil

return html
