---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `register_fn` call in Rust instead.

--- Synchronous HTTP get/post with redirect following and header support. Errors use the `(value, err_string)` convention.
---@class smelt.http
local http = {}

--- Perform a synchronous HTTP GET against `url`. `opts` accepts `headers`, `timeout_secs`, and `max_redirects`. Returns `({ status, final_url, body, headers }, nil)` on success or `(nil, err_string)` on failure.
---@type fun(url: string, opts: table?): table?, string?
http.get = nil

--- Perform a synchronous HTTP POST against `url` with `body` bytes. `opts` accepts `headers`, `timeout_secs`, and `max_redirects`. Returns `({ status, final_url, body, headers }, nil)` on success or `(nil, err_string)` on failure.
---@type fun(url: string, body: string?, opts: table?): table?, string?
http.post = nil

--- Return a randomly selected User-Agent string from the built-in pool.
---@type fun(): string
http.random_user_agent = nil

return http
