---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `register_fn` call in Rust instead.

--- Process-wide HTTP response cache. Plugins can stash bodies under arbitrary keys to dedupe repeat fetches across a session.
---@class smelt.http.cache
local http_cache = {}

--- Look up a cached HTTP response by `key`. Returns the stored string or `nil` if no entry exists.
---@type fun(key: string): string?
http_cache.get = nil

--- Store `value` in the HTTP response cache under `key`.
---@type fun(key: string, value: string): nil
http_cache.put = nil

return http_cache
