---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Image file detection and base64 data-URL loading.
---@class smelt.image
local image = {}

--- Encode raw `bytes` as a base64 `data:` URL with the given `mime` type.
---@type fun(bytes: string, mime: string): string
image.data_url_from_bytes = nil

--- Return `true` if `p` looks like an image file (matched by extension/sniffing).
---@type fun(p: string): boolean
image.is_image_file = nil

--- Return a display label for an image path.
---@type fun(p: string): string
image.label_from_path = nil

--- Return the image MIME type inferred from `p`'s extension.
---@type fun(p: string): string
image.mime_from_path = nil

--- Read the image at `p` and encode it as a `data:` URL. Returns `(url, nil)` on success or `(nil, err_string)` on failure.
---@type fun(p: string): string?, string?
image.read_as_data_url = nil

--- Read and base64-encode an image off the main thread. Same return shape as
--- `smelt.image.read_as_data_url`.
---@see smelt.image.read_as_data_url
---@type fun(path: string): string?, string?
image.read_as_data_url_async = nil

return image
