---@meta

-- Auto-generated by `cargo run -p tui --bin gen-lua-docs`.
-- Do not edit by hand; update the `register_fn` call in Rust instead.

--- Root smelt namespace. Host-tier bindings are registered first; UiHost-tier bindings are injected when a TUI is active.
---@class smelt
local smelt = {}

--- Request a clean shutdown of the app. The quit fires on the next tick after the current handler returns.
---@type fun(): nil
smelt.quit = nil

--- Run `handler` as a fire-and-forget coroutine on the Lua task runtime. The handler may yield; its result is discarded.
---@type fun(handler: fun()): nil
smelt.spawn = nil

return smelt
