---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Root smelt namespace. Host-tier bindings are registered first; UiHost-tier bindings are injected when a TUI is active.
---@class smelt
local smelt = {}

--- Return which top-level pane currently has focus: `"transcript"` or `"prompt"`.
---@type fun(): string
smelt.focus = nil

--- Look up or allocate a stable namespace id for `name`. Namespaces scope `buf:mark` / `buf:clear_ns` calls so plugins can repaint their region without disturbing others.
---@type fun(name: string): integer
smelt.ns = nil

--- Promote the current loader frame to plugin scope `name` and return a
--- scope handle that bundles common per-plugin entry points so a plugin's
--- module body reads as a single object:
--- 
---   local M = smelt.plugin("banner")
---   M.state.fires = 0                       -- = smelt.state("banner")
---   M:cell("banner.open"):subscribe(fn)     -- = smelt.cell(name):subscribe
---   M:on("ready", fn)                       -- = smelt.lifecycle.on
---   M:on_ready(fn)                          -- = smelt.lifecycle.on_ready
---   M:on_shutdown(fn)                       -- = smelt.lifecycle.on_shutdown
---   M:cmd("banner.toggle", fn)              -- = smelt.cmd.register
---   M:keymap("n", "<C-g>", fn)              -- = smelt.keymap.set
--- 
--- After this call, `smelt.state()` resolves to the named slot and
--- unnamed resource constructors auto-name keyed by `name`. Idempotent
--- within a single module body run: counters reset on every promotion
--- so declaration order is what matters.
--- 
--- Must be called from a module body (or init.lua). Outside a loader
--- frame (e.g. from an event callback) it raises immediately.
---@see smelt.lifecycle.on
---@see smelt.lifecycle.on_ready
---@see smelt.lifecycle.on_shutdown
---@see smelt.cmd.register
---@see smelt.keymap.set
---@type fun(name: any): any
smelt.plugin = nil

--- Request a clean shutdown of the app. The quit fires on the next tick after the current handler returns.
---@type fun(): nil
smelt.quit = nil

--- Sleep for `ms` milliseconds. Must be called from inside `smelt.spawn(fn)`
--- or a `tool.execute`. Raises `cancelled` if the task is cancelled while
--- parked.
---@type fun(ms: integer): any
smelt.sleep = nil

--- Run `handler` as a coroutine on the Lua task runtime. The handler may yield; its result is discarded. Returns a `Reg` whose `:remove()` cancels the task — any in-flight `smelt.sleep` / `smelt.task.wait` raises `cancelled` and the coroutine unwinds.
---@see smelt.task.wait
---@type fun(handler: fun()): smelt.Reg
smelt.spawn = nil

return smelt
