---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Single-line input handle constructor. `smelt.input.new(opts)` returns an `Input` userdata that owns a buffer/window pair wired to shared line-input editing semantics.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.input
local input = {}

--- Create a single-line input and return an `Input` handle. Options: `text?`, `placeholder?`, plus window opts accepted by `smelt.win.new` (`region`, `name`, `pad_left`, `pad_right`, `wrap`, `scrollbar`, etc.).
---@see smelt.win.new
---@type fun(opts: table?): smelt.input.Input?
input.new = nil

return input
