---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Local session introspection web UI. `smelt.inspect.url()` reads the running server URL; the optional `inspect` plugin adds `smelt.inspect.start()`, `smelt.inspect.stop()`, and `smelt.inspect.open()`.
---@class smelt.inspect
local inspect = {}

--- Return the URL of the running inspector server, or nil if it is not running.
---@type fun(): any
inspect.url = nil

return inspect
