---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Encode/decode JSON for Lua plugins. Tables with contiguous 1..N integer keys encode as arrays; other tables encode as objects. Use `smelt.json.array()` when an empty table must encode as an array.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.json
local json = {}

--- Create an empty JSON array table. Unlike `{}`, it encodes as `[]` while empty.
---@type fun(): table
json.array = nil

--- Decode JSON into a Lua value. Returns `(value, nil)` on success or `(nil, err_string)` on failure.
---@type fun(text: string): any, string?
json.decode = nil

--- Encode a Lua value as JSON. Pass `{ pretty = true }` to format with indentation. Tables with contiguous 1..N integer keys encode as arrays; other tables encode as objects. Use `smelt.json.array()` for an empty array.
---@see smelt.json.array
---@type fun(value: any, opts: table?): string
json.encode = nil

return json
