---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Encode/decode JSON for Lua plugins. Tables with contiguous 1..N integer keys encode as arrays; other tables encode as objects.
---@class smelt.json
local json = {}

--- Decode JSON into a Lua value. Returns `(value, nil)` on success or `(nil, err_string)` on failure.
---@type fun(text: string): any, string?
json.decode = nil

--- Encode a Lua value as JSON. Pass `{ pretty = true }` to format with indentation. Tables with contiguous 1..N integer keys encode as arrays; other tables encode as objects.
---@type fun(value: any, opts: table?): string
json.encode = nil

return json
