---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `register_fn` call in Rust instead.

--- Register key bindings and query layered help sections. UiHost-only.
---@class smelt.keymap
local keymap = {}

--- Return layered keybinding help as `{ title, entries = { { label, detail } } }` rows. Filters vim-only chords when vim mode is disabled.
---@type fun(): table
keymap.help_sections = nil

--- Return the set of currently-bound `{ mode, chord }` rows. `mode` is the canonical short form (`"n"`/`"i"`/`"v"`/`""`).
---@type fun(): table
keymap.list = nil

--- Bind `chord` in `mode` to a Lua callback. `mode` is `"n"|"i"|"v"|""` (or the long form `normal`/`insert`/`visual`); the chord is canonicalized at registration and unknown values raise immediately. Re-binding the same `(mode, chord)` overwrites the prior handler.
---@type fun(mode: string, chord: string, handler: fun()): nil
keymap.set = nil

--- Drop the binding for `chord` in `mode`. `mode` accepts the same forms as `set`. Returns `true` if a binding was removed.
---@type fun(mode: string, chord: string): boolean
keymap.unset = nil

return keymap
