---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `register_fn` call in Rust instead.

--- Register key bindings and query layered help sections. UiHost-only.
---@class smelt.keymap
local keymap = {}

--- Return layered keybinding help as `{ title, entries = { { label, detail } } }` rows. Filters vim-only chords when vim mode is disabled.
---@type fun(): table
keymap.help_sections = nil

--- Bind `chord` in `mode` to a Lua callback. `mode` is `"n"|"i"|"v"|""` (or the long form `normal`/`insert`/`visual`); the chord is canonicalized at registration and unknown values raise immediately.
---@type fun(mode: string, chord: string, handler: fun()): nil
keymap.set = nil

return keymap
