---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Once-per-launch hooks keyed by event name. `on(event, fn)` is the general form; `on_ready` is a shorthand for the most common case (react to a CLI flag at startup). Each hook fires at most once per launch and is dropped from the registry on fire.
---@class smelt.lifecycle
local lifecycle = {}

--- Queue `fn` for the lifecycle event named `event`. Multiple hooks per event fire in registration order. Today only `"ready"` is emitted (after bootstrap + argv parse, before the main loop); more events may be added without breaking this API. Returns an `off()` that unregisters the hook before it fires; calling `off()` after the hook has already fired is a no-op returning `false`.
---@type fun(event: string, fn: function): fun(): boolean
lifecycle.on = nil

--- Shorthand for `lifecycle.on("ready", fn)`. The host calls `fn` once, after Lua bootstrap and CLI parsing finish and before the main loop starts. Use this to wire a CLI flag declared via `smelt.cli.register_flag` to a startup action — e.g. open a picker, load a session, dispatch a command. Returns an `off()` that unregisters the hook before `ready` fires.
---@see smelt.cli.register_flag
---@type fun(fn: function): fun(): boolean
lifecycle.on_ready = nil

return lifecycle
