---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Generic stdio Language Server Protocol client. Used by the optional LSP tool plugin.
--- Classification: Advanced - Documented low-level capability for plugins that need full control. It may evolve more freely than the Supported facade.
---@class smelt.lsp
local lsp = {}

--- Configure available language servers. `servers` maps names to `{ cmd, language_id, extensions, root_markers }`.
---@type fun(config: table): nil
lsp.configure = nil

return lsp
