---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `register_fn` call in Rust instead.

--- Paint markdown into a Buffer. UiHost-only.
---@class smelt.markdown
local markdown = {}

--- Render markdown `source` into the buffer using the same renderer the transcript uses for assistant text blocks (headings, lists, code fences, inline emphasis).
---@type fun(buf_id: integer, source: string): nil
markdown.render = nil

return markdown
