---@meta

-- Auto-generated by `cargo run -p tui --bin gen-lua-docs`.
-- Do not edit by hand; update the `register_fn` call in Rust instead.

--- Config-time MCP server registration. Unknown fields raise errors.
---@class smelt.mcp
local mcp = {}

--- Declare an MCP server named `name`. See `smelt.mcp.Config`.
---@see smelt.mcp.Config
---@type fun(name: string, cfg: smelt.mcp.Config): nil
mcp.register = nil

return mcp
