---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Config-time MCP server registration. Unknown fields raise errors.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.mcp
local mcp = {}

--- Snapshot every declared MCP server. Each row is `{ name, description, server_info, config, status, tool_count, tools }` where `description` is the configured human summary, `server_info` is `{ name, version, instructions }?`, `status` is `{ kind = "disabled"|"connecting"|"connected"|"error", since_ms?, error?, at_ms? }`, and `tools` contains `{ server, name, qualified_name, description, schema }` rows. Lifecycle reads are sync - safe to call from a status renderer or keymap.
---@type fun(): table
mcp.list = nil

--- Declare an MCP server named `name`. See `smelt.mcp.Config`. Returns a `Reg` whose `:remove()` drops the desired-state entry; the next `/reload` reconciles it away.
---@see smelt.mcp.Config
---@type fun(name: string, cfg: smelt.mcp.Config): smelt.Reg
mcp.register = nil

--- Return the lifecycle status for server `name`: `"disabled"`, `"connecting"`, `"connected"`, or `"error"`. Returns `nil` when no server with that name is declared.
---@type fun(name: string): string?
mcp.status = nil

--- Snapshot every discovered MCP tool. Each row is `{ server, name, qualified_name, description, schema }`. When `server` is provided, only that server's tools are returned; otherwise tools from every connected server.
---@type fun(server: string?): table
mcp.tools = nil

return mcp
