---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Persistent message log with full bodies and tracebacks.
---@class smelt.messages
local messages = {}

--- Append a new message of `kind` (`"error"`, `"warn"`/`"warning"`, anything else falls back to `"info"`) attributed to `source` with body `msg`.
---@type fun(kind: string, source: string, msg: string): nil
messages.append = nil

--- Drop every message from the log.
---@type fun(): nil
messages.clear = nil

--- Return the total number of messages currently in the log.
---@type fun(): integer
messages.count = nil

--- Return every persisted message as rows of `{ kind, source, summary, full, ts_ms }`, ordered oldest-first.
---@type fun(): table
messages.list = nil

--- Mark every message in the log as read so `unread_count` returns `0` until new errors arrive.
---@type fun(): nil
messages.mark_read = nil

--- Return the number of unread error messages in the log.
---@type fun(): integer
messages.unread_count = nil

return messages
