---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Metrics ledger access and live perf instrumentation. UiHost-only.
---@class smelt.metrics
local metrics = {}

--- Return raw entries from the on-disk metrics ledger. Lua commands aggregate and render these records into UI.
---@type fun(): table
metrics.entries = nil

return metrics
