---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Perf instrumentation toggle, clear, and snapshot. UiHost-only.
--- Classification: Advanced - Documented low-level capability for plugins that need full control. It may evolve more freely than the Supported facade.
---@class smelt.metrics.perf
local metrics_perf = {}

--- Clear all accumulated perf samples (durations and value gauges).
---@type fun(): nil
metrics_perf.clear = nil

--- Return whether perf instrumentation collection is enabled.
---@type fun(): boolean
metrics_perf.enabled = nil

--- Toggle perf instrumentation collection on/off. Disabled by default; enable to populate `snapshot` for the F12 debug panel.
---@type fun(on: boolean): nil
metrics_perf.set_enabled = nil

--- Return the current perf snapshot as `{ durations, values, enabled }` with per-label `count`, `last`, `p50`, `p95`, `p99`, `max`, `total` fields. Powers detailed diagnostics; prefer `snapshot_top` for live UI panels.
---@type fun(): table
metrics_perf.snapshot = nil

--- Return a cheap live perf snapshot with only the top `limit` duration rows and no value rows. Intended for panels that refresh frequently.
---@type fun(limit: integer?): table
metrics_perf.snapshot_top = nil

return metrics_perf
