---@meta

-- Auto-generated by `cargo run -p tui --bin gen-lua-docs`.
-- Do not edit by hand; update the `register_fn` call in Rust instead.

--- Agent mode read/cycle. `mode.set` and `mode.cycle` are injected by the TUI layer so they can access the live app state.
---@class smelt.mode
local mode = {}

--- Advance to the next agent mode in the configured cycle. No-op stub in core; the TUI overrides this binding.
---@type fun(): nil
mode.cycle = nil

--- Return the configured agent-mode cycle; falls back to all known modes when the user has not customized one.
---@type fun(): smelt.mode.Mode[]
mode.cycle_list = nil

--- Return the active agent mode (e.g. `"normal"`, `"plan"`, `"apply"`, `"yolo"`).
---@type fun(): smelt.mode.Mode
mode.get = nil

--- Switch the agent mode. Raises a Lua error on unknown values.
---@type fun(mode: smelt.mode.Mode): nil
mode.set = nil

return mode
