---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Agent-mode selector. `smelt.mode.current()` reads the active mode, `smelt.mode.set(v)` sets it in a TUI session, and `smelt.mode.cycle_list()` lists the configured cycle.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.mode
local mode = {}

--- Return the active agent mode name.
---@type fun(): string
mode.current = nil

--- Tier: UiHost - Requires a terminal UI; calling these from headless mode raises.
--- Advance the active agent mode to the next entry in `smelt.mode.cycle_list()`,
--- wrapping at the end. No-op when the cycle is empty.
---@see smelt.mode.cycle_list
---@type fun(): nil
mode.cycle = nil

--- Return the configured agent-mode cycle; falls back to the built-in default when the user has not customized one.
---@type fun(): string[]
mode.cycle_list = nil

--- Return a copy of the registered mode definition for `name`, or `nil` when unknown.
---@type fun(name: string): smelt.mode.Mode?
mode.get = nil

--- Return copies of registered mode definitions in registration order.
---@type fun(): smelt.mode.Mode[]
mode.list = nil

--- Register an agent mode from `{ name, label?, icon?, hl_group?, note?,
--- permissions?, after? }`. Registering a new name appends it, or inserts it
--- after an existing `after` name. Registering an existing name replaces its
--- definition without changing its position. Raises when `name` is missing.
---@type fun(spec: table): nil
mode.register = nil

--- Tier: UiHost - Requires a terminal UI; calling these from headless mode raises.
--- Set the active agent mode. The change is applied immediately to the UI and persisted according to the active remember policy.
---@type fun(mode: string): nil
mode.set = nil

return mode
