---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Model selector. `smelt.model.current()` reads the active model key, `smelt.model.set(v)` switches, and `smelt.model.list()` returns the available models.
---@class smelt.model
local model = {}

--- Resolved capabilities for the active model/provider as `{ input_modalities, supports_image, supports_pdf, supports_video, supports_reasoning, tool_calling, max_tokens, context_window, transport = { ... }, sources = { ... } }`.
---@type fun(): table?
model.capabilities = nil

--- Return the active model key, or `nil` when no active model exists.
---@type fun(): string?
model.current = nil

--- Resolved input modalities for the active model as an array such as `{ "text", "image", "pdf" }`. Config/provider metadata wins, models.dev fills missing data, and unknown models default to text only.
---@type fun(): table?
model.input_modalities = nil

--- Return an array of `{ key, name, display_name?, provider, api_base, provider_type }` records for every model the active config can switch to.
---@type fun(): table
model.list = nil

--- Resolved maximum output tokens for the active model. Returns the config override if set, otherwise falls back to the models.dev catalog value, then to the provider default. Returns `nil` when no limit is known.
---@type fun(): integer?
model.max_tokens = nil

---@type fun(name: any, value: any): any
model.preferred = nil

--- Resolved pricing for the active model as `{ input, output, cache_read, cache_write, source }`. `source` is one of `"config override"`, `"models.dev"`, or `"none"`. Prices are USD per 1M tokens.
---@type fun(): table?
model.pricing = nil

--- Switch the active model by key. Errors when the name cannot be resolved.
---@type fun(name: string): nil
model.set = nil

--- Return `{ current, requested, availability, reason?, providers }` for model selection. `availability` is `available`, `stale_catalog`, `unavailable`, `pending`, or `none`; unavailable reasons are stable snake-case strings. Each managed provider reports sanitized `authenticated`, `status`, `error`, `request_id`, `auth_revision`, and `desired_revision` fields.
---@type fun(): table
model.status = nil

--- Return whether the active model supports the named input modality, for example `image` or `pdf`.
---@type fun(modality: string): boolean?
model.supports_input = nil

--- Return `{ provider_type, api_base, api_key_env, multimodal_tool_results }` for the active model transport. `api_key_env` is the environment variable name, never its value.
---@type fun(): table?
model.transport = nil

return model
