---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Model selector. `smelt.model()` reads the active model key, `smelt.model(v)` switches, `smelt.model.list()` returns the available models.
---@class smelt.model
local model = {}

--- Return an array of `{ key, name, provider }` records for every model the active config can switch to.
---@type fun(): table
model.list = nil

---@type fun(name: any, value: any): any
model.preferred = nil

return model
