---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Model selector. `smelt.model.current()` reads the active model key, `smelt.model.set(v)` switches, and `smelt.model.list()` returns the available models.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.model
local model = {}

--- Resolved capabilities for the active model/provider as `{ input_modalities, supports_image, supports_pdf, supports_video, supports_reasoning, tool_calling, max_tokens, context_window, transport = { ... }, sources = { ... } }`.
---@type fun(): table?
model.capabilities = nil

--- Return the active model key, or `nil` when no active model exists.
---@type fun(): string?
model.current = nil

--- Tier: Host - Available in every runtime, including headless mode.
--- Return picker-visible `{ key, name, display_name?, provider, api_base, provider_type }` records. Hidden catalog models remain selectable by explicit key.
---@type fun(): table
model.list = nil

--- Tier: Host - Available in every runtime, including headless mode.
--- Read or update a named model preference. With only `name`, returns the
--- stored model key or `nil`. Passing a second argument stores that model key;
--- passing `nil` explicitly clears it. Preferences survive Lua reloads through
--- `smelt.state.persistent("model_preferred")`.
---@type fun(name: string, ...: string?): string?
model.preferred = nil

--- Resolved pricing for the active model as `{ input, output, cache_read, cache_write, source }`. `source` is one of `"config override"`, `"models.dev"`, or `"none"`. Prices are USD per 1M tokens.
---@type fun(): table?
model.pricing = nil

--- Switch the active model by key. Errors when the name cannot be resolved.
---@type fun(name: string): nil
model.set = nil

--- Return `{ current, requested, availability, reason?, providers }` for model selection. `availability` is `available`, `stale_catalog`, `unavailable`, `pending`, or `none`; unavailable reasons are stable snake-case strings. Each managed provider reports sanitized `authenticated`, `status`, `error`, `request_id`, `auth_revision`, and `desired_revision` fields.
---@type fun(): table
model.status = nil

--- Return whether the active model supports the named input modality, for example `image` or `pdf`.
---@type fun(modality: string): boolean?
model.supports_input = nil

return model
