---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Parse, read, and apply notebook cell edits, plus compute preview data for the edit_notebook tool. UiHost-only.
---@class smelt.notebook
local notebook = {}

--- Apply a notebook edit (cell insert/replace/delete) described by `args` and persist the new file. Returns `(message_table, nil)` on success or `(nil, err_msg)` on failure. Callers are expected to hold the per-path advisory flock.
---@type fun(args: table): any?, string?
notebook.apply_edit = nil

--- Return `true` if `path` looks like a Jupyter notebook (`.ipynb` extension).
---@type fun(path: string): boolean
notebook.is_notebook_path = nil

--- Parse a notebook JSON string. Returns `(notebook, nil)` with `{ nbformat, nbformat_minor, cells = { { kind, id?, source, execution_count? } } }` on success, or `(nil, error)` on failure.
---@type fun(json: string): table?, string?
notebook.parse = nil

--- Compute the preview payload for an `edit_notebook` call. Returns `nil` when the notebook can't be read/parsed or the target cell is out of range. The returned table has `{ edit_mode, path, title, old_source, new_source, syntax_ext }`.
---@type fun(args: table): table?
notebook.preview_data = nil

--- Render a Jupyter notebook at `path` as cell-by-cell text starting at `offset` for at most `limit` cells. Returns `(text, nil)` on success or `(nil, err_msg)` on parse failure — same output the built-in `read_file` tool produces.
---@type fun(path: string, offset: integer, limit: integer): string?, string?
notebook.read = nil

return notebook
