---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Status-area toasts. Each call appends the body to `smelt.messages` and surfaces a one-line summary in the toast row above the prompt. The optional `source` arg tags the entry in `/messages` (defaults to `"lua"`). UiHost-only.
---@class smelt.notify
local notify = {}

--- Show an error toast (highlighted with the error color) and append the body to the message log. Pass `source` to tag the `/messages` entry (e.g. `"upgrade"`); defaults to `"lua"`.
---@type fun(msg: string, source: string?): nil
notify.error = nil

--- Bind `source` once and return a callable bag that forwards to
--- `smelt.notify` / `smelt.notify.error` / `smelt.notify.warn` with the
--- source pinned. A plugin opts in with one line at the top of the file:
---   local notify = smelt.notify.scoped("upgrade")
---   notify("downloading …")
---   notify.error("/upgrade: spawn failed")
--- so the per-call-site `, "upgrade"` repetition goes away. Same toast +
--- `/messages` semantics as the underlying calls. Skipped on headless
--- where `smelt.notify` isn't bound.
---@see smelt.notify.error
---@see smelt.notify.warn
---@type fun(source: string): table
notify.scoped = nil

--- Show a warning toast and append the body to the message log. Pass `source` to tag the `/messages` entry; defaults to `"lua"`.
---@type fun(msg: string, source: string?): nil
notify.warn = nil

return notify
