---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `register_fn` call in Rust instead.

--- Status-area notifications. Call `smelt.notify("msg")` for an info toast or `smelt.notify.error("msg")` for an error toast. UiHost-only.
---@class smelt.notify
local notify = {}

--- Show an error notification in the status area (highlighted with the error color).
---@type fun(msg: string): nil
notify.error = nil

return notify
