---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Environment and system primitives: getenv, setenv, platform, cwd, pid, etc.
---@class smelt.os
local os = {}

--- Return the target CPU architecture as reported by `std::env::consts::ARCH` (e.g. `"x86_64"`, `"aarch64"`).
---@type fun(): string
os.arch = nil

--- Return the current working directory as `(path, nil)`, or `(nil, err_string)` on failure.
---@type fun(): string?, string?
os.cwd = nil

--- Return the filesystem path to the running smelt binary as `(path, nil)` on success, or `(nil, err_string)` on failure. Useful for plugins that re-exec the binary or report install location.
---@type fun(): string?, string?
os.exe_path = nil

--- Return the value of the environment variable `name`, or `nil` if it is not set.
---@type fun(name: string): string?
os.getenv = nil

--- Return the user's home directory, or `nil` if it cannot be determined.
---@type fun(): string?
os.home = nil

--- Open `url` in the system's default browser. macOS uses `open`, Windows uses `cmd /c start`, everything else tries `xdg-open` then falls back to `open`. Only `http(s)://`, `mailto:`, and `file://` URLs are accepted. Returns `(true, nil)` on a successful spawn, or `(false, err_string)` if the scheme is rejected or every launcher errored.
---@type fun(url: string): boolean, string?
os.open_url = nil

--- Return the OS process id of the running smelt instance.
---@type fun(): integer
os.pid = nil

--- Return the target operating system as reported by `std::env::consts::OS` (e.g. `"macos"`, `"linux"`).
---@type fun(): string
os.platform = nil

--- Change the process working directory to `p`. Returns `(true, nil)` on success or `(false, err_string)` on failure.
---@type fun(p: string): boolean, string?
os.set_cwd = nil

--- Set the process environment variable `name` to `value`. Mutates the live process env; visible to subsequent `getenv` calls and child processes.
---@type fun(name: string, value: string): nil
os.setenv = nil

--- Return the platform temporary directory path.
---@type fun(): string
os.tempdir = nil

--- Remove the environment variable `name` from the process environment.
---@type fun(name: string): nil
os.unsetenv = nil

return os
