---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `register_fn` call in Rust instead.

--- Overlay handle constructor. `smelt.overlay.new(opts)` opens an overlay from `opts.layout` (a `smelt.overlay.layout` userdata) and returns an `Overlay` userdata. `opts.name` opts the overlay into hot-reload survival. UiHost-only.
---@class smelt.overlay
local overlay = {}

--- Open an overlay rendered from `opts.layout` (a `smelt.overlay.layout` userdata) and return an `Overlay` userdata. `opts.name` opts the overlay into hot-reload survival.
---@see smelt.overlay.layout
---@type fun(opts: table): smelt.overlay.Overlay
overlay.new = nil

return overlay
