---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Pure parsers: frontmatter extraction from markdown documents.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.parse
local parse = {}

--- Split `---`-delimited YAML frontmatter from a markdown document. Returns `(frontmatter_table, body)` or `(nil, content)` when no frontmatter is present.
---@type fun(content: string): any, string
parse.frontmatter = nil

--- Parse a JSON document into a Lua value. Returns the decoded value on success, `nil` on parse error. Objects become tables, arrays become 1-indexed tables, numbers become integers when they fit losslessly.
---@type fun(content: string): any
parse.json = nil

return parse
