---@meta

-- Auto-generated by `cargo run -p tui --bin gen-lua-docs`.
-- Do not edit by hand; update the `register_fn` call in Rust instead.

--- Pure parsers: frontmatter extraction from markdown documents.
---@class smelt.parse
local parse = {}

--- Split `---`-delimited YAML frontmatter from a markdown document. Returns `(frontmatter_table, body)` or `(nil, content)` when no frontmatter is present.
---@type fun(content: string): any, string
parse.frontmatter = nil

return parse
