---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Pure path arithmetic: normalize, join, relative, expand, display, etc.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.path
local path = {}

--- Return the final component (file name) of `p`, or `nil` if `p` ends in `..`.
---@type fun(p: string): string?
path.basename = nil

--- Resolve `p` to its canonical absolute form (following symlinks). Returns `(path, nil)` on success or `(nil, err_string)` on failure.
---@type fun(p: string): string?, string?
path.canonical = nil

--- Return the absolute path to the slash-commands directory under the runtime config root.
---@type fun(): string
path.commands_dir = nil

--- Return the absolute path to smelt's runtime config directory.
---@type fun(): string
path.config_dir = nil

--- Return a user-friendly rendering of `p` for UI display (e.g. with the home dir abbreviated to `~`).
---@type fun(p: string): string
path.display = nil

--- Return a user-friendly rendering of a possibly partial path for streaming tool summaries. Absolute paths that may still collapse to the current working directory or home directory return an empty string until enough path has arrived.
---@type fun(p: string): string
path.display_streaming = nil

--- Expand config-path syntax in `p`: leading `~`, `$VAR`, and `${VAR}`. Does not invoke a shell, expand globs, or canonicalize symlinks.
---@type fun(p: string): string
path.expand = nil

--- Return the file extension of `p` (without the leading dot), or `nil` if there is none.
---@type fun(p: string): string?
path.extension = nil

--- Return `true` if `p` is an absolute path on the current platform.
---@type fun(p: string): boolean
path.is_absolute = nil

--- Join the variadic `parts` into a single path using the platform separator.
---@type fun(...: string): string
path.join = nil

--- Normalize `p` by collapsing redundant `.`, `..`, and separator components without touching the filesystem.
---@type fun(p: string): string
path.normalize = nil

--- Return the parent directory of `p`, or `nil` if `p` has no parent component.
---@type fun(p: string): string?
path.parent = nil

--- Return the path of `target` expressed relative to `base`.
---@type fun(base: string, target: string): string
path.relative = nil

--- Resolve runtime path `p` to a normalized absolute path. Expands a leading `~` using the runtime home and resolves relative paths from the runtime cwd without touching the filesystem or expanding environment variables.
---@type fun(p: string): string
path.resolve = nil

return path
