---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Pure path arithmetic: normalize, join, relative, expand, display, etc.
---@class smelt.path
local path = {}

--- Return the final component (file name) of `p`, or `nil` if `p` ends in `..`.
---@type fun(p: string): string?
path.basename = nil

--- Resolve `p` to its canonical absolute form (following symlinks). Returns `(path, nil)` on success or `(nil, err_string)` on failure.
---@type fun(p: string): string?, string?
path.canonical = nil

--- Return the absolute path to the slash-commands directory under the user config root.
---@type fun(): string
path.commands_dir = nil

--- Return the absolute path to smelt's user config directory.
---@type fun(): string
path.config_dir = nil

--- Return a user-friendly rendering of `p` for UI display (e.g. with the home dir abbreviated to `~`).
---@type fun(p: string): string
path.display = nil

--- Expand config-path syntax in `p`: leading `~`, `$VAR`, and `${VAR}`. Does not invoke a shell, expand globs, or canonicalize symlinks.
---@type fun(p: string): string
path.expand = nil

--- Return the file extension of `p` (without the leading dot), or `nil` if there is none.
---@type fun(p: string): string?
path.extension = nil

--- Return `true` if `p` is an absolute path on the current platform.
---@type fun(p: string): boolean
path.is_absolute = nil

--- Join the variadic `parts` into a single path using the platform separator.
---@type fun(...: string): string
path.join = nil

--- Normalize `p` by collapsing redundant `.`, `..`, and separator components without touching the filesystem.
---@type fun(p: string): string
path.normalize = nil

--- Return the parent directory of `p`, or `nil` if `p` has no parent component.
---@type fun(p: string): string?
path.parent = nil

--- Return the path of `target` expressed relative to `base`.
---@type fun(base: string, target: string): string
path.relative = nil

return path
