---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- List session/workspace rules and sync a Lua-built ruleset back through the App. UiHost-only.
---@class smelt.permissions
local permissions = {}

--- Decide a subcommand bucket (e.g. `("normal", "shell", "git status")`) against the current ruleset. Returns `"allow"`, `"ask"`, or `"deny"`; defaults to `"ask"` when no app context is available.
---@type fun(mode_str: string, bucket: string, value: string): string
permissions.check = nil

--- Decision primitives for tool `decide` callbacks. Returns "allow"/"ask"/"deny".
---@type fun(mode_str: string, name: string): string
permissions.check_tool = nil

--- Add one session-scoped grant. Currently supports `{ kind = "path", mode, tool, access = "read"|"write", path_prefix }` for mode/tool-specific path access.
---@type fun(grant: smelt.permissions.SessionPathGrant): nil
permissions.grant_session = nil

--- Return current permission rules as `{ session = { { tool, pattern } }, path_grants = { { kind = "path", mode, tool, access, path_prefix } }, workspace = { { tool, patterns } } }`. Session entries and path grants come from runtime approvals; workspace entries come from the on-disk store rooted at the current cwd.
---@type fun(): smelt.permissions.ListResult
permissions.list = nil

--- Install the per-mode permission ruleset. See `smelt.permissions.RulesSpec`.
---@see smelt.permissions.RulesSpec
---@type fun(spec: smelt.permissions.RulesSpec): nil
permissions.set_rules = nil

--- Replace runtime + workspace permission entries with `spec.session`, `spec.path_grants`, and `spec.workspace`. Persists workspace rules to disk; session rules apply for this run only.
---@type fun(spec: smelt.permissions.SyncSpec): nil
permissions.sync = nil

return permissions
