---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `register_fn` call in Rust instead.

--- The main editable input surface: win handle, text get/set, and cursor control. UiHost-only.
---@class smelt.prompt
local prompt = {}

--- Remove the named prompt section. No-op if the section does not exist.
---@type fun(name: string): nil
prompt.remove_section = nil

--- Set the named prompt section (e.g. selection context, attached files) to `content`. Sections render above the editable text and are submitted with the next turn.
---@type fun(name: string, content: string): nil
prompt.set_section = nil

--- Replace the prompt buffer with `text`. The cursor lands at the end and undo state is reset.
---@type fun(text: string): nil
prompt.set_text = nil

--- Return the prompt input buffer's current text.
---@type fun(): string
prompt.text = nil

--- Return a `Win` handle for the prompt input. Use `win:key(...)` and `win:on(...)` to attach plugin behaviour.
---@type fun(): smelt.win.Win
prompt.win = nil

return prompt
