---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `register_fn` call in Rust instead.

--- List built-in model providers and register custom ones. Headless-safe.
---@class smelt.provider
local provider = {}

--- Return every registered provider as an array of tables. Each entry has `name`, `type`, `api_base`, `api_key_env`, and a `models` array.
---@type fun(): table
provider.list = nil

--- Register provider middleware. `mw` is a table of `{ on_request = fn?, on_response = fn? }`:
--- 
--- - `on_request(messages)` — runs just before the engine calls the provider. `messages` is the full conversation history (an array of `{ role, content, tool_calls? }` rows including the system prompt at index 1). Return a replacement array to mutate it; any other return value leaves the history untouched.
--- - `on_response(message)` — runs after the assistant message is fully assembled but before it's appended to history. `message` is the same `{ role = "assistant", content?, tool_calls? }` shape used everywhere else. Return a replacement table to mutate it; any other return leaves it as-is.
--- 
--- Hooks fire in registration order. Each hook sees the previous hook's replacement. Returns an `off()` function that removes this middleware.
--- 
--- For streaming observation use `smelt.cell.subscribe("stream_delta", ...)` — synchronous mutation of mid-stream tokens isn't safe because the parser owns the partial state.
---@type fun(mw: table): function
provider.middleware = nil

--- Declare a provider named `name`. Re-registering replaces the previous entry of the same name.
---@type fun(name: string, cfg: smelt.provider.Config): nil
provider.register = nil

return provider
