---@meta

-- Auto-generated by `cargo run -p tui --bin gen-lua-docs`.
-- Do not edit by hand; update the `register_fn` call in Rust instead.

--- List built-in model providers and register custom ones. Headless-safe.
---@class smelt.provider
local provider = {}

--- Return every registered provider as an array of tables. Each entry has `name`, `type`, `api_base`, `api_key_env`, and a `models` array.
---@type fun(): table
provider.list = nil

--- Declare a provider named `name`. Re-registering replaces the previous entry of the same name.
---@type fun(name: string, cfg: smelt.provider.Config): nil
provider.register = nil

return provider
