---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- List built-in model providers and register custom ones. Headless-safe.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.provider
local provider = {}

--- Classification: Advanced - Documented low-level capability for plugins that need full control. It may evolve more freely than the Supported facade.
--- Advanced UI helper: 1-based row position for a stable item key.
---@type fun(rows: any, key: any): any
provider._position_of_key = nil

--- Classification: Advanced - Documented low-level capability for plugins that need full control. It may evolve more freely than the Supported facade.
--- Advanced UI helper: select the fallback row unless stable-key preservation succeeds.
---@type fun(rows: any, old_key: any, preserve: any, fallback: any): any
provider._select_row = nil

--- Classification: Advanced - Documented low-level capability for plugins that need full control. It may evolve more freely than the Supported facade.
--- Advanced UI helper: keep stale rows visible while a provider is loading an
--- empty/synthetic refresh, instead of flashing to a status row.
---@type fun(result: any, rows: any, current_rows: any): any
provider._should_keep_stale_rows = nil

--- Return true when the row list contains at least one non-synthetic row.
---@type fun(rows: table[]?): boolean
provider.has_real_rows = nil

--- Return true when a provider or normalized result is still loading.
---@type fun(result: table?): boolean
provider.is_loading = nil

--- Return the stable identity key used to preserve selection across provider refreshes.
---@type fun(item: table?): string?
provider.item_key = nil

--- Return every registered provider as an array of tables. Each entry has `name`, `type`, `api_base`, `api_key_env`, and a `models` array.
---@type fun(): table
provider.list = nil

--- Register provider middleware. `mw` is a table of `{ on_response = fn }`:
--- 
--- - `on_response(message)` - runs after the assistant message is fully assembled but before it's appended to history. `message` is the same `{ role = "assistant", content?, tool_calls? }` shape used everywhere else. Return a replacement table to mutate it; any other return leaves it as-is.
--- 
--- Hooks fire in registration order. Each hook sees the previous hook's replacement. Returns a `Reg` whose `:remove()` drops this middleware.
--- 
--- For streaming observation use `smelt.events.on("stream_delta", ...)` - synchronous mutation of mid-stream tokens isn't safe because the parser owns the partial state.
---@type fun(mw: table): smelt.Reg
provider.middleware = nil

--- Normalize a provider result or plain row list into renderable rows plus loading state.
---@type fun(result: table[]|table?, opts?: { show_message?: boolean, loading_message?: string }): smelt.provider.NormalizedResult
provider.normalize = nil

--- Declare a provider named `name`. Re-registering replaces the previous entry of the same name. Returns a `Reg` whose `:remove()` drops the provider.
---@type fun(name: string, cfg: smelt.provider.Config): smelt.Reg
provider.register = nil

--- Return true when the row list is exactly one synthetic status/message row.
---@type fun(rows: table[]?): boolean
provider.synthetic_only = nil

return provider
