---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Reasoning-effort selector. `smelt.reasoning.current()` reads the active effort, `smelt.reasoning.set(v)` sets it in a TUI session, and `smelt.reasoning.cycle_list()` lists the configured cycle.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.reasoning
local reasoning = {}

--- Return the active reasoning effort.
---@type fun(): string
reasoning.current = nil

--- Tier: UiHost - Requires a terminal UI; calling these from headless mode raises.
--- Advance the active reasoning effort to the next entry in
--- `smelt.reasoning.cycle_list()`, wrapping at the end. No-op when the
--- cycle is empty.
---@see smelt.reasoning.cycle_list
---@type fun(): nil
reasoning.cycle = nil

--- Return the configured reasoning-effort cycle.
---@type fun(): string[]
reasoning.cycle_list = nil

--- Return the reasoning-effort labels known by this smelt version. Models may advertise additional labels.
---@type fun(): string[]
reasoning.known_list = nil

--- Tier: UiHost - Requires a terminal UI; calling these from headless mode raises.
--- Set the active reasoning effort. The change is applied immediately to the UI and persisted according to the active remember policy.
---@type fun(effort: string): nil
reasoning.set = nil

return reasoning
