---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Reasoning-effort selector. `smelt.reasoning()` reads the active effort; `smelt.reasoning(v)` sets it (overridden by the TUI to apply the change). `smelt.reasoning.cycle_list()` lists the configured cycle.
---@class smelt.reasoning
local reasoning = {}

--- Tier: UiHost - Requires a terminal UI; calling these from headless mode raises.
--- Advance the active reasoning effort to the next entry in
--- `smelt.reasoning.cycle_list()`, wrapping at the end. No-op when the
--- cycle is empty.
---@see smelt.reasoning.cycle_list
---@type fun(): nil
reasoning.cycle = nil

--- Return the configured reasoning-effort cycle.
---@type fun(): smelt.reasoning.Effort[]
reasoning.cycle_list = nil

return reasoning
