---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Per-key opt-in to last-used recall on launch. `smelt.remember.set({ model = false })` makes that key always start from `smelt.defaults`, ignoring `recent.json`. Defaults to `true` for every key.
---@class smelt.remember
local remember = {}

--- Set which startup choices are remembered across launches. Accepts `{ model?, mode?, reasoning_effort? }`; omitted fields keep their current policy.
---@type fun(cfg: smelt.remember.Config): nil
remember.set = nil

return remember
