---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Paint text / markdown / syntax-highlighted code / split diffs into a `Buf`. UiHost-only.
---@class smelt.render
local render = {}

--- Paint a side-by-side diff between `opts.old` and `opts.new` into two buffers. Both buffers end up with the same row count; synthetic padding rows align them. Pick syntax via `opts.lang` or `opts.path`.
---@type fun(left: smelt.buf.Buf, right: smelt.buf.Buf, opts: table): nil
render.diff_split = nil

--- Render markdown `source` into the buffer using the same renderer the transcript uses for assistant text blocks.
---@type fun(buf: smelt.buf.Buf, source: string): nil
render.markdown = nil

--- Paint syntect-highlighted code from `opts.content` into the buffer as a plain block. Pick syntax via `opts.lang` or `opts.path`. Unknown languages fall back to plain text.
---@type fun(buf: smelt.buf.Buf, opts: table): nil
render.syntax = nil

--- Paint plain text into a buffer with dim/error body styling. `opts.is_error = true` switches to the error-message highlight group.
---@type fun(buf: smelt.buf.Buf, content: string, opts: table?): nil
render.text = nil

return render
