---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Paint text / markdown / syntax-highlighted code / diffs / notebook previews into a `Buf`. UiHost-only.
---@class smelt.render
local render = {}

--- Paint an inline diff between `opts.old` and `opts.new` into the buffer, syntax-highlighted by `opts.path`'s extension. Mirrors the pipeline used by the built-in confirm dialog.
---@type fun(buf: smelt.buf.Buf, opts: table): nil
render.diff = nil

--- Paint a side-by-side diff between `opts.old` and `opts.new` into two buffers — `left` gets the pre-edit view, `right` gets the post-edit view. Both buffers end up with the same row count: synthetic padding rows fill in wherever one side has fewer changes than the other, so vertical alignment between sides is exact. Pick the syntax via `opts.lang` or `opts.path`; `lang` wins when both are set.
---@type fun(left: smelt.buf.Buf, right: smelt.buf.Buf, opts: table): nil
render.diff_split = nil

--- Render markdown `source` into the buffer using the same renderer the transcript uses for assistant text blocks (headings, lists, code fences, inline emphasis).
---@type fun(buf: smelt.buf.Buf, source: string): nil
render.markdown = nil

--- Render a notebook edit preview into the buffer (insert mode shows the new source highlighted; edit mode shows an inline diff). `args` is the notebook tool's argument table.
---@type fun(buf: smelt.buf.Buf, args: table): nil
render.notebook = nil

--- Paint syntect-highlighted code from `opts.content` into the buffer as a plain block — one source line per row, no gutter, no line numbers. Indentation is the caller's responsibility. Pick the syntax via `opts.lang` (`"bash"`, `"rust"`, `"py"`, …) or `opts.path` (extension-sniffed); `lang` wins when both are set. Unknown languages fall back to plain text.
---@type fun(buf: smelt.buf.Buf, opts: table): nil
render.syntax = nil

--- Paint `opts.content` into the buffer with file-view metadata: each row gets `SourceLine::Linear` stamped so a `gutter = "line_numbers"` window draws the gutter. Pick the syntax via `opts.lang` or `opts.path`. Use this for write_file / notebook diffs; prefer `smelt.render.syntax` for plain snippets.
---@see smelt.render.syntax
---@type fun(buf: smelt.buf.Buf, opts: table): nil
render.syntax_file = nil

--- Paint plain text into a buffer with the dim/error body styling that the built-in tool render path uses. `opts.is_error = true` switches to the error-message highlight group.
---@type fun(buf: smelt.buf.Buf, content: string, opts: table?): nil
render.text = nil

return render
