---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Session slug. Use `smelt.session.slug.get()` to read it. Writing flows through `smelt.session.title.set(title, slug)`.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.session.slug
local session_slug = {}

--- Return the current session slug, or `nil` when it has not been set.
---@type fun(): string?
session_slug.get = nil

return session_slug
