---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Current session metadata, turn list, message snapshots, rewind, and persisted session management. UiHost-only.
---@class smelt.session
local session = {}

--- Install a model-context checkpoint without deleting transcript history. Takes `{ kind?, summary, first_live_message_index, tokens_before?, guard? }`; future model requests use the summary plus the original model-visible suffix starting at `first_live_message_index`. When `guard` from `smelt.work.guard()` is provided, the checkpoint is installed only if that lifecycle is still current; late callbacks after cancel or turn replacement return `nil`. Returns the model-visible messages after the checkpoint is installed, or `nil` when the boundary would be a no-op.
---@see smelt.work.guard
---@type fun(spec: table): table?
session.checkpoint = nil

--- Latest authoritative provider-reported active-context token count, or `nil` when Smelt does not currently have a valid reading for the model-visible history.
---@type fun(): integer?
session.context_tokens = nil

--- Configured context-window size in tokens for the active model. `nil` when the model entry has no declared limit.
---@type fun(): integer?
session.context_window = nil

--- Cumulative session cost in USD across every model call this session has made.
---@type fun(): number
session.cost = nil

--- Unix-epoch timestamp (milliseconds) at which this session was started.
---@type fun(): integer
session.created_at_ms = nil

--- Working directory the session was launched from. Stable across the session.
---@type fun(): string
session.cwd = nil

--- Delete the persisted session with `id`. Refuses to delete the currently active session.
---@type fun(id: string): nil
session.delete = nil

--- Absolute path of the on-disk session directory (transcript JSONL, attachments, ledger).
---@type fun(): string
session.dir = nil

--- Fork the current session: clone its messages into a new session id and switch to it. Useful for branching off an experiment without losing the original timeline.
---@type fun(): nil
session.fork = nil

--- Stable session id (matches the on-disk session filename).
---@type fun(): string
session.id = nil

--- List persisted sessions other than the current one. Each row carries `id`, `title`, `subtitle`, `cwd`, `parent_id`, `updated_at_ms`, `created_at_ms`, and `size_bytes` when available.
---@type fun(): table
session.list = nil

--- Switch the UI to the persisted session with `id`. Replays its message log and resets transient state.
---@type fun(id: string): nil
session.load = nil

--- Return the model-visible message list for the next request. If the session has a context checkpoint, this is the checkpoint summary plus retained live tail; otherwise it is the persisted transcript. Read-only.
---@type fun(): table
session.model_messages = nil

--- Cancel any in-flight agent and clear the session to a blank slate. Logs an `agent_stop` event with reason `user_cancel_and_clear`.
---@type fun(): nil
session.reset = nil

--- Rewind the session to a prior user turn. `block_idx = nil` rewinds to before the first turn; `opts.restore_vim_insert = true` re-enters vim insert mode after the rewind.
---@type fun(block_idx: integer?, opts: table?): nil
session.rewind_to = nil

--- Currently-assembled system prompt sent on the next turn. Reflects every prompt section (base, skills, instructions). Useful for auxiliary LLM calls that want to share the main turn's prompt-cache slot.
---@type fun(): string
session.system = nil

--- Return the searchable plain-text blob for session `id` (user + assistant text only; reasoning, tool output, and system messages excluded). Returns `nil` when the session is missing. Reads the `content.txt` sidecar; falls back to rebuilding from `session.json` and caching the sidecar for legacy sessions.
---@type fun(id: string): string?
session.text = nil

--- Parallel batch read of `session.text(id)` for many ids. Returns a table keyed by id; missing sessions are omitted. Use this when a picker needs to search across all sessions - the heavy IO happens on a worker pool rather than serializing on the Lua thread.
---@type fun(ids: string[]): table
session.texts = nil

--- Cumulative token usage across every turn this session has made. Returns a table with `input`, `output`, `cache_read`, `cache_write`, `reasoning`, `total` (input + output), and `cache_hit_ratio` (cache_read / (input + cache_read), `nil` if no input observed yet).
---@type fun(): table
session.tokens = nil

--- Arrange a flat list of session entries (as returned by `smelt.session.list`)
--- into a DFS-ordered tree by `parent_id`. Each returned entry gets a `depth`
--- field (0 = root, 1 = first-level fork, ...). Roots come first, sorted by
--- `opts.sort_by` descending (default `"updated_at_ms"`); each root is
--- immediately followed by its children, sorted by the same key.
--- 
--- Entries whose `parent_id` references an id not present in `entries` are
--- treated as roots - this is what makes the function safe under workspace
--- filtering, where a fork's parent may have been filtered out.
---@see smelt.session.list
---@type fun(entries: table[], opts: table?): table[]
session.tree = nil

--- Return user turns as `{ block_idx, label }` rows where `label` is the first line of the user message. Used by the rewind dialog.
---@type fun(): table
session.turns = nil

return session
