---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Session messages. `smelt.session.messages.list(opts?)` returns transcript rows as `{ role, content?, tool_calls?, tool_call_id?, is_error? }`; by default this reads a bounded tail. Pass `opts.limit`, `opts.since_index`, or `opts.all = true` for an explicit full read. Use `smelt.session.model_messages()` for the model-visible history after checkpointing.
---@class smelt.session.messages
local session_messages = {}

--- Return transcript messages, optionally filtered by `{ roles?, include_tool?, since_index?, limit?, all? }`. Without `all = true`, reads at most a bounded tail.
---@type fun(opts: table?): table
session_messages.list = nil

return session_messages
