---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Session messages. Callable: `messages()` (or `messages(opts)`) returns persisted transcript rows as `{ role, content?, tool_calls?, tool_call_id?, is_error? }`; pass `opts.roles`, `opts.include_tool`, `opts.since_index`, or `opts.limit` to filter. Use `smelt.session.model_messages()` for the model-visible history after checkpointing.
---@class smelt.session.messages
local session_messages = {}

return session_messages
