---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Session title. Use `smelt.session.title.get()` to read the current title and `smelt.session.title.set(title, slug?)` to write it. Writes update the task label and save the session.
---@class smelt.session.title
local session_title = {}

--- Return the current session title, or `nil` when it has not been set.
---@type fun(): string?
session_title.get = nil

--- Set the session title. When `slug` is omitted, one is derived from the title.
---@type fun(title: string, slug: string?): nil
session_title.set = nil

return session_title
