---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `register_fn` call in Rust instead.

--- Current session metadata, turn list, message snapshots, rewind, and persisted session management. UiHost-only.
---@class smelt.session
local session = {}

--- Most recent prompt-token count reported by the provider, or `nil` if no turn has completed yet.
---@type fun(): integer?
session.context_tokens = nil

--- Configured context-window size in tokens for the active model. `nil` when the model entry has no declared limit.
---@type fun(): integer?
session.context_window = nil

--- Cumulative session cost in USD across every model call this session has made.
---@type fun(): number
session.cost = nil

--- Unix-epoch timestamp (milliseconds) at which this session was started.
---@type fun(): integer
session.created_at_ms = nil

--- Working directory the session was launched from. Stable across the session.
---@type fun(): string
session.cwd = nil

--- Delete the persisted session with `id`. Refuses to delete the currently active session.
---@type fun(id: string): nil
session.delete = nil

--- Absolute path of the on-disk session directory (transcript JSONL, attachments, ledger).
---@type fun(): string
session.dir = nil

--- Fork the current session: clone its messages into a new session id and switch to it. Useful for branching off an experiment without losing the original timeline.
---@type fun(): nil
session.fork = nil

--- Stable session id (matches the on-disk session filename).
---@type fun(): string
session.id = nil

--- List persisted sessions other than the current one. Each row carries `id`, `title`, `subtitle`, `cwd`, `parent_id`, `updated_at_ms`, `created_at_ms`, and `size_bytes` when available.
---@type fun(): table
session.list = nil

--- Switch the UI to the persisted session with `id`. Replays its message log and resets transient state.
---@type fun(id: string): nil
session.load = nil

--- Snapshot the current session messages as `{ role, content?, tool_calls?, tool_call_id?, is_error? }` rows. Roles are `system`/`user`/`assistant`/`tool`.
---@type fun(): table
session.messages = nil

--- Cancel any in-flight agent and clear the session to a blank slate. Logs an `agent_stop` event with reason `user_cancel_and_clear`.
---@type fun(): nil
session.reset = nil

--- Rewind the session to a prior user turn. `block_idx = nil` rewinds to before the first turn; `opts.restore_vim_insert = true` re-enters vim insert mode after the rewind.
---@type fun(block_idx: integer?, opts: table?): nil
session.rewind_to = nil

--- Session title (a short summary derived from the first user message), or `nil` until the engine assigns one.
---@type fun(): string?
session.title = nil

--- Return user turns as `{ block_idx, label }` rows where `label` is the first line of the user message. Used by the rewind dialog.
---@type fun(): table
session.turns = nil

return session
