---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Session slug (read-only). Writing flows through `smelt.session.title(t, s)`.
---@class smelt.session.slug
local session_slug = {}

return session_slug
