---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Metatable-backed proxy table for preferences. Read and write keys directly (`settings.foo = true`, `settings.compact_threshold = 0.65`) or iterate with `pairs`. Values are typed per the schema; type mismatches raise. UiHost-only.
---@class smelt.settings
local settings = {}

--- Return the settings schema as an array of `{ key, kind, choices? }` rows. `kind` is `"bool"`, `"number"`, or `"string"`. `choices` is present for `"string"` keys with a closed value set. UIs use this to render every known setting without hand-maintaining a list.
---@type fun(): table
settings.schema = nil

return settings
