---@meta

-- Auto-generated by `cargo run -p tui --bin gen-lua-docs`.
-- Do not edit by hand; update the `register_fn` call in Rust instead.

--- Metatable-backed proxy table for boolean preferences. Read and write keys directly (`settings.foo = true`) or iterate with `pairs`. UiHost-only.
---@class smelt.settings
local settings = {}

return settings
