---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Shell command splitting and interactive/background-operator validators.
---@class smelt.shell
local shell = {}

--- Return a user-facing error message if `command` uses the shell `&` background operator, or `nil` otherwise.
---@type fun(command: string): string?
shell.check_background_op = nil

--- Return a user-facing error message if `command` would invoke an interactive program (editor, REPL, pager, `git -i`, etc.), or `nil` if it is safe to run non-interactively.
---@type fun(command: string): string?
shell.check_interactive = nil

--- Extract filesystem paths referenced by `command` for workspace permission checks.
---@type fun(command: string): string[]
shell.extract_paths = nil

--- Return true when `command` contains shell output redirection such as `>` or `>>`.
---@type fun(command: string): boolean
shell.has_output_redirection = nil

--- Split `command` into the sequence of subcommands separated by shell operators (`;`, `&&`, `||`, `|`). Operators themselves are dropped.
---@type fun(command: string): string[]
shell.split = nil

--- Split `command` into subcommands and pair each with the operator that followed it. Returns rows of `{ command = string, op = string? }`.
---@type fun(command: string): table
shell.split_with_ops = nil

return shell
