---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Named reactive values. `smelt.signal(name)` returns a sticky `Signal` handle with `:get`, `:set`, `:subscribe`, `:name`. `smelt.signal.new` declares a signal with an initial value. `smelt.signal.glob` subscribes across every name matching a glob pattern. Use `smelt.events.on` for event-shaped signals where only occurrences matter.
---@class smelt.signal
local signal = {}

--- Register `handler(name, value, previous)` for every signal whose name matches `pattern` (glob syntax). Returns a `Reg` whose `:remove()` drops the glob subscription.
---@type fun(pattern: string, handler: fun(arg1: string, arg2: any, arg3: any)): smelt.Reg
signal.glob = nil

--- Declare a signal named `name` with `initial` as its starting value. No-op if the signal already exists.
---@type fun(name: smelt.signal.Name, initial: any): nil
signal.new = nil

return signal
