---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- List and load skill content from the SkillLoader populated at startup.
---@class smelt.skills
local skills = {}

--- Load the skill named `name` and return `(content, nil)` on success or `(nil, err_string)` if the skill is missing or failed to load.
---@type fun(name: string): string?, string?
skills.content = nil

--- Return the names of every skill discovered by the loader as a Lua array. Empty when no skills are loaded.
---@type fun(): table
skills.list = nil

return skills
