---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- List and load skill content from the SkillLoader populated at startup. Markdown custom commands can opt into skill discovery with `agent_skill: true` (or `agent-skill: true`) in their frontmatter; the skill name is the command file stem. Loaded command skills are static context: slash-command arguments are not included, and shell output markers are not evaluated.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.skills
local skills = {}

--- Load the skill named `name` and return `(content, nil)` on success or `(nil, err_string)` if the skill is missing or failed to load.
---@type fun(name: string): string?, string?
skills.content = nil

--- Return every discovered skill as `{ name, description, source, location, shadowed }` rows sorted by name.
---@type fun(): table
skills.info = nil

--- Return the names of every skill discovered by the loader as a Lua array. Empty when no skills are loaded.
---@type fun(): table
skills.list = nil

return skills
