---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Shared spinner glyph and cadence for plugin animations. Pure rendering primitive — work-state tokens belong in `smelt.work`. UiHost-only.
---@class smelt.spinner
local spinner = {}

--- Return the current spinner glyph (single grapheme). Stays in sync with the prompt top-bar working indicator so plugin spinners animate together.
---@type fun(): string
spinner.glyph = nil

--- Return the spinner frame period in milliseconds. Use as the redraw interval to match the built-in cadence.
---@type fun(): integer
spinner.period_ms = nil

return spinner
