---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Snapshot host state for the Lua statusline composer. UiHost-only.
---@class smelt.statusline
local statusline = {}

--- Return the statusline state in one table per refresh: `tps` (tokens-per-second from the live or just-archived turn, when available), `vim`, `mode`, `permission_pending`, `running_procs`, `running_agents`, `task_label`, `settings`, and `position`. The working pill lives in the prompt top bar now; plugins that need work state read the `work_*` cells instead. Styles are not projected — look colors up by theme group in the composer. Returns an empty table when the app pointer is unavailable.
---@type fun(): table
statusline.snapshot = nil

return statusline
