---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Per-plugin state. `smelt.state.get(name)` returns an ephemeral table that survives `/reload` only; `smelt.state.persistent(name)` returns a JSON-backed wrapper that survives restarts too.
---@class smelt.state
local state = {}

--- Return an ephemeral state table. With an explicit name, returns the
--- table for that name. With no arg, returns the current plugin's scoped
--- table keyed by the current scope name. Raises if called with no arg
--- outside a module body (no scope active).
---@type fun(name?: string): table
state.get = nil

---@type fun(name: string, opts: { debounce_ms: integer? }?): table
state.persistent = nil

return state
