---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Per-plugin state. `smelt.state(name)` returns an ephemeral table that survives `/reload` only; `smelt.state.persistent(name)` returns a JSON-backed wrapper that survives restarts too.
---@class smelt.state
local state = {}

--- Persistent wrapper: backed by JSON under
--- `$XDG_STATE_HOME/smelt/plugins/<name>.json`. Top-level writes are
--- debounced and auto-saved; nested mutations require an explicit
--- `s.save()` call. Reads pass through to the loaded table.
---@type fun(name: string, opts: { debounce_ms: integer? }?): table
state.persistent = nil

return state
