---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Register/unregister statusline sources and snapshot composer state. UiHost-only.
---@class smelt.statusline
local statusline = {}

--- Register a Lua statusline source named `name`. The handler is called once per refresh and returns a single segment table or a list. Each segment is `{ text, style_group?, style?, priority?, align_right?, truncatable?, separated? }`: `style_group` names a theme group whose resolved style applies (e.g. `"SmeltModePlan"`); `style` is a `StyleDecl` overlay applied on top. Higher `priority` drops first; `truncatable` shrinks with `…` before being fully dropped; `separated` inserts ` · ` before this segment. `opts.align = "right"` makes the source's segments default to the right strip; later registrations replace earlier ones with the same name. Returns a `Reg` whose `:remove()` drops the source.
---@type fun(name: string, handler: fun(value: table): table, opts: smelt.statusline.RegisterOpts?): smelt.Reg
statusline.register = nil

--- Return the statusline state in one table per refresh: `working`/`throbber`, `vim`, `mode`, `permission_pending`, `running_procs`, `running_agents`, `task_label`, `settings`, and `position`. Styles are not projected — name a `style_group` on each segment instead. Returns an empty table when the app pointer is unavailable.
---@type fun(): table
statusline.snapshot = nil

--- Drop the statusline source registered under `name`. No-op if no such source exists.
---@type fun(name: string): nil
statusline.unregister = nil

return statusline
