---@meta

-- Auto-generated by `cargo run -p tui --bin gen-lua-docs`.
-- Do not edit by hand; update the `register_fn` call in Rust instead.

--- Paint syntect-highlighted code into a Buffer. UiHost-only.
---@class smelt.syntax
local syntax = {}

--- Paint syntect-highlighted code from `opts.content` into the buffer, picking the syntax from `opts.path`'s file extension. Falls back to plain text when no syntax matches.
---@type fun(buf_id: integer, opts: table): nil
syntax.render = nil

return syntax
