---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `register_fn` call in Rust instead.

--- Paint syntect-highlighted code into a Buffer. UiHost-only.
---@class smelt.syntax
local syntax = {}

--- Paint syntect-highlighted code from `opts.content` into the buffer as a plain block — one source line per row, no gutter, no line numbers. Indentation is the caller's responsibility. Pick the syntax via `opts.lang` (`"bash"`, `"rust"`, `"py"`, …) or `opts.path` (extension-sniffed); `lang` wins when both are set. Unknown languages fall back to plain text.
---@type fun(buf_id: integer, opts: table): nil
syntax.render = nil

return syntax
