---@meta

-- Auto-generated by `cargo run -p tui --bin gen-lua-docs`.
-- Do not edit by hand; update the `register_fn` call in Rust instead.

--- Yield-then-resume coroutine bridge: alloc and resume external tasks.
---@class smelt.task
local task = {}

--- Allocate and return a fresh external task id used to pair a yielded coroutine with a later `task.resume` call.
---@type fun(): integer
task.alloc = nil

--- Resume the yielded task `id` with `value`. The runtime delivers `value` as the return of the matching `coroutine.yield`.
---@type fun(id: integer, value: any): nil
task.resume = nil

return task
