---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Yield-then-resume coroutine bridge: alloc and resume external tasks.
--- Classification: Advanced - Documented low-level capability for plugins that need full control. It may evolve more freely than the Supported facade.
---@class smelt.task
local task = {}

--- Run `fns` concurrently; wait for all to finish. Returns an array of
--- results in the same order as the input. Errors from any branch
--- propagate; the remaining branches still complete and their results
--- are discarded. Must run inside a yielding context.
---@type fun(...: fun(): any): any[]
task.all = nil

--- Allocate and return a fresh external task id used to pair a yielded coroutine with a later `task.resume` call.
---@type fun(): integer
task.alloc = nil

--- Allocate an external task id, invoke `start(id)` to kick off whatever
--- will eventually call `smelt.task.resume(id, value)` (or resolve through
--- the Rust resume sink), and park until that resolution arrives. Returns
--- the resolved value. Raises `cancelled` if the task is cancelled while
--- parked. Plugin authors bridging custom Rust extensions use this to
--- avoid hand-rolling the alloc + start + wait dance.
---@type fun(start: fun(id: integer)): any
task.external = nil

--- Check whether an error value represents a task or engine-ask cancellation.
--- Matches both the task-runtime `RuntimeError("cancelled")` shape and the
--- engine-ask `{ kind = "cancelled", message = "..." }` shape.
---@type fun(err: any): boolean
task.is_cancelled = nil

--- Run `fns` concurrently; first to return wins. Returns the winner's
--- `(index, result)` as multi-value, mirroring `task.timeout`'s
--- `(value, err)` shape. All other branches are cancelled. Errors from
--- any branch propagate (losers cancelled first). Must run inside a
--- yielding context.
---@type fun(...: fun(): any): integer, any
task.race = nil

--- Resume the yielded task `id` with `value`. The runtime delivers `value` as the return of the matching `coroutine.yield`.
---@type fun(id: integer, value: any): nil
task.resume = nil

--- Run `fn` with an `ms`-millisecond deadline. Returns `(result, nil)` if
--- `fn` finishes in time, or `(nil, "timeout")` if the deadline fires
--- first - in which case `fn`'s coroutine is cancelled (any in-flight
--- `smelt.sleep` / `task.wait` raises `cancelled` and the coroutine
--- unwinds). Must run inside a yielding context.
---@type fun(ms: integer, fn: fun(): any): any, string?
task.timeout = nil

--- Park the running task until `smelt.task.resume(id, value)` fires. Returns the resumed value.
--- Pass `{ interactive = true }` (or `{ pauses_deadline = true }`) for user-facing
--- waits such as dialogs; tool watchdog deadlines do not count wall time spent
--- waiting for the user.
---@type fun(id: integer, opts?: table): any
task.wait = nil

return task
