---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Visual-width measurement. UiHost-only.
---@class smelt.text
local text = {}

--- Force `s` to occupy exactly `width` display cells: truncate when too long (appending `opts.suffix`, default `"…"`), pad when too short (with `opts.fill`, default `" "`). `opts.align` is `"left"` (default), `"right"`, or `"center"`. Use this for fixed-width UI slots — handles multi-byte and wide chars correctly so the result is always exactly `width` cells wide regardless of content.
---@type fun(s: string, width: integer, opts: table?): string
text.fit = nil

--- Format a USD cost with precision that scales to the magnitude: `$0.0042` under one cent, `$0.123` under one dollar, `$1.23` otherwise. Mirrors the format the prompt bar uses for session cost.
---@type fun(usd: number): string
text.format_cost = nil

--- Format `seconds` as a short human-readable duration: `42s`, `3m 12s`, `1h 5m 0s`. Used by the prompt-bar working indicator; useful for any plugin surfacing elapsed time.
---@type fun(seconds: integer): string
text.format_duration = nil

--- Format a raw token count as `1.2k`, `3.4m`, or the bare integer for values under 1000. Useful for compact statusline / banner displays.
---@type fun(n: integer): string
text.format_tokens = nil

--- Return the number of lines in `s`. Counts `\n` separators and adds one if the last line is unterminated; an empty string returns `0`. Matches the line count users see in a renderer that splits on `\n` without dropping the trailing partial line.
---@type fun(s: string): integer
text.line_count = nil

--- Lowercase `s`, replace non-alphanumeric runs with `-`, drop empty segments. Same algorithm the title plugin uses for fallback slugs.
---@type fun(s: string): string
text.slugify = nil

--- Truncate `s` to at most `max_bytes`, snapping to the previous UTF-8 char boundary. Returns `s` unchanged when it already fits; appends `suffix` when provided and truncation actually occurred. **Byte-based** — use `smelt.text.fit` instead when you need to fit into a terminal-cell budget.
---@see smelt.text.fit
---@type fun(s: string, max_bytes: integer, suffix: string?): string
text.truncate = nil

--- Return the visual column count of `s`. Lua's `#s` counts bytes; use this for sizing extmark ranges or computing column offsets so multi-byte and wide characters land correctly.
---@type fun(s: string): integer
text.width = nil

return text
