---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Read and write theme highlight groups, snapshot the current palette, and enumerate built-in color presets. UiHost-only. Highlight groups follow nvim's PascalCase convention (`Comment`, `SmeltAccent`, …). Writing `SmeltAccent` or `SmeltSlug` is special: it bumps the corresponding palette index and rebuilds dependent groups.
---@class smelt.theme
local theme = {}

--- Return the resolved foreground (or background) color for highlight group `group` (PascalCase: `Comment`, `ErrorMsg`, `SmeltAccent`, …) as a `{ ansi, rgb? }` table. Unknown groups resolve to the terminal's default fg.
---@type fun(group: string): table
theme.get = nil

--- Return `true` if the active theme is a light theme. Lets plugins flip glyphs or contrast levels based on the current palette.
---@type fun(): boolean
theme.is_light = nil

--- Alias theme role `from` to `to` so reads of `from` resolve to `to`'s current color. Lets plugins reuse semantic groups (`MyPluginAccent` → `SmeltAccent`).
---@type fun(from: string, to: string): nil
theme.link = nil

--- Built-in color presets for Lua-side pickers.
---@type fun(): table
theme.presets = nil

--- Set highlight group `group`'s color. Pass a `{ ansi = N }` or `{ rgb = { r, g, b } }` table; RGB snaps to the closest 256-color slot. Setting `SmeltAccent` or `SmeltSlug` also bumps the corresponding palette index and rebuilds dependent groups; other groups only have their fg replaced.
---@type fun(group: string, value: table): nil
theme.set = nil

--- Snapshot every known theme role and its current color into a `{ role = color }` table. Useful for theme-aware pickers and diagnostic dumps.
---@type fun(): table
theme.snapshot = nil

return theme
