---@meta

-- Auto-generated by `cargo run -p tui --bin gen-lua-docs`.
-- Do not edit by hand; update the `register_fn` call in Rust instead.

--- Read and write theme roles, snapshot the current palette, and enumerate built-in color presets. UiHost-only.
---@class smelt.theme
local theme = {}

--- Return the theme's accent color as a `{ ansi, rgb? }` table. Used to drive accent-tinted UI like the throbber and selected list rows.
---@type fun(): table
theme.accent = nil

--- Return the foreground color for theme `role` (e.g. `Comment`, `ErrorMsg`, `SmeltAccent`) as a `{ ansi, rgb? }` table. Raises if the role is unknown.
---@type fun(role: string): table
theme.get = nil

--- Return `true` if the active theme is a light theme. Lets plugins flip glyphs or contrast levels based on the current palette.
---@type fun(): boolean
theme.is_light = nil

--- Alias theme role `from` to `to` so reads of `from` resolve to `to`'s current color. Lets plugins reuse semantic groups (`MyPluginAccent` → `SmeltAccent`).
---@type fun(from: string, to: string): nil
theme.link = nil

--- Built-in color presets for Lua-side pickers.
---@type fun(): table
theme.presets = nil

--- Override theme `role`'s color with a `{ ansi = N }` or `{ rgb = { r, g, b } }` table. Takes effect on the next paint.
---@type fun(role: string, value: table): nil
theme.set = nil

--- Snapshot every known theme role and its current color into a `{ role = color }` table. Useful for theme-aware pickers and diagnostic dumps.
---@type fun(): table
theme.snapshot = nil

return theme
