---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- One-shot and recurring timer callbacks. Each call returns a `Reg` whose `:remove()` cancels the timer.
---@class smelt.timer
local timer = {}

--- Schedule `handler` to fire repeatedly every `ms` milliseconds. Returns a `Reg` whose `:remove()` stops the timer. Raises if `ms` is `0`.
---@type fun(ms: integer, handler: fun()): smelt.Reg
timer.every = nil

--- Schedule `handler` to run once after `ms` milliseconds. Returns a `Reg` whose `:remove()` cancels the timer before it fires.
---@type fun(ms: integer, handler: fun()): smelt.Reg
timer.set = nil

return timer
