---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Wall-clock time parsing and formatting. Host-tier so plugins can render provider timestamps consistently in both TUI and headless contexts.
---@class smelt.time
local time = {}

--- Format Unix seconds in the user's local time zone with a strftime-style format string.
---@type fun(timestamp: integer, format: string): string?
time.format = nil

--- Format Unix seconds in UTC with a strftime-style format string.
---@type fun(timestamp: integer, format: string): string?
time.format_utc = nil

--- Return the current Unix timestamp in seconds. Backed by the host clock so tests can freeze time by swapping in a virtual clock.
---@type fun(): integer
time.now = nil

--- Return the current Unix timestamp in milliseconds. Backed by the host clock so tests can freeze time by swapping in a virtual clock.
---@type fun(): integer
time.now_ms = nil

--- Parse an ISO-8601 / RFC3339 timestamp and return Unix seconds, not milliseconds, or nil when the input is invalid.
---@type fun(timestamp: string): integer?
time.parse_iso8601 = nil

return time
