---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Register, unregister, and resolve plugin tools for the engine.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.tools
local tools = {}

--- Classification: Advanced - Documented low-level capability for plugins that need full control. It may evolve more freely than the Supported facade.
--- Compact repeated absolute cwd prefixes in model-facing tool output. This is
--- display-only policy for structured path outputs, not a filesystem primitive.
---@type fun(path: any): any
tools._compact_cwd_path = nil

--- Classification: Advanced - Documented low-level capability for plugins that need full control. It may evolve more freely than the Supported facade.
--- Apply `_compact_cwd_path` to each path in an array, preserving order.
--- Returns an empty array when `paths` is `nil`.
---@type fun(paths: any): any
tools._compact_cwd_paths = nil

--- Classification: Advanced - Documented low-level capability for plugins that need full control. It may evolve more freely than the Supported facade.
--- Remove the active working-directory prefix from the start of each line in
--- model-facing text while preserving line endings. Returns `""` for `nil`.
---@type fun(content: any): any
tools._compact_cwd_prefix_lines = nil

--- Classification: Advanced - Documented low-level capability for plugins that need full control. It may evolve more freely than the Supported facade.
--- Attach an outer watchdog to a tool definition. This is intentionally
--- separate from the tool's own timeout handling: builtins use a small grace
--- period so their domain-specific timeout result wins before the watchdog fires.
---@type fun(def: any, opts: any): any
tools._with_watchdog = nil

--- Call another tool from within `execute`. Pass `parent_call_id` so streamed
--- output groups under the parent invocation. Returns `{ content, is_error, metadata? }`.
---@type fun(name: string, args: table?, parent_call_id: string?): { content: string, is_error: boolean?, metadata: table? }
tools.call = nil

--- Best-effort one-liner summary of a tool call's arguments. Picks a sensible field from `args` in priority order: `questions` (returns `"N question(s)"`), `pattern` (optionally suffixed with ` in <display path>`), then the first non-empty `command | file_path | notebook_path | path | url | query | name | id`. Returns `""` if nothing matches. Used as the default `summary` field on tools registered via `smelt.tools.register`.
---@see smelt.tools.register
---@type fun(args: table?): string
tools.default_summary = nil

--- Return the names of every registered plugin tool, sorted.
---@type fun(): table
tools.list = nil

--- Register middleware for tool `name`. Pass `""` (empty string) as `name` to match every tool. `mw` is a table of `{ before = fn?, after = fn? }`:
--- 
--- - `before(args, ctx)` runs synchronously before the tool executes. Return a table to replace `args`; return `{ deny = true, reason = "..." }` to short-circuit with an error result. Any other return is no-op.
--- - `after(args, ctx, result)` runs after the tool completes and may return `{ content, is_error }` to replace the result. NOTE: `after` currently only fires for tools that complete synchronously; yielding tools (most builtins) skip it until the task-runtime path is wired.
--- 
--- Hooks fire in registration order; an earlier hook's replacement is visible to later hooks. Returns a `Reg` whose `:remove()` drops this middleware.
---@type fun(name: string, mw: table): smelt.Reg
tools.middleware = nil

--- Patch metadata for an already-registered tool without replacing its handler. Supports `description` and `parameters`. Returns a `Reg` whose `:remove()` restores the previous metadata.
---@type fun(name: string, patch: table): smelt.Reg
tools.patch = nil

--- Format a path for a tool summary. During argument streaming, paths that may
--- collapse to the current working directory or home directory return an empty
--- string; once final, all paths use `smelt.path.display`.
---@see smelt.path.display
---@type fun(path: string, ctx?: { final: boolean }, opts?: { prefix: string?, suffix: string? }): string
tools.path_summary = nil

--- Register a plugin tool. See `smelt.tools.ToolDef` for every supported field; only `name` and `execute` are required. Returns a `Reg` whose `:remove()` unregisters the tool.
---@see smelt.tools.ToolDef
---@type fun(def: smelt.tools.ToolDef): smelt.Reg
tools.register = nil

--- Resolve the pending tool call `call_id` from request `request_id` with `{ content, is_error, metadata? }`. Sends a `ToolResult` back to the engine.
---@type fun(request_id: integer, call_id: string, result: table): nil
tools.resolve = nil

--- Unregister a previously-registered tool by `name`. Returns `true` if a tool was removed, `false` otherwise.
---@type fun(name: string): boolean
tools.unregister = nil

return tools
