---@meta

-- Auto-generated by `cargo run -p tui --bin gen-lua-docs`.
-- Do not edit by hand; update the `register_fn` call in Rust instead.

--- Read rendered transcript display text and yank the current block. UiHost-only.
---@class smelt.transcript
local transcript = {}

--- Return `text` from the app state.
---@type fun(): string
transcript.text = nil

--- Copy the transcript block under the cursor to the system clipboard. Notifies the user with the copied range; no-op when the cursor is outside any block.
---@type fun(): nil
transcript.yank_block = nil

return transcript
