---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Declarative transcript display grouping. Register adjacent-run group rules while the host owns deterministic planning and the composed root renderer presents resulting group nodes.
---@class smelt.transcript.groups
local transcript_groups = {}

--- Current group-registry cache key, or nil when any active group opted out of
--- persisted planning/layout caches.
---@type fun(): integer?
transcript_groups.cache_key = nil

--- Current group-registry generation. Rust render planning uses this to invalidate
--- plan/cache state once group planning is enabled.
---@type fun(): integer
transcript_groups.generation = nil

--- Return group specs in planner order: higher priority first, then registration order.
---@type fun(): smelt.transcript.GroupSpec[]
transcript_groups.list = nil

--- Register or replace a declarative transcript group type. This only declares
--- planning metadata; Rust owns deterministic adjacent-run planning and the
--- composed root transcript renderer presents resulting group nodes.
---@type fun(spec: smelt.transcript.GroupSpec): smelt.Reg
transcript_groups.register = nil

return transcript_groups
