---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Transcript display policy and rendered transcript inspection. Host-tier renderer hooks are layered with UiHost read APIs when a TUI is active.
---@class smelt.transcript
local transcript = {}

--- Tier: UiHost - Requires a terminal UI; calling these from headless mode raises.
--- Return the exact transcript block containing absolute display row `row`, or nil when the row is outside a block. This may materialize full block layout.
---@type fun(row: integer): table?
transcript.block_at_row = nil

--- Tier: UiHost - Requires a terminal UI; calling these from headless mode raises.
--- Return the nearest transcript block at or before absolute display row `row`, optionally filtered by `opts.role`. Uses the row index and does not materialize the full block layout.
---@type fun(row: integer, opts: table?): table?
transcript.block_before_or_at_row = nil

--- Tier: UiHost - Requires a terminal UI; calling these from headless mode raises.
--- Return the laid-out transcript blocks for the current frame as a list of `{ idx, role, first_row, rows, first_line }`. `idx` is 0-based into `session.messages` order (the same value `session.rewind_to(idx)` accepts). `role` is `"user"|"assistant"|"thinking"|"tool"|"code"|"exec"|"compacted"`. `first_row` is the absolute display row of the block's first visible line (compare against `win:scroll().top`). `rows` is the block's row count. `first_line` is the first non-empty line of the block's raw source text. Returns an empty list before the first frame projects.
---@type fun(): table
transcript.blocks = nil

--- Add or replace named middleware around the root renderer. Later extensions
--- run first. The callback receives `(next, block, ctx)` and may return its own
--- layout or delegate with `next(block, ctx)`. The returned `Reg` removes only
--- this registration instance. Omit `opts.cache_key` to opt out of persisted
--- DisplayIR while the middleware is active.
---@type fun(name: string, renderer: fun(next: fun(block: smelt.transcript.Block, ctx: smelt.transcript.Context): table?, block: smelt.transcript.Block, ctx: smelt.transcript.Context): table?, opts: table?): smelt.Reg
transcript.extend_renderer = nil

--- Tier: UiHost - Requires a terminal UI; calling these from headless mode raises.
--- Apply a fold action (`open` or `close`) to every current transcript render node.
---@type fun(action: string): boolean
transcript.fold_all = nil

--- Tier: UiHost - Requires a terminal UI; calling these from headless mode raises.
--- Apply a fold action (`toggle`, `peek`, `open`, `close`) to the render node at absolute display row `row`. Pass `{ explicit = true }` to require a collapsed summary/elision affordance row.
---@type fun(row: integer, action: string, opts: table?): boolean
transcript.fold_at_row = nil

--- Tier: UiHost - Requires a terminal UI; calling these from headless mode raises.
--- Apply a fold action (`toggle`, `peek`, `open`, or `close`) to every current block node with the given kind, e.g. `thinking`. `toggle` is aggregate: open all if any matching node is folded, otherwise close all.
---@type fun(kind: string, action: string): boolean
transcript.fold_kind = nil

--- Tier: UiHost - Requires a terminal UI; calling these from headless mode raises.
--- Apply a fold action (`toggle`, `peek`, `open`, `close`) to a typed render node id returned by `node_at_row(...).node_id`.
---@type fun(node_id: table, action: string): boolean
transcript.fold_node = nil

--- Return the current composed root transcript renderer, or nil before the
--- default renderer has been installed.
---@type fun(): (fun(block: smelt.transcript.Block, ctx: smelt.transcript.Context): table?)?
transcript.get_renderer = nil

--- Bump the renderer generation after changing closed-over state that affects
--- renderer output without calling `set_renderer`, `extend_renderer`, or a
--- registration's `:remove()`. This also opts out of persisted DisplayIR until
--- the renderer is installed again with a cache key.
---@type fun(): integer
transcript.invalidate_renderer = nil

--- Tier: UiHost - Requires a terminal UI; calling these from headless mode raises.
--- Return `true` when the transcript history holds no blocks (user, assistant, thinking, tool, exec, code, compacted). Reads `transcript.history` directly, so unlike `blocks()` it works before the first frame projects and is the right signal for empty-state plugins (logo splash, onboarding hints).
---@type fun(): boolean
transcript.is_empty = nil

--- Tier: UiHost - Requires a terminal UI; calling these from headless mode raises.
--- Return render-node metadata for absolute display row `row`, including `{ kind, id, node_id, block_id?, group_id?, index, first_row, rows, row_offset, view_state, explicit_fold_target }`, or nil when outside the transcript. `id`/`node_id` is a stable typed table `{ kind = "block"|"group", id = number }` accepted by `fold_node`.
---@type fun(row: integer): table?
transcript.node_at_row = nil

--- Tier: UiHost - Requires a terminal UI; calling these from headless mode raises.
--- Return rendered transcript display rows in `[start, start + count)`. This is exact for the requested absolute display-row range and materializes only the bounded range needed for the query.
---@type fun(start: integer, count: integer): table
transcript.rows = nil

--- Replace the base transcript renderer used when the host asks Lua for a
--- transcript block layout. Existing middleware registered with `extend_renderer`
--- remains wrapped around the new base. The renderer must return a `smelt.layout`
--- value; return `smelt.layout.empty()` to hide a block. Omit `opts.cache_key`
--- to opt out of persisted DisplayIR, or bump it whenever renderer output changes
--- across process restarts.
---@see smelt.layout.empty
---@type fun(renderer: fun(block: smelt.transcript.Block, ctx: smelt.transcript.Context): table?, opts: table?): nil
transcript.set_renderer = nil

--- Tier: UiHost - Requires a terminal UI; calling these from headless mode raises.
--- Create a transcript-shaped streaming renderer for `buf`. The returned object feeds deltas through the same incremental markdown parser and renderer used by the main transcript.
---@type fun(buf: smelt.buf.Buf, opts: smelt.transcript.StreamOpts?): smelt.transcript.Stream
transcript.stream = nil

--- Tier: UiHost - Requires a terminal UI; calling these from headless mode raises.
--- Return the full transcript as a single newline-joined string (post-render display text, using current transcript presentation state).
---@type fun(): string
transcript.text = nil

--- Tier: UiHost - Requires a terminal UI; calling these from headless mode raises.
--- Return the transcript blocks materialized in the current visible projection as `{ idx, role, first_row, rows, first_line }` entries. Unlike `blocks()`, this does not force full transcript materialization.
---@type fun(): table
transcript.visible_blocks = nil

return transcript
