---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Bundled default transcript entry points for rendering semantic blocks and raw tool output.
--- Classification: Advanced - Documented low-level capability for plugins that need full control. It may evolve more freely than the Supported facade.
---@class smelt.transcript.defaults
local transcript_defaults = {}

--- Render any semantic transcript block with the bundled default policy.
---@type fun(block: smelt.transcript.Block, ctx: smelt.transcript.Context): smelt.layout.Node
transcript_defaults.render = nil

--- Render raw tool output with the default gutter and rendered-row cap.
---@type fun(output: smelt.transcript.ToolOutput?, ctx: smelt.transcript.Context?, opts: table?): smelt.layout.Node
transcript_defaults.render_tool_output = nil

return transcript_defaults
