---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `register_fn` call in Rust instead.

--- Query and mutate the per-project content trust store.
---@class smelt.trust
local trust = {}

--- Mark the current working directory as trusted, persisting it in the user's trust store.
---@type fun(): string
trust.mark = nil

--- Return the trust state of the current working directory: `"trusted"`, `"untrusted"`, or `"no_content"`. Raises if the cwd cannot be read.
---@type fun(): string
trust.status = nil

return trust
