---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Screen-composition primitives: main layout composer and per-window renderer registration.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.ui
local ui = {}

--- Return the current terminal size as `{ width, height }` in cells. Useful for choosing between compact and wide overlay layouts without relying on any particular window's current rect.
---@type fun(): smelt.ui.Size
ui.size = nil

return ui
