---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Screen-composition primitives: main layout composer and per-window renderer registration.
---@class smelt.ui
local ui = {}

return ui
