---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `register_fn` call in Rust instead.

--- Composable layout-tree primitives (leaf/vbox/hbox) for overlays. The resulting userdata is passed to `smelt.ui.overlay.open` via `opts.layout`.
---@class smelt.ui.layout
local ui_layout = {}

--- Horizontal container. `items` is an array of `{ child_layout, width = <constraint>, collapse_when_empty = bool? }`. `opts` accepts `border`, `title`, `gap`.
---@type fun(items: table, opts: table?): smelt.ui.layout
ui_layout.hbox = nil

--- Wrap a window or paint id into a leaf node. `opts` accepts `border`, `title`, `collapse_when_empty` (force the slot to zero size when the wrapped window's buffer is empty).
---@type fun(id: integer, opts: table?): smelt.ui.layout
ui_layout.leaf = nil

--- Vertical container. `items` is an array of `{ child_layout, height = <constraint>, collapse_when_empty = bool? }`. `opts` accepts `border`, `title`, `gap` (cells between children).
---@type fun(items: table, opts: table?): smelt.ui.layout
ui_layout.vbox = nil

return ui_layout
