---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `register_fn` call in Rust instead.

--- Generic overlay composition from items and paint regions. UiHost-only.
---@class smelt.ui.overlay
local ui_overlay = {}

--- Open a generic overlay composed from `opts.items` (windows, paint regions, lines). Returns the overlay id so it can be focused or closed via `smelt.win`.
---@type fun(opts: table): integer
ui_overlay.open = nil

return ui_overlay
