---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `register_fn` call in Rust instead.

--- Picker overlay: open, set_items, set_selected. UiHost-only.
---@class smelt.ui.picker
local ui_picker = {}

--- Open a picker overlay configured by `opts` (`title`, `items`, `on_select`, ...). Returns the picker's `WinId` so callers can mutate items later via `set_items`/`set_selected`.
---@type fun(opts: table): integer
ui_picker._open = nil

return ui_picker
