---@meta

-- Auto-generated by `cargo run -p tui --bin gen-lua-docs`.
-- Do not edit by hand; update the `register_fn` call in Rust instead.

--- Shared spinner glyph and cadence for plugin animations. UiHost-only.
---@class smelt.ui.spinner
local ui_spinner = {}

--- Return the current spinner glyph (single grapheme). Stays in sync with the status bar's working pill so plugin spinners animate together.
---@type fun(): string
ui_spinner.glyph = nil

--- Return the spinner frame period in milliseconds. Use as the redraw interval to match the built-in cadence.
---@type fun(): integer
ui_spinner.period_ms = nil

return ui_spinner
