---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `LuaMod::fn_` call in Rust instead.

--- Read and write the vim mode of the focused vim-enabled surface. UiHost-only.
--- Classification: Supported - Primary alpha facade for user config and plugins.
---@class smelt.vim
local vim = {}

--- Return the vim mode of the focused surface, or `nil` if it isn't vim-enabled.
---@type fun(): smelt.vim.Mode?
vim.mode = nil

--- Switch the vim mode of the focused vim-enabled window. Raises on unknown values.
---@type fun(mode: smelt.vim.Mode): nil
vim.set_mode = nil

return vim
