---@meta

-- Auto-generated by `cargo xtask gen-lua-docs`.
-- Do not edit by hand; update the `register_fn` call in Rust instead.

--- Window lifecycle, focus, keymap/event registration, and buffer resolution. UiHost-only — windows are layout leaves that render a buffer onto the screen.
---@class smelt.win
local win = {}

--- Return the buffer id backing window `id`, or `nil` if no such window exists.
---@type fun(id: integer): integer?
win.buf = nil

--- Remove a per-window event handler by `callback_id` (returned from `on_event`). The associated Lua handle is freed.
---@type fun(win_id: integer, event: smelt.win.Event, callback_id: integer): nil
win.clear_event = nil

--- Remove a per-window key binding for `win_id` previously installed via `set_keymap`. The associated Lua handle is freed.
---@type fun(win_id: integer, key_str: string): nil
win.clear_keymap = nil

--- Close the overlay leaf identified by `id`. No-op if the window does not exist or is not an overlay leaf.
---@type fun(id: integer): nil
win.close = nil

--- Mark `win_id` as a single-line text input leaf with the same editing keymap as the prompt. If `placeholder` is non-empty, seed the buffer with dim placeholder text; the first printable keystroke clears it and starts a fresh line.
---@type fun(win_id: integer, placeholder: string?): nil
win.configure_input = nil

--- Mark `win_id` as a list leaf with arrow-key/scroll handling and place the initial cursor at row `initial_cursor` (clamped to `u16`).
---@type fun(win_id: integer, initial_cursor: integer?): nil
win.configure_list = nil

--- Return the current cursor row (0-based) of `win_id`, or `nil` if the window doesn't exist.
---@type fun(win_id: integer): integer?
win.cursor_row = nil

--- Return which top-level pane currently has focus: `"transcript"` or `"prompt"`.
---@type fun(): string
win.focus = nil

--- Move `win_id`'s cursor by `delta` rows (clamped to the buffer's line count), keep the row on-screen by adjusting `scroll_top`, and emit `selection_changed`. Lets an external panel (e.g. a docked search input) drive a list without holding focus.
---@type fun(win_id: integer, delta: integer): nil
win.move_cursor = nil

--- Subscribe `func` to event `event` on window `win_id`. Returns a callback id usable with `clear_event`.
---@type fun(win_id: integer, event: smelt.win.Event, func: fun(value: table)): integer
win.on_event = nil

--- Open a split window over the buffer `buf_id`. `opts.region` picks the layout slot (default `"lua_overlay"`); `opts.focusable`, `opts.cursor_line_highlight`, and `opts.vim_enabled` toggle behaviour. `opts.pad_left` / `opts.pad_right` reserve padding columns on either side. `opts.scrollbar` (default `true`) reserves the rightmost column for a scrollbar that paints only when content overflows — set `false` for cursor-driven UIs (lists, single-line inputs). `opts.gutter` enables a data-driven gutter column to the left of content: `"line_numbers"` installs the standard line-number gutter (diff-aware when the buffer carries diff `SourceLine` metadata); `"none"` / omitted disables it. Returns the new `WinId` or `nil` if no slot was available.
---@type fun(buf_id: integer, opts: table?): integer?
win.open = nil

--- Return the window's current viewport rect as `{ row, col, width, height }`, or `nil` until the first render lays it out.
---@type fun(id: integer): any
win.rect = nil

--- Place `win_id`'s cursor at absolute `row` (clamped to the buffer's line count). Adjusts `scroll_top` so the row stays on-screen and emits `selection_changed` if the position actually moved.
---@type fun(win_id: integer, row: integer): nil
win.set_cursor_row = nil

--- Move keyboard focus to window `id`. No-op if the window is not focusable or does not exist.
---@type fun(id: integer): nil
win.set_focus = nil

--- Install `func` as the handler for `key_str` on window `win_id`. Replaces any existing binding (the displaced Lua handle is freed). Raises on unknown key strings.
---@type fun(win_id: integer, key_str: string, func: fun(value: table)): nil
win.set_keymap = nil

return win
