---@meta

-- Auto-generated by `cargo run -p tui --bin gen-lua-docs`.
-- Do not edit by hand; update the `register_fn` call in Rust instead.

--- Window lifecycle, focus, keymap/event registration, and buffer resolution. UiHost-only — windows are layout leaves that render a buffer onto the screen.
---@class smelt.win
local win = {}

--- `smelt.win.buf(win_id) -> buf_id | nil`
---@type fun(id: integer): integer?
win.buf = nil

--- Remove a per-window event handler by `callback_id` (returned from `on_event`). The associated Lua handle is freed.
---@type fun(win_id: integer, event: smelt.win.Event, callback_id: integer): nil
win.clear_event = nil

--- Remove a per-window key binding for `win_id` previously installed via `set_keymap`. The associated Lua handle is freed.
---@type fun(win_id: integer, key_str: string): nil
win.clear_keymap = nil

--- Close the overlay leaf identified by `id`. No-op if the window does not exist or is not an overlay leaf.
---@type fun(id: integer): nil
win.close = nil

--- Mark `win_id` as a single-line text input leaf with the same editing keymap as the prompt.
---@type fun(win_id: integer): nil
win.configure_input = nil

--- Mark `win_id` as a list leaf with arrow-key/scroll handling and place the initial cursor at row `initial_cursor` (clamped to `u16`).
---@type fun(win_id: integer, initial_cursor: integer?): nil
win.configure_list = nil

--- Return `focus` from the app state.
---@type fun(): string
win.focus = nil

--- Return `mode` from the app state.
---@type fun(): string
win.mode = nil

--- Subscribe `func` to event `event` on window `win_id`. Returns a callback id usable with `clear_event`.
---@type fun(win_id: integer, event: smelt.win.Event, func: fun(value: table)): integer
win.on_event = nil

--- Open a split window over the buffer `buf_id`. `opts.region` picks the layout slot (default `"lua_overlay"`); `opts.focusable`, `opts.cursor_line_highlight`, and `opts.vim_enabled` toggle behaviour. Returns the new `WinId` or `nil` if no slot was available.
---@type fun(buf_id: integer, opts: table?): integer?
win.open = nil

--- `smelt.win.rect(win_id) -> {row, col, width, height} | nil` — nil until first render.
---@type fun(id: integer): any
win.rect = nil

--- `smelt.win.set_focus(win_id)`
---@type fun(id: integer): nil
win.set_focus = nil

--- Install `func` as the handler for `key_str` on window `win_id`. Replaces any existing binding (the displaced Lua handle is freed). Raises on unknown key strings.
---@type fun(win_id: integer, key_str: string, func: fun(value: table)): nil
win.set_keymap = nil

return win
